"""input/output management"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/002_io.ipynb.

# %% auto #0
__all__ = ['SaveImage', 'SaveImaged', 'LOADER_REGISTRY', 'LoadImage', 'LoadImaged', 'write_image', 'tiff2torch', 'string2dict',
           'split_path', 'is_ome_tiff', 'extract_formats', 'bioio_loader', 'split_hdf_path', 'hdf5_loader',
           'LoaderRegistry', 'image_reader', 'BioImageReader']

# %% ../nbs/002_io.ipynb #58b60095
# =================================
# Standard library
# =================================
import time
import re

# =================================
# Scientific / data
# =================================
import h5py
import numpy as np

# =================================
# Bioimage IO
# =================================
from bioio import BioImage as AICSImage
from bioio import Writer as writer
from bioio_tifffile import Reader as TiffReader
from bioio_ome_tiff import Reader as OmeTiffReader

# =================================
# Medical imaging
# =================================
from torchio import ScalarImage

# =================================
# fastai
# =================================
from fastai.data.all import *
from fastai.vision.all import *

# =================================
# MONAI
# =================================
from monai.transforms import LoadImage, LoadImaged, SaveImage, SaveImaged
from monai.data.image_reader import ImageReader
from collections.abc import Callable, Iterable, Sequence
from monai.config import PathLike
from monai.data import MetaTensor
from monai.data.utils import is_supported_format
from monai.utils import MetaKeys

# =================================
# bioMONAI
# =================================
from .utils import *

# %% ../nbs/002_io.ipynb #453fb47a
def write_image(data, file_path, dimension_order="TCZYX"):
    """
    Writes an image to a file.

    :param data: Image data (numpy array, tensor, or AICSImage)
    :param file_path: Path to save the image
    :param format: Format to save the image in (default is png)
    """
    if isinstance(data, torchTensor):
        data = data.numpy()
    elif isinstance(data, AICSImage):
        data = data.data

    if not isinstance(data, np.ndarray):
        raise ValueError("Unsupported data type. Expected numpy array, tensor, or AICSImage.")

    try:
        # file_path = file_path + '.' + format
        writer.save(data, file_path, dimension_order)
        print(f"Image successfully saved to {file_path}")
    except Exception as e:
        print(f"An error occurred while saving the image: {e}")


# %% ../nbs/002_io.ipynb #f820309d
SaveImage = SaveImage
SaveImaged = SaveImaged

# %% ../nbs/002_io.ipynb #c87d4d38
def tiff2torch(file_path: str):
    '''
    Load tiff into pytorch tensor
    '''
    import tifffile as tiff
    
    img = np.array(tiff.imread(file_path))
    return torch_from_numpy(img)

# %% ../nbs/002_io.ipynb #9c768b4a
def string2dict(s: str) -> dict[str, int | slice | None]:
    """
    Parse layout strings with:
        - sizes: C2
        - slices: Y[100:200]
        - steps:  Y[100:200:2]

    Returns:
        dict[str, int | slice | None]
    """

    result = {}

    pattern = re.findall(
        r"([A-Za-z])"               # axis
        r"(\d+)?"                   # optional size
        r"(?:\[(\d*):(\d*):?(\d*)\])?",  # optional slice w/ step
        s
    )

    for axis, size, start, stop, step in pattern:
        axis = axis.upper()

        # -------------------------
        # slice case
        # -------------------------
        if start or stop or step:
            slc = slice(
                int(start) if start else None,
                int(stop) if stop else None,
                int(step) if step else None,
            )
            result[axis] = slc

        # -------------------------
        # size case
        # -------------------------
        elif size:
            result[axis] = int(size)

        # -------------------------
        # empty axis
        # -------------------------
        else:
            result[axis] = None

    return result

# %% ../nbs/002_io.ipynb #f111048c
def split_path(file_path, # The path to the file to split
                   exts:(L, list)=['.ome.tiff', '.tiff', '.tif', '.png'] # List of filename extensions 
                   ):
    img_ext = [ext for ext in exts if ext in file_path]
    if img_ext == []:
        return file_path, dict()
    p = file_path.split(img_ext[0])
    if len(p) == 1 or p[1] == '':
        return file_path, dict()
    else:
        path = p[0] + img_ext[0]
        ind_dict = string2dict(p[1])
    return path, ind_dict

# %% ../nbs/002_io.ipynb #3f4aac4a
def is_ome_tiff(path: Path) -> bool:
    return path.suffixes[-2:] == [".ome", ".tiff"]

# %% ../nbs/002_io.ipynb #0ae336ba
def extract_formats(filenames: Sequence[str] | str) -> list[str | None]:
    """
    Extract file format(s) from one or multiple filenames.

    Supports:
        - standard extensions (.nii.gz, .png, .npz)
        - HDF5 internal paths (.hdf5/... or .h5/...)

    Args:
        filenames: single path or sequence of paths.

    Returns:
        List of format strings in uppercase (without dots),
        or None if no suffix is found.
    """

    if isinstance(filenames, (str, Path)):
        filenames = [filenames]

    formats = []

    for name in filenames:
        path_str = str(name).lower()

        # HDF5 special case
        if any(ext in path_str for ext in (".h5", ".hdf5")):
            formats.append("HDF5")
            continue

        # Standard suffixes
        suffixes = Path(name).suffixes
        if suffixes:
            fmt = "".join(suffixes).lstrip(".").upper()
            formats.append(fmt)
        else:
            formats.append(None)

    return formats

# %% ../nbs/002_io.ipynb #e1ba1c73
class bioio_loader():
    
    def __init__(self,
                 ind_dict=None, # Dictionary indicating the channels to load
                 loader=None, # Optional custom reader to use for loading the image
                 channels="CZYX" # The desired channel order for the output data
                ):
        store_attr()

    def __call__(self, path) -> Any:
        return self.image_reader(path)
    
    def image_reader(self, 
               path, # The file path to the image             
               ):

        """
        Loads an image from the specified path using AICSImage library.

        Parameters:
            path (str): The file path to the image.

        Returns:
            tuple: A tuple containing the image data and its affine transformation matrix.
                The image data is a NumPy array representing the image.
                The affine transformation matrix is a 4x4 NumPy array.
        """

        ind_dict = self.ind_dict
        if ind_dict == None:
            # parse path string
            path, ind_dict = split_path(str(path))
            
        # Support for tiff files    
        path = str(path)
        image_aics = AICSImage(path, reconstruct_mosaic=False, reader=self.loader)

        # Convert to numpy array    
        data = image_aics.get_image_data(self.channels, **ind_dict)
        # extract metadata
        meta = image_aics.metadata
        # Create an identity affine transformation matrix
        affine = np.eye(4)
        # Return the image data and the affine matrix
        return data, meta, affine


# %% ../nbs/002_io.ipynb #2bf5edc3
def split_hdf_path(file_path, # The path to the HDF5 file to split
                   hdf5_exts:(L, list)=['.h5','.hdf5'] # List of filename extensions 
                   ):
    hdf5_ext = [ext for ext in hdf5_exts if ext in file_path][0]
    if hdf5_ext == []:
        return file_path, None, None
    p = file_path.split(hdf5_ext)
    if len(p) == 1 or p[1] == '':
        return file_path, None, None
    else:
        path = p[0] + hdf5_ext
        dataset, patch = p[1].split('/')[1:]
        patch = int(patch)
    return path, dataset, patch

# %% ../nbs/002_io.ipynb #82d62082
class hdf5_loader():
    def __init__(self,
                 dataset=None, # The dataset to load
                 patch=0, # The patch to load from the dataset
                 hdf5_exts:(L, list)=['.h5','.hdf5'], # List of filename extensions 
                 channels="CYX" # The desired channel layout for the output data
                ):
        store_attr()

    def __call__(self, path) -> Any:
        return self.image_reader(path)
    
    def image_reader(self, 
               path, # The path to the HDF5 file to be read
               ):
        """
        Reads a *.h5 (HDF5 format) file and returns the image data along with an identity affine matrix.

        Parameters:
        path (str): The path to the file to be read.

        Returns:
        tuple: A tuple containing:
            - data (numpy.ndarray): The image data read from the file.
            - affine (numpy.ndarray): A 4x4 identity affine matrix.
        """
        
        # split path
        if self.dataset == None:
            path, dataset, patch = split_hdf_path(path, self.hdf5_exts)
            self.dataset = dataset
            self.patch = patch

        with h5py.File(path, 'r') as file:
                if self.dataset == None: print('List of datasets in this file: \n',list(file.keys())); return None
                else:
                    data = file[self.dataset + '/' + '%d'%(self.patch)][:] 
                    meta = dict(file[self.dataset + '/' + '%d'%(self.patch)].attrs)

        # adjust data dimensions according to channels layout
        while len(data.shape) < len(self.channels):
            # add absent dimensions assuming missing dimensions are at the beginning
            data = np.expand_dims(data, axis=0)
        if len(data.shape) > len(self.channels):
            # remove absent dimensions assuming that data is in CZYX order and missing dimensions are at the beginning
            data = data[(0,)*(data.ndim - len(self.channels)) + (slice(None),)*len(self.channels)]
                
        # Create a 4x4 identity affine NumpyArray
        affine = np.eye(4)

        # Return the image data and the affine matrix
        return data, meta, affine


# %% ../nbs/002_io.ipynb #d418d00e
def _preprocess(obj: MetaTensor, transforms: Callable|Iterable[Callable]|None=None) -> MetaTensor:
    """
    Apply a sequence of transforms to an image object.

    Args:
        obj: Input image object.
        transforms: Callable or list of callables.

    Returns:
        MetaTensor: Transformed object.
    """
    if transforms is None:
        transforms = []
    elif callable(transforms):
        transforms = [transforms]

    obj.meta['size_original'] = obj.shape
    obj.meta['transforms'] = {}

    for t in transforms:
        start = time.time()

        obj = t(obj)

        obj.meta['transforms'][t.__class__.__name__] = obj.meta['transforms'].get(t.__class__.__name__, [])
        obj.meta['transforms'][t.__class__.__name__] = {
                'time': time.time() - start,
                'params': getattr(t, "__dict__", {}),
        }

    obj.meta['size_after_tfms'] = obj.shape if hasattr(obj, "shape") else None

    return obj

# %% ../nbs/002_io.ipynb #c60c74aa
class LoaderRegistry:
    def __init__(self):
        self._loaders = {}

    def register(self, *suffixes):
        def decorator(fn):
            for s in suffixes:
                self._loaders[s.lower()] = fn
            return fn
        return decorator

    def get(self, path: Path):
        full_suffix = "".join(path.suffixes).lower()
        if full_suffix in self._loaders:
            return self._loaders[full_suffix]
        return self._loaders.get(path.suffix.lower())


LOADER_REGISTRY = LoaderRegistry()

# %% ../nbs/002_io.ipynb #22586921
def _load_default(path, ind_dict=None, loader=None, channels="CZYX", **kwargs):
    path_str = str(path)
    if ind_dict == None:
        path_str, ind_dict = split_path(path_str)
    data, meta, affine = bioio_loader(ind_dict, loader=loader, channels=channels)(path_str)

    return MetaTensor(x=data, affine=affine, meta=meta)



# %% ../nbs/002_io.ipynb #0bbc84e8
@LOADER_REGISTRY.register(".npy")
def _load_npy(path, **kwargs):
    data = np.load(path)
    return MetaTensor(x=data) 


# %% ../nbs/002_io.ipynb #27932955
@LOADER_REGISTRY.register(".npz")
def _load_npz(path, npz_key=None, **kwargs):
    npz_file = np.load(path)

    key = npz_key or next(iter(npz_file.keys()))
    if key not in npz_file:
        raise KeyError(f"Key '{key}' not found. Available: {list(npz_file.keys())}")

    return MetaTensor(x=npz_file[key])



# %% ../nbs/002_io.ipynb #6d8439bf
@LOADER_REGISTRY.register(".h5", ".hdf5")
def _load_hdf5(path, channels="CZYX", **kwargs):
    path_str = str(path)

    hdf5_ext = [ext for ext in ('.h5', '.hdf5') if ext in path_str]
    path, dataset, patch = split_hdf_path(path_str, hdf5_exts=hdf5_ext)

    data, meta, affine = hdf5_loader(dataset=dataset, patch=patch, hdf5_exts=hdf5_ext, channels=channels)(path)

    return MetaTensor(x=data, affine=affine, meta=meta)

# %% ../nbs/002_io.ipynb #44f42658
@LOADER_REGISTRY.register(".png")
def _load_png(path, ind_dict=None, channels="CZYX", loader=None, **kwargs):
    """
    Load a PNG image using AICSImage.

    Returns:
        ScalarImage containing the image tensor.
    """

    path_str = str(path)
    if ind_dict == None:
        path_str, ind_dict = split_path(path_str)
    channels = channels.replace("C", "S")
    data, meta, affine = bioio_loader(ind_dict, loader=loader, channels=channels)(path_str)

    return MetaTensor(x=data, affine=affine, meta=meta)

# %% ../nbs/002_io.ipynb #e4ff27ed
@LOADER_REGISTRY.register(".tiff", ".tif")
def _load_tiff(path, ind_dict=None, channels="CZYX", **kwargs):
    """
    Load a TIFF image using AICSImage.

    Returns:
        ScalarImage containing the image tensor.
    """

    path_str = str(path)
    if ind_dict == None:
        path_str, ind_dict = split_path(path_str)
    
    # ome.tiff require a separate loader than regular tiff
    if is_ome_tiff(Path(path_str)):
       image_loader = OmeTiffReader
    else:
        image_loader = TiffReader

    data, meta, affine = bioio_loader(ind_dict, loader=image_loader, channels=channels)(path_str)

    return MetaTensor(x=data, affine=affine, meta=meta)

# %% ../nbs/002_io.ipynb #42c796c8
def _get_loader(path: Path):
    """
    Select appropriate loader based on file format.

    Priority:
        1. registry-based loader (exact match)
        2. format-based fallback (via extract_formats)
        3. default loader
    """

    # 1. Registry-based detection (fast path)
    loader = LOADER_REGISTRY.get(path)
    if loader:
        return loader

    # 2. Format-based detection (HDF5-aware)
    fmt = extract_formats(path)[0]

    if fmt == "HDF5":
        return _load_hdf5

    # 3. Default fallback
    return _load_default

# %% ../nbs/002_io.ipynb #d9629282
def _load_and_preprocess(
    file_path: PathLike,
    transforms: Callable|Iterable[Callable]|None =None,
    loader: Callable|None =None,
    channels: str ="CZYX",
    ind_dict: dict|None =None,
    npz_key: str|None =None,
) -> MetaTensor:
    """
    Load image and apply preprocessing transforms.

    Also attaches file format metadata.
    """
    path = Path(file_path)

    image_loader = _get_loader(path)
    metatensor = image_loader(path, loader=loader, channels=channels, ind_dict=ind_dict, npz_key=npz_key)

    metatensor = _preprocess(metatensor, transforms)

    # format extraction
    metatensor.meta['format'] = extract_formats(path)[0]
    # save channels info
    metatensor.meta['layout'] = channels

    return metatensor

# %% ../nbs/002_io.ipynb #08b998f4
def _multi_sequence_stream(
    image_paths: Sequence[PathLike],
    transforms=None,
    loader=None,
    channels="CZYX",
    ind_dict=None,
    npz_key=None,
) -> Iterable[MetaTensor]:
    """
    Lazily yield preprocessed image samples.

    Args:
        image_paths: Iterable of file paths.
        transforms: Optional transforms.
        reader: Optional reader.
        npz_key: Optional NPZ key.

    Yields:
        tuple (image, metadata)
    """
    for p in image_paths:
        yield _load_and_preprocess(
            p,
            transforms=transforms,
            loader=loader,
            channels=channels,
            ind_dict=ind_dict,
            npz_key=npz_key,
        )

# %% ../nbs/002_io.ipynb #c4fc78a7
def _stack(input_metatensors: Sequence[MetaTensor], # The sequence of MetaTensors to stack
           stack_axis: str = "C",                   # The axis along which to stack the tensors (e.g., "S" for sequence)
           channels: str = "CZYX",                  # The desired channel order for the output tensor
           dtype: torch.dtype = torch.float32,      # The desired data type for the output tensor
           squeeze: bool = True,                    # Whether to squeeze singleton dimensions from the input tensors before stacking
           ) -> torch.Tensor:                       # The resulting stacked tensor
    """
    Stack a sequence of MetaTensors into a single tensor.
    Args:
        input_metatensors: The sequence of MetaTensors to stack
        stack_axis: The axis along which to stack the tensors (e.g., "S" for sequence)
        channels: The desired channel order for the output tensor
        dtype: The desired data type for the output tensor
        squeeze: Whether to squeeze singleton dimensions from the input tensors before stacking
    Returns:
        The resulting stacked tensor
    """
    metatensors = []
    for t in input_metatensors:

        if squeeze:
            t = t.squeeze()

        t = t.to(dtype)

        metatensors.append(t)

    # stack along a new dimension 
    output_metatensor = torch.stack(metatensors, dim=0)

    # CASE A: stack_axis NOT in channel_order → just insert new axis
    if stack_axis not in channels:
        # insert S as new semantic axis
        # (no fusion, no concat)
        output_metatensor.meta.update({'layout': stack_axis + channels})

        return output_metatensor
    
    # stack_axis EXISTS in channel_order → concatenate into that axis
    axis_idx = channels.index(stack_axis)

    # -------------------------------------------------
    # concatenate along stack_axis
    # -------------------------------------------------
    output_metatensor = torch.cat(
        torch.unbind(output_metatensor, dim=axis_idx),
        dim=axis_idx
    )

    return output_metatensor


def _meta_from_layout(shape: tuple[int, ...],           # The shape of the image tensor
                      layout: str                       # The channel layout string (e.g., "CZYX")
                      ) -> dict[str, int | str | None]: # A dictionary containing metadata extracted from the layout, including size, width, height, channels, depth, frames, sequence, mode, and kind.
    """
    Extract metadata from channel layout.
    Args:
        shape: The shape of the image tensor
        layout: The channel layout string (e.g., "CZYX")    
    Returns:
        A dictionary containing metadata extracted from the layout, including size, width, height, channels, depth, frames, sequence, mode, and kind.
     """

    _channel_modes = {1: "L", 3: "RGB"}
    
    if len(shape) != len(layout):
        raise ValueError(f"{shape} vs {layout}")

    axis_map = dict(zip(layout, shape))

    meta = {
        "size_output": tuple(shape),
        "width": axis_map.get("X"),
        "height": axis_map.get("Y"),
        "channels": axis_map.get("C"),
        "depth": axis_map.get("Z"),
        "frames": axis_map.get("T"),
        "sequence": axis_map.get("S"),
        MetaKeys.SPATIAL_SHAPE: tuple(axis_map[ax] for ax in "ZYX" if ax in axis_map),
    }

    # mode
    c = meta["channels"]
    meta["mode"] = (
        "L" if c is None else _channel_modes.get(c, f"multichannel ({c})")
    )

    # kind
    if meta["sequence"] is not None and meta["sequence"] > 1:
        meta["kind"] = "sequence"
    if meta["frames"] is not None and meta["frames"] > 1:
        meta["kind"] = "video"
    elif meta["depth"] is not None and meta["depth"] > 1:
        meta["kind"] = "volume"
    else:
        meta["kind"] = "image"

    if "C" in layout:
        meta[MetaKeys.ORIGINAL_CHANNEL_DIM] = layout.index("C")
    else:
        meta[MetaKeys.ORIGINAL_CHANNEL_DIM] = float("nan")

    return meta



# %% ../nbs/002_io.ipynb #f4177cc4
def image_reader(
    file_path: PathLike | Sequence[PathLike],           # The file path(s) to the image(s) to be read. Can be a single path or a sequence of paths for multi-image loading.
    lazy: bool = False,                                 # Whether to use lazy loading (streaming) for multi-image inputs. If True, returns an iterable of MetaTensors instead of a single stacked tensor.
    output: str = "tensor",                             # The desired output format. Options: "nparray", "nparray+meta", "tensor", "tensor+meta", "metatensor"
    transforms: Callable|list[Callable]|None = None,    # Optional transforms to apply to the loaded image(s). Can be a single callable or a list of callables.
    loader: Callable|None = None,                       # Optional custom reader to use for loading the image. If None, the loader will be selected based on file format.
    channels: str ="CZYX",                              # The desired channel layout for the output tensor. Should be compatible with the input data and the loader used.
    ind_dict: dict|None = None,                         # Optional dictionary indicating specific channels or slices to load. Keys should correspond to axes in the channel layout (e.g., {"Y": slice(0, 10)}).
    npz_key: str|None = None,                           # The key to use for loading data from .npz files.
    dtype=torch.float32,                                # The desired data type for the output tensor. Only applicable if output includes tensor formats.
    squeeze: bool = False,                              # Whether to squeeze singleton dimensions from the input tensors before stacking.
    stack_axis: str = "C",                              # The axis along which to stack multi-image inputs. Should be one of the characters in the channel layout (e.g., "C", "S") or a new axis if not present in the layout.
) -> (                                                  # The type of the returned value depends on the `output` parameter.
    MetaTensor
    | np.ndarray
    | tuple[np.ndarray, dict]
    | torch.Tensor
    | tuple[torch.Tensor, dict]
    | tuple[torch.Tensor, dict]                         
):
    """
    Main entry point for medical image loading.

    ----------------------------------------------------------------------
    OVERVIEW
    ----------------------------------------------------------------------
    Supports:
        - single image loading
        - multi-image / multi-sequence loading
        - lazy or eager execution
        - scalar, NumPy, tensor, and MetaTensor outputs
        - flexible axis control for multi-image stacking

    ----------------------------------------------------------------------
    AXIS MODEL
    ----------------------------------------------------------------------
    Two concepts define tensor layout:

    1. channels:
        Defines per-image axis layout (e.g. "CZYX")

    2. stack_axis:
        Defines how multi-image inputs are injected.

    RULES:

    CASE 1:
        If stack_axis is IN channels:
            → images are stacked along that axis (no new axis created)
            → that axis becomes sequence dimension

    CASE 2:
        If stack_axis is NOT in channels:
            → a new axis is created at stack_axis position
            → sequence dimension is inserted

    ----------------------------------------------------------------------
    OUTPUT MODES
    ----------------------------------------------------------------------
        "nparray"       -> np.ndarray
        "nparray+meta"  -> (np.ndarray, Meta or list[Meta])
        "tensor"        -> torch.Tensor
        "tensor+meta"   -> (torch.Tensor, Meta or list[Meta])
        "metatensor"    -> MetaTensor

    ----------------------------------------------------------------------
    """
    # loader
    def _load(p):
        return _load_and_preprocess(
            p,
            transforms=transforms,
            loader=loader,
            channels=channels,
            ind_dict=ind_dict,
            npz_key=npz_key,
        )

    def _iter_multi():
        if lazy:
            return _multi_sequence_stream(
                file_path,
                transforms=transforms,
                loader=loader,
                channels=channels,
                ind_dict=ind_dict,
                npz_key=npz_key,
            )
        return [_load(p) for p in file_path]

    

    def _to_numpy(tensor):
        return tensor.detach().cpu().numpy()

    # -------------------------------------------------
    # detect multi
    # -------------------------------------------------
    # if isinstance(file_path, Sequence) and not isinstance(file_path, (str, Path)) and len(file_path) == 1:
    #     file_path = file_path

    is_multi = isinstance(file_path, Sequence) and not isinstance(file_path, (str, Path))

    # =====================================================
    # MULTI CASE
    # =====================================================
    if is_multi:
        metatensors = _iter_multi()
        metatensor = _stack(metatensors, stack_axis=stack_axis, channels=channels, dtype=dtype, squeeze=squeeze)
        metatensor.meta.update(_meta_from_layout(metatensor.shape, metatensor.meta['layout']))

        if output == "metatensor":
            return metatensor

        if output == "tensor":
            return Tensor(metatensor)

        if output == "tensor+meta":
            return Tensor(metatensor), {i:m.meta for i, m in enumerate(metatensors)}

        if output == "nparray":
            return _to_numpy(metatensor)
        
        if output == "nparray+meta":
            return _to_numpy(metatensor), {i:m.meta for i, m in enumerate(metatensors)}


        raise ValueError(f"Unknown output mode: {output}")

    # =====================================================
    # SINGLE CASE
    # =====================================================
    metatensor = _load(file_path)
    metatensor.meta.update(_meta_from_layout(metatensor.shape, channels))

    if squeeze:
        metatensor = metatensor.squeeze()

    metatensor = metatensor.to(dtype)

    if output == "metatensor":
        return metatensor
    
    if output == "tensor":
        return Tensor(metatensor)

    if output == "tensor+meta":
        return Tensor(metatensor), metatensor.meta
    
    if output == "nparray":
        return _to_numpy(metatensor)

    if output == "nparray+meta":
        return _to_numpy(metatensor), metatensor.meta

    raise ValueError(f"Unknown output mode: {output}")

# %% ../nbs/002_io.ipynb #514dacd9
LoadImage = LoadImage
LoadImaged = LoadImaged

# %% ../nbs/002_io.ipynb #5a78f57f
class BioImageReader(ImageReader):
    def __init__(
        self,
        converter: Callable[[MetaTensor], MetaTensor] | None = None,  # A callable that takes a MetaTensor and returns a MetaTensor
        reverse_indexing: bool = False,
        **kwargs,
    ):
        super().__init__()
        self.converter = converter
        self.reverse_indexing = reverse_indexing
        self.kwargs = kwargs

    # --------------------------------------------------
    def verify_suffix(self, filename:Sequence[PathLike] | PathLike) -> bool:
        suffixes = self._get_supported_suffixes()
        return is_supported_format(filename, suffixes)


    def _get_supported_suffixes(self) -> list[str]:
        """
        Collect supported suffixes from loader registry.
        """
        suffixes = set()

        for loader in LOADER_REGISTRY.values():
            exts = getattr(loader, "suffixes", None)
            if exts:
                suffixes.update(exts)

        return list(suffixes)

    # --------------------------------------------------
    def read(self, data: PathLike | Sequence[PathLike] | np.ndarray, **kwargs) -> MetaTensor:
        kwargs_ = {**self.kwargs, **kwargs}
        if len(data) == 1 and isinstance(data, Sequence) and not isinstance(data, (str, Path)):
            data = data[0]

        mt = image_reader(
            data,
            output="metatensor",
            **kwargs_,
        )

        if self.converter:
            mt = self.converter(mt)

        return mt

    # --------------------------------------------------
    def get_data(self, img: MetaTensor) -> tuple[np.ndarray, dict]:

        if self.reverse_indexing and img.ndim >= 2:
            img = MetaTensor(
                x=img.swapaxes(-1, -2),
                meta=img.meta,
            )

        # extract numpy array
        array = img.as_tensor().cpu().numpy()

        # ensure plain dict
        meta = dict(img.meta)

        return array, meta 
    
    def _get_spatial_shape(self, img: MetaTensor):
        m = img.meta
        return tuple(
            v for v in (m.get("width"), m.get("height"), m.get("depth")) if v is not None
        )
