"""input/output management"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/02_io.ipynb.

# %% auto #0
__all__ = ['SaveImage', 'SaveImaged', 'registry', 'LoadImage', 'LoadImaged', 'write_image', 'tiff2torch', 'string2dict',
           'split_path', 'extract_formats', 'bioio_loader', 'split_hdf_path', 'hdf5_loader', 'TransformMetadata',
           'PreprocessMetadata', 'LoaderRegistry', 'image_reader']

# %% ../nbs/02_io.ipynb #58b60095
# =================================
# Standard library
# =================================
from typing import Any
from pathlib import Path, PurePath
from dataclasses import dataclass, field
import time


# =================================
# Scientific / data
# =================================
import h5py
import numpy as np

# =================================
# Bioimage IO
# =================================
from bioio import BioImage as AICSImage
from bioio import Writer as writer
from bioio_tifffile import Reader as TiffReader
from bioio_ome_tiff import Reader as OmeTiffReader

# =================================
# Medical imaging
# =================================
from torchio import ScalarImage

# =================================
# fastai
# =================================
from fastai.data.all import *
from fastai.vision.all import *

# =================================
# MONAI
# =================================
from monai.transforms import LoadImage, LoadImaged, SaveImage, SaveImaged
from monai.data.image_reader import ImageReader, _copy_compatible_dict, _stack_images
from collections.abc import Callable, Iterable, Sequence
from monai.config import PathLike
from monai.data import MetaTensor
from monai.data.utils import is_supported_format
from monai.utils import MetaKeys, ensure_tuple

# =================================
# bioMONAI
# =================================
from .core import L, torchTensor, torch_from_numpy

# %% ../nbs/02_io.ipynb #453fb47a
def write_image(data, file_path, dimension_order="TCZYX"):
    """
    Writes an image to a file.

    :param data: Image data (numpy array, tensor, or AICSImage)
    :param file_path: Path to save the image
    :param format: Format to save the image in (default is png)
    """
    if isinstance(data, torchTensor):
        data = data.numpy()
    elif isinstance(data, AICSImage):
        data = data.data

    if not isinstance(data, np.ndarray):
        raise ValueError("Unsupported data type. Expected numpy array, tensor, or AICSImage.")

    try:
        # file_path = file_path + '.' + format
        writer.save(data, file_path, dimension_order)
        print(f"Image successfully saved to {file_path}")
    except Exception as e:
        print(f"An error occurred while saving the image: {e}")


# %% ../nbs/02_io.ipynb #f820309d
SaveImage = SaveImage
SaveImaged = SaveImaged

# %% ../nbs/02_io.ipynb #c87d4d38
def tiff2torch(file_path: str):
    '''
    Load tiff into pytorch tensor
    '''
    import tifffile as tiff
    
    img = np.array(tiff.imread(file_path))
    return torch_from_numpy(img)

# %% ../nbs/02_io.ipynb #9c768b4a
def string2dict(input_string:str):
    # Create an empty dictionary
    result_dict = {}

    # Iterate over each character in the string
    for char in input_string:
        # Check if the character is a letter (assuming ASCII letters)
        if char.isalpha():
            # Assign the letter as a key and initialize its value to 0
            result_dict[char] = None

    # Now, iterate over each character again to assign numeric values
    for i, char in enumerate(input_string):
        if char.isdigit():
            # Find the corresponding letter (key) for this number (value)
            key = next((k for k, v in result_dict.items() if v is None), None)
            if key is not None:
                # Assign the numeric value to the found key
                result_dict[key] = int(char)
                
    return result_dict

# %% ../nbs/02_io.ipynb #f111048c
def split_path(file_path, # The path to the file to split
                   exts:(L, list)=['.ome.tiff', '.tiff', '.tif', '.png'] # List of filename extensions 
                   ):
    img_ext = [ext for ext in exts if ext in file_path]
    if img_ext == []:
        return file_path, dict()
    p = file_path.split(img_ext[0])
    if len(p) == 1 or p[1] == '':
        return file_path, dict()
    else:
        path = p[0] + img_ext[0]
        ind_dict = string2dict(p[1])
    return path, ind_dict

# %% ../nbs/02_io.ipynb #0ae336ba
def extract_formats(filenames: Sequence[str] | str) -> list[str | None]:
    """
    Extract file format(s) from one or multiple filenames.

    Supports:
        - standard extensions (.nii.gz, .png, .npz)
        - HDF5 internal paths (.hdf5/... or .h5/...)

    Args:
        filenames: single path or sequence of paths.

    Returns:
        List of format strings in uppercase (without dots),
        or None if no suffix is found.
    """

    if isinstance(filenames, (str, Path)):
        filenames = [filenames]

    formats = []

    for name in filenames:
        path_str = str(name).lower()

        # HDF5 special case
        if any(ext in path_str for ext in (".h5", ".hdf5")):
            formats.append("HDF5")
            continue

        # Standard suffixes
        suffixes = Path(name).suffixes
        if suffixes:
            fmt = "".join(suffixes).lstrip(".").upper()
            formats.append(fmt)
        else:
            formats.append(None)

    return formats

# %% ../nbs/02_io.ipynb #e1ba1c73
class bioio_loader():
    def __init__(self,
                 ind_dict=None, # Dictionary indicating the channels to load
                 loader=None, # Optional custom reader to use for loading the image
                 channels="CZYX" # The desired channel order for the output data
                ):
        store_attr()

    def __call__(self, path) -> Any:
        return self.image_reader(path)
    
    def image_reader(self, 
               path, # The file path to the image             
               ):

        """
        Loads an image from the specified path using AICSImage library.

        Parameters:
            path (str): The file path to the image.

        Returns:
            tuple: A tuple containing the image data and its affine transformation matrix.
                The image data is a NumPy array representing the image.
                The affine transformation matrix is a 4x4 NumPy array.
        """

        ind_dict = self.ind_dict
        if ind_dict == None:
            # parse path string
            path, ind_dict = split_path(str(path))
            
        # Support for tiff files    
        path = str(path)
        image_aics = AICSImage(path, reconstruct_mosaic=False, reader=self.loader)

        # Convert to numpy array    
        data = image_aics.get_image_data(self.channels, **ind_dict)
        # Create an identity affine transformation matrix
        affine = np.eye(4)
        # Return the image data and the affine matrix
        return data, affine


# %% ../nbs/02_io.ipynb #2bf5edc3
def split_hdf_path(file_path, # The path to the HDF5 file to split
                   hdf5_exts:(L, list)=['.h5','.hdf5'] # List of filename extensions 
                   ):
    hdf5_ext = [ext for ext in hdf5_exts if ext in file_path][0]
    if hdf5_ext == []:
        return file_path, None, None
    p = file_path.split(hdf5_ext)
    if len(p) == 1 or p[1] == '':
        return file_path, None, None
    else:
        path = p[0] + hdf5_ext
        dataset, patch = p[1].split('/')[1:]
        patch = int(patch)
    return path, dataset, patch

# %% ../nbs/02_io.ipynb #82d62082
class hdf5_loader():
    def __init__(self,
                 dataset=None, # The dataset to load
                 patch=0, # The patch to load from the dataset
                 hdf5_exts:(L, list)=['.h5','.hdf5'], # List of filename extensions 
                ):
        store_attr()

    def __call__(self, path) -> Any:
        return self.image_reader(path)
    
    def image_reader(self, 
               path, # The path to the HDF5 file to be read
               ):
        """
        Reads a *.h5 (HDF5 format) file and returns the image data along with an identity affine matrix.

        Parameters:
        path (str): The path to the file to be read.

        Returns:
        tuple: A tuple containing:
            - data (numpy.ndarray): The image data read from the file.
            - affine (numpy.ndarray): A 4x4 identity affine matrix.
        """
        
        # split path
        if self.dataset == None:
            path, dataset, patch = split_hdf_path(path, self.hdf5_exts)
            self.dataset = dataset
            self.patch = patch

        with h5py.File(path, 'r') as file:
                if self.dataset == None: print('List of datasets in this file: \n',list(file.keys())); return None
                else:
                    data = file[self.dataset + '/' + '%d'%(self.patch)][:] 

        # Create a 4x4 identity affine NumpyArray
        affine = np.eye(4)

        # Return the image data and the affine matrix
        return data, affine


# %% ../nbs/02_io.ipynb #e8248528
@dataclass
class TransformMetadata:
    """
    Metadata for a single transform applied during preprocessing.

    Attributes:
        name: Name of the transform class.
        time: Execution time in seconds.
        params: Dictionary of transform parameters.
    """
    name: str
    time: float
    params: dict[str, Any]


@dataclass
class PreprocessMetadata:
    """
    Metadata container for preprocessing.

    Attributes:
        original_size: Shape before preprocessing.
        final_size: Shape after preprocessing.
        transforms: List of applied transforms.
        format: File format(s) (e.g. NIFTI, HDF5, PNG).
    """
    original_size: tuple
    final_size: tuple | None = None
    transforms: list[TransformMetadata] = field(default_factory=list)
    format: str | None = None
    channels: str | None = None

# %% ../nbs/02_io.ipynb #d418d00e
def _preprocess(obj: ScalarImage, transforms: Callable|Iterable[Callable]|None=None) -> tuple[ScalarImage, PreprocessMetadata]:
    """
    Apply a sequence of transforms to an image object.

    Args:
        obj: Input image object.
        transforms: Callable or list of callables.

    Returns:
        tuple:
            - transformed object
            - PreprocessMetadata
    """
    if transforms is None:
        transforms = []
    elif callable(transforms):
        transforms = [transforms]

    metadata = PreprocessMetadata(original_size=obj.shape[1:])

    for t in transforms:
        start = time.time()

        obj = t(obj)

        metadata.transforms.append(
            TransformMetadata(
                name=t.__class__.__name__,
                time=time.time() - start,
                params=getattr(t, "__dict__", {}),
            )
        )

    metadata.final_size = obj.shape[1:] if hasattr(obj, "shape") else None

    return obj, metadata

# %% ../nbs/02_io.ipynb #c60c74aa
class LoaderRegistry:
    def __init__(self):
        self._loaders = {}

    def register(self, *suffixes):
        def decorator(fn):
            for s in suffixes:
                self._loaders[s.lower()] = fn
            return fn
        return decorator

    def get(self, path: Path):
        full_suffix = "".join(path.suffixes).lower()
        if full_suffix in self._loaders:
            return self._loaders[full_suffix]
        return self._loaders.get(path.suffix.lower())


registry = LoaderRegistry()

# %% ../nbs/02_io.ipynb #22586921
def _load_default(path, ind_dict=None, loader=None, channels="CZYX", **kwargs):
    path_str = str(path)
    if ind_dict == None:
        path_str, ind_dict = split_path(path_str)
    reader = bioio_loader(ind_dict, loader=loader, channels=channels)

    return ScalarImage(path_str, reader=reader)



# %% ../nbs/02_io.ipynb #0bbc84e8
@registry.register(".npy")
def _load_npy(path, **kwargs):
    data = np.load(path)
    return ScalarImage(tensor=data)


# %% ../nbs/02_io.ipynb #27932955
@registry.register(".npz")
def _load_npz(path, npz_key=None, **kwargs):
    npz_file = np.load(path)

    key = npz_key or next(iter(npz_file.keys()))
    if key not in npz_file:
        raise KeyError(f"Key '{key}' not found. Available: {list(npz_file.keys())}")

    return ScalarImage(tensor=npz_file[key])



# %% ../nbs/02_io.ipynb #6d8439bf
@registry.register(".h5", ".hdf5")
def _load_hdf5(path, **kwargs):
    path_str = str(path)

    hdf5_ext = [ext for ext in ('.h5', '.hdf5') if ext in path_str]
    path, dataset, patch = split_hdf_path(path_str, hdf5_exts=hdf5_ext)

    reader = hdf5_loader(dataset=dataset, patch=patch, hdf5_exts=hdf5_ext)

    return ScalarImage(path, reader=reader)

# %% ../nbs/02_io.ipynb #44f42658
@registry.register(".png")
def _load_png(path, ind_dict=None, channels="CZYX", loader=None, **kwargs):
    """
    Load a PNG image using AICSImage.

    Returns:
        ScalarImage containing the image tensor.
    """

    path_str = str(path)
    path_str, ind_dict = split_path(path_str)
    channels = channels.replace("C", "S")
    reader = bioio_loader(ind_dict, channels=channels, loader=loader)

    return ScalarImage(path_str, reader=reader)

# %% ../nbs/02_io.ipynb #e4ff27ed
@registry.register(".tiff", ".tif")
def _load_tiff(path, ind_dict=None, channels="CZYX", **kwargs):
    """
    Load a TIFF image using AICSImage.

    Returns:
        ScalarImage containing the image tensor.
    """

    path_str = str(path)
    path_str, ind_dict = split_path(path_str)
    
    # ome.tiff require a separate loader than regular tiff
    if (path[-8:]=="ome.tiff"):
       image_loader = OmeTiffReader
    else:
        image_loader = TiffReader

    reader = bioio_loader(ind_dict, loader=image_loader, channels=channels)

    return ScalarImage(path_str, reader=reader)

# %% ../nbs/02_io.ipynb #42c796c8
def _get_loader(path: Path):
    """
    Select appropriate loader based on file format.

    Priority:
        1. registry-based loader (exact match)
        2. format-based fallback (via extract_formats)
        3. default loader
    """

    # 1. Registry-based detection (fast path)
    loader = registry.get(path)
    if loader:
        return loader

    # 2. Format-based detection (HDF5-aware)
    fmt = extract_formats(path)[0]

    if fmt == "HDF5":
        return _load_hdf5

    # 3. Default fallback
    return _load_default

# %% ../nbs/02_io.ipynb #d9629282
def _load_and_preprocess(
    file_path,
    transforms: Callable|Iterable[Callable]|None =None,
    loader: Callable|None =None,
    channels: str ="CZYX",
    ind_dict: dict|None =None,
    npz_key: str|None =None,
) -> tuple[ScalarImage, PreprocessMetadata]:
    """
    Load image and apply preprocessing transforms.

    Also attaches file format metadata.
    """
    path = Path(file_path)

    image_loader = _get_loader(path)
    img = image_loader(path, loader=loader, channels=channels, ind_dict=ind_dict, npz_key=npz_key)

    img, meta = _preprocess(img, transforms)

    # format extraction
    meta.format = extract_formats(path)[0]
    # save channels info
    meta.channels = channels

    return img, meta

# %% ../nbs/02_io.ipynb #08b998f4
def _multi_sequence_stream(
    image_paths,
    transforms=None,
    loader=None,
    channels="CZYX",
    ind_dict=None,
    npz_key=None,
) -> Iterable[tuple[ScalarImage, PreprocessMetadata]]:
    """
    Lazily yield preprocessed image samples.

    Args:
        image_paths: Iterable of file paths.
        transforms: Optional transforms.
        reader: Optional reader.
        npz_key: Optional NPZ key.

    Yields:
        tuple (image, metadata)
    """
    for p in image_paths:
        yield _load_and_preprocess(
            p,
            transforms=transforms,
            loader=loader,
            channels=channels,
            ind_dict=ind_dict,
            npz_key=npz_key,
        )

# %% ../nbs/02_io.ipynb #f4177cc4
def image_reader(
    file_path: str | Path | list[str|Path] | Sequence[str|Path],
    lazy: bool = False,
    output: str = "tensor",
    transforms: Callable|list[Callable]|None = None,
    loader: Callable|None = None,
    channels: str ="CZYX",
    ind_dict: dict|None = None,
    npz_key: str|None = None,
    dtype=torch.float32,
    squeeze: bool = False,
    stack_axis: str = "C",
) -> (
    ScalarImage
    | list[ScalarImage]
    | tuple[ScalarImage, PreprocessMetadata]
    | tuple[list[ScalarImage], list[PreprocessMetadata]]
    | torch.Tensor
    | tuple[torch.Tensor, PreprocessMetadata]
    | tuple[torch.Tensor, list[PreprocessMetadata]]
    | MetaTensor
):
    """
    Main entry point for medical image loading.

    ----------------------------------------------------------------------
    OVERVIEW
    ----------------------------------------------------------------------
    Supports:
        - single image loading
        - multi-image / multi-sequence loading
        - lazy or eager execution
        - scalar, tensor, and MetaTensor outputs
        - flexible axis control for multi-image stacking

    ----------------------------------------------------------------------
    AXIS MODEL
    ----------------------------------------------------------------------
    Two concepts define tensor layout:

    1. channels:
        Defines per-image axis layout (e.g. "CZYX")

    2. stack_axis:
        Defines how multi-image inputs are injected.

    RULES:

    CASE 1:
        If stack_axis is IN channels:
            → images are stacked along that axis (no new axis created)
            → that axis becomes sequence dimension

    CASE 2:
        If stack_axis is NOT in channels:
            → a new axis is created at stack_axis position
            → sequence dimension is inserted

    ----------------------------------------------------------------------
    OUTPUT MODES
    ----------------------------------------------------------------------
        "scalar"        -> ScalarImage or list[ScalarImage]
        "scalar+meta"   -> (ScalarImage, Meta) or (list, list)
        "tensor"        -> torch.Tensor
        "tensor+meta"   -> (torch.Tensor, Meta or list[Meta])
        "metatensor"    -> MetaTensor

    ----------------------------------------------------------------------
    """

    # loader
    def _load(p):
        return _load_and_preprocess(
            p,
            transforms=transforms,
            loader=loader,
            channels=channels,
            ind_dict=ind_dict,
            npz_key=npz_key,
        )

    def _is_multi(x):
        return isinstance(x, (list, tuple)) or (
            isinstance(x, Iterable) and not isinstance(x, (str, Path))
        )

    def _iter_multi():
        if lazy:
            return _multi_sequence_stream(
                file_path,
                transforms=transforms,
                loader=loader,
                channels=channels,
                ind_dict=ind_dict,
                npz_key=npz_key,
            )
        return (_load(p) for p in file_path)

    # tensor builder
    def _stack(imgs):

        tensors = []
        for img in imgs:
            t = img.data

            if squeeze:
                t = t.squeeze()

            t = t.to(dtype)

            tensors.append(t)

        # stack along a new dimension 
        t = torch.stack(tensors, dim=0)

        # CASE A: stack_axis NOT in channel_order → just insert new axis
        if stack_axis not in channels:
            # insert S as new semantic axis
            # (no fusion, no concat)

            return t
        
        # stack_axis EXISTS in channel_order → concatenate into that axis
        axis_idx = channels.index(stack_axis)

        # -------------------------------------------------
        # move stack dim (0) next to target axis
        # -------------------------------------------------
        perm = list(range(t.ndim))

        perm.remove(0)
        perm.insert(axis_idx + 1, 0)

        t = t.permute(*perm)

        # -------------------------------------------------
        # concatenate along stack_axis
        # -------------------------------------------------
        t = torch.cat(
            torch.unbind(t, dim=axis_idx + 1),
            dim=axis_idx
        )

        return t

    # -------------------------------------------------
    # detect multi
    # -------------------------------------------------
    is_multi = _is_multi(file_path)

    # =====================================================
    # MULTI CASE
    # =====================================================
    if is_multi:
        imgs, metas = zip(*_iter_multi())

        if output == "scalar":
            return list(imgs)

        if output == "scalar+meta":
            return list(imgs), list(metas)

        tensor = _stack(imgs)

        if output == "tensor":
            return tensor

        if output == "tensor+meta":
            return tensor, list(metas)

        if output == "metatensor":
            return MetaTensor(
                x=tensor,
                meta=[m.__dict__ for m in metas],
            )

        raise ValueError(f"Unknown output mode: {output}")

    # =====================================================
    # SINGLE CASE
    # =====================================================
    img, meta = _load(file_path)

    if output == "scalar":
        return img

    if output == "scalar+meta":
        return img, meta

    tensor = img.data

    if squeeze:
        tensor = tensor.squeeze()

    tensor = tensor.to(dtype)

    if output == "tensor":
        return tensor

    if output == "tensor+meta":
        return tensor, meta

    if output == "metatensor":
        return MetaTensor(x=tensor, meta=meta.__dict__)

    raise ValueError(f"Unknown output mode: {output}")

# %% ../nbs/02_io.ipynb #514dacd9
LoadImage = LoadImage
LoadImaged = LoadImaged
