"""Metric tracking and analysis tools"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/060_metrics.ipynb.

# %% auto #0
__all__ = ['METRIC_BACKENDS', 'register_metric_backend', 'FastaiMetricMixin', 'MetricBackend', 'MonaiMetricBackend',
           'FastaiMetricBackend', 'BioMetric', 'MSEMetric', 'SSIMMetric', 'PSNRMetric', 'MSSSIMMetric', 'MAEMetric',
           'RMSEMetric', 'DiceFastaiMetric', 'DiceMetric', 'IoUMetric', 'GeneralizedDiceScore', 'PanopticQualityMetric',
           'ROCAUCFastaiMetric', 'ROCAUCMetric', 'AveragePrecisionMetric', 'ConfusionMatrixMetric',
           'HausdorffDistanceMetric', 'SurfaceDistanceMetric', 'SurfaceDiceMetric', 'FIDMetric', 'MMDMetric',
           'MetricsReloadedBinaryFastai', 'MetricsReloadedBinary', 'MetricsReloadedCategorical', 'FRCLossMetric',
           'FRCMetric', 'VarianceMetric', 'LabelQualityScore']

# %% ../nbs/060_metrics.ipynb #09106178
# =================================
# PyTorch
# =================================
from torch import (
    abs,
    argmax,
    complex64,
    div,
    isnan,
    is_tensor,
    isinf,
    real,
    sigmoid,
    where,
    zeros_like,
)
from torch.nn.functional import one_hot, softmax

# =================================
# fastai
# =================================
import fastai.metrics as fm
from fastai.vision.all import AvgMetric, Metric, partial

# =================================
# MONAI
# =================================
import monai.metrics as mm

# =================================
# bioMONAI
# =================================
from .losses import FRCLoss
from .utils import *

# %% ../nbs/060_metrics.ipynb #05d4562d
METRIC_BACKENDS = {}

def register_metric_backend(name):
    """Register a metric backend."""
    def decorator(backend):
        if name in METRIC_BACKENDS:
            raise ValueError(f"Metric backend already registered: {name}")
        METRIC_BACKENDS[name] = backend
        return backend

    return decorator

# %% ../nbs/060_metrics.ipynb #da277220
class FastaiMetricMixin:
    """
    Mixin that adapts an epoch-level metric to the fastai ``Metric`` interface.

    The mixin is designed to be combined with native metric implementations
    such as MONAI metrics. It provides the fastai metric lifecycle while
    leaving metric computation, accumulation, and aggregation to the native
    implementation.

    Predictions are obtained from ``learn.pred``. Targets are obtained from
    ``learn.yb`` and normalized to a single target tensor when fastai stores
    them in a tuple or list.

    Subclasses can override ``_prepare`` when the native metric requires a
    specific representation of predictions or targets.
    """

    def __init__(self, *args, name=None, **kwargs):
        super().__init__(*args, **kwargs)
        self._name = name or self.__class__.__name__.removesuffix("Metric")

    @property
    def name(self):
        """Name exposed to the fastai training loop."""
        return self._name

    def _get_target(self, yb):
        """
        Extract the target tensor from fastai's target representation.

        Fastai normally stores targets in ``learn.yb`` as a tuple, but simple
        learners or tests may provide a tensor directly. When a tuple or list
        is provided, the first element is assumed to be the primary target.

        Parameters
        ----------
        yb : torch.Tensor, tuple, or list
            Target representation stored by the learner.

        Returns
        -------
        torch.Tensor
            Target tensor used by the metric.
        """
        if isinstance(yb, (tuple, list)):
            return yb[0]

        return yb

    def _prepare(self, pred, target):
        """
        Prepare predictions and targets before metric computation.

        The default implementation returns both inputs unchanged. Subclasses
        can override this method when the native metric requires a specific
        representation.

        Parameters
        ----------
        pred : torch.Tensor
            Predictions produced by the learner.

        target : torch.Tensor
            Normalized target tensor.

        Returns
        -------
        tuple
            Prepared ``(pred, target)`` pair.
        """
        return pred, target

    def accumulate(self, learn):
        """
        Accumulate metric statistics for the current batch.

        Parameters
        ----------
        learn : fastai.Learner
            Learner containing the predictions and targets for the current
            batch.
        """
        target = self._get_target(learn.yb)

        pred, target = self._prepare(
            learn.pred,
            target,
        )

        self(pred, target)

    @property
    def value(self):
        """Return the aggregated metric value."""
        value = self.aggregate()

        if isinstance(value, tuple):
            value = value[0]

        if hasattr(value, "numel") and value.numel() == 1:
            return value.item()

        return value

# %% ../nbs/060_metrics.ipynb #7cd10510
class MetricBackend:
    """
    Base class for metric backend adapters.

    A backend converts a metric class and its constructor arguments into the
    metric implementation required by a training framework.
    """

    def create(self, metric_cls, *args, **kwargs):
        """
        Instantiate a metric for the backend.

        Parameters
        ----------
        metric_cls : type
            Metric class to instantiate.
        *args
            Positional arguments passed to the metric constructor.
        **kwargs
            Keyword arguments passed to the metric constructor.

        Returns
        -------
        object
            Instantiated metric.
        """
        return metric_cls(*args, **kwargs)


# %% ../nbs/060_metrics.ipynb #3261f51c
@register_metric_backend("monai")
class MonaiMetricBackend(MetricBackend):
    """
    Backend for native MONAI metrics.

    MONAI metrics are instantiated directly without additional adaptation.
    """

    pass


# %% ../nbs/060_metrics.ipynb #20beaab1
@register_metric_backend("fastai")
class FastaiMetricBackend(MetricBackend):
    """
    Backend for metrics used with the fastai training engine.

    Explicit fastai metric implementations are instantiated directly.
    Metrics that do not provide a fastai-specific implementation are adapted
    dynamically by combining their native implementation with
    ``FastaiMetricMixin``.
    """

    def create(self, metric_cls, *args, **kwargs):
        """
        Create a fastai-compatible metric.

        Parameters
        ----------
        metric_cls : type
            Metric implementation to instantiate.
        *args
            Positional arguments passed to the metric constructor.
        **kwargs
            Keyword arguments passed to the metric constructor.

        Returns
        -------
        object
            Fastai-compatible metric instance.
        """
        if (
            issubclass(metric_cls, Metric)
            or issubclass(metric_cls, FastaiMetricMixin)
        ):
            return metric_cls(*args, **kwargs)

        adapted_cls = type(
            f"Fastai{metric_cls.__name__}",
            (FastaiMetricMixin, metric_cls),
            {},
        )

        return adapted_cls(*args, **kwargs)

# %% ../nbs/060_metrics.ipynb #0661c10a
class BioMetric:
    default_backend = "monai"
    _default = None

    @classmethod
    def _get_metric(cls, backend):
        metric_cls = getattr(cls, f"_{backend}", None)

        if metric_cls is None:
            metric_cls = cls._default

        if metric_cls is None:
            raise ValueError(
                f"No metric implementation for backend '{backend}' "
                f"and no default implementation defined."
            )

        return metric_cls

    @classmethod
    def _create_metric(cls, backend, *args, **kwargs):
        metric_cls = cls._get_metric(backend)

        try:
            backend_cls = METRIC_BACKENDS[backend]
        except KeyError:
            raise ValueError(f"Unknown metric backend: {backend}")

        return backend_cls().create(metric_cls, *args, **kwargs)

    @property
    def name(self):
        return self.__class__.__name__

    def __new__(cls, *args, backend=None, **kwargs):
        backend = backend or cls.default_backend
        return cls._create_metric(backend, *args, **kwargs)

# %% ../nbs/060_metrics.ipynb #4960aa4d
class MSEMetric(BioMetric):
    _default = mm.MSEMetric


class SSIMMetric(BioMetric):
    _default = mm.SSIMMetric


class PSNRMetric(BioMetric):
    _default = mm.PSNRMetric


class MSSSIMMetric(BioMetric):
    _default = mm.MultiScaleSSIMMetric


class MAEMetric(BioMetric):
    _default = mm.MAEMetric


class RMSEMetric(BioMetric):
    _default = mm.RMSEMetric

# %% ../nbs/060_metrics.ipynb #925bfd79
class DiceFastaiMetric(FastaiMetricMixin, mm.DiceMetric):
    """
    Fastai-compatible adapter for MONAI's ``DiceMetric``.

    This class combines ``FastaiMetricMixin`` with MONAI's ``DiceMetric`` so
    that Dice computation remains fully delegated to MONAI while the metric
    exposes the interface required by the fastai training loop.

    Predictions produced by a fastai segmentation model are converted to the
    representation expected by MONAI before metric computation:

    * single-channel predictions are converted to binary masks using a
      sigmoid activation followed by a threshold of ``0.5``;
    * multi-channel predictions are converted to discrete class labels using
      ``argmax`` over the channel dimension;
    * targets without a channel dimension are expanded with a singleton
      channel dimension.

    All constructor arguments are forwarded directly to MONAI's
    ``DiceMetric``.

    Parameters
    ----------
    include_background : bool, default=True
        Whether to include the background class in the Dice computation.
    reduction : str, default="mean"
        Reduction method used to combine Dice scores.
    get_not_nans : bool, default=False
        Whether to return the number of non-NaN values used in the reduction.
    ignore_empty : bool, default=True
        Whether to ignore samples with an empty target segmentation.
    num_classes : int, optional
        Number of classes when using single-channel label maps.
    return_with_label : bool or list of str, default=False
        Whether to return Dice values together with their labels.
    per_component : bool, default=False
        Whether to compute Dice independently for each binary component.
    **kwargs
        Additional arguments accepted by MONAI's ``DiceMetric``.

    Notes
    -----
    The metric itself is implemented by MONAI. ``FastaiMetricMixin`` only
    provides the fastai metric lifecycle and calls ``_prepare`` before
    delegating to MONAI's ``__call__`` implementation.
    """

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self._name = "Dice"

    def _prepare(self, pred, target):
        """
        Convert fastai predictions and targets to MONAI Dice inputs.

        Parameters
        ----------
        pred : torch.Tensor
            Model predictions. Expected shape is ``(B, C, ...)`` for
            channel-based segmentation outputs.
        target : torch.Tensor
            Ground-truth segmentation labels.

        Returns
        -------
        tuple
            Prepared ``(pred, target)`` pair suitable for MONAI's
            ``DiceMetric``.
        """
        # Binary segmentation: one output channel
        if pred.ndim == target.ndim + 1:
            if pred.shape[1] == 1:
                pred = (torch.sigmoid(pred) > 0.5).float()

            # Multi-class segmentation
            else:
                pred = pred.argmax(dim=1, keepdim=True)

        # Add channel dimension to label-map targets
        if target.ndim == pred.ndim - 1:
            target = target.unsqueeze(1)

        return pred, target

# %% ../nbs/060_metrics.ipynb #a63e7732
class DiceMetric(BioMetric):
    """
    Compute the Dice coefficient for segmentation tasks.

    The Dice coefficient measures the spatial overlap between predicted and
    target segmentations. The metric supports single-channel label maps for
    multi-class segmentation as well as multi-channel representations for
    class-wise or multi-label segmentation.

    Parameters
    ----------
    include_background : bool, default=True
        Whether to include the background channel in the computation.

    reduction : str, default="mean"
        Reduction method used to combine per-sample and per-channel Dice
        scores. Common options include ``"mean"``, ``"sum"``,
        ``"mean_batch"``, ``"sum_batch"``, and ``"none"``.

    get_not_nans : bool, default=False
        If ``True``, also return the number of non-NaN values used in the
        reduction.

    ignore_empty : bool, default=True
        Whether to ignore cases where the target segmentation is empty.
        If ``True``, empty target regions do not contribute to the metric.

    num_classes : int, optional
        Number of classes when the input is provided as a single-channel
        label map. This may be required when the number of classes cannot be
        inferred from the input.

    return_with_label : bool or list of str, default=False
        If ``True``, return Dice values together with their class labels.
        A list of labels can be provided to explicitly name the classes.

    per_component : bool, default=False
        If ``True``, compute the Dice score independently for each binary
        component.

    Examples
    --------
    Compute the mean Dice score while excluding the background::

        dice = DiceMetric(
            include_background=False,
            reduction="mean",
        )

    Compute per-class Dice scores::

        dice = DiceMetric(
            include_background=False,
            reduction="none",
        )

    Notes
    -----
    The default backend uses MONAI's ``DiceMetric`` implementation. The
    fastai backend uses ``DiceFastaiMetric``, which combines MONAI's metric
    implementation with ``FastaiMetricMixin`` to provide the interface
    required by the fastai training loop.
    """

    _default = mm.DiceMetric
    _fastai = DiceFastaiMetric

# %% ../nbs/060_metrics.ipynb #37db4336
class IoUMetric(BioMetric):
    _default = mm.MeanIoU

# %% ../nbs/060_metrics.ipynb #fb8decf3
class GeneralizedDiceScore(BioMetric):
    _default = mm.GeneralizedDiceScore

# %% ../nbs/060_metrics.ipynb #7df2d770
class PanopticQualityMetric(BioMetric):
    """
    Wrapper around monai.metrics.PanopticQualityMetric.

    Expects:
        pred  : (B, C, H, W) logits
        target: (B, H, W) or (B, 1, H, W) panoptic map
                Each pixel contains encoded panoptic label
                (semantic + instance id).

    All kwargs are forwarded to MONAI PanopticQualityMetric.
    """
    _default = mm.PanopticQualityMetric
    # pq_metric = mm.PanopticQualityMetric(**kwargs)

    # def PQ(pred, target):
    #     # Convert logits to discrete labels
    #     # pred = pred.argmax(dim=1)  # (B, H, W)

    #     if target.ndim == 4 and target.shape[1] == 1:
    #         target = target.squeeze(1)

    #     pq_metric.reset()
    #     pq_metric(y_pred=pred, y=target)
    #     return pq_metric.aggregate()

    # return AvgMetric(PQ)

# %% ../nbs/060_metrics.ipynb #249510e0
class ROCAUCFastaiMetric(FastaiMetricMixin, mm.ROCAUCMetric):
    """
    Fastai-compatible adapter for MONAI's ``ROCAUCMetric``.

    Optionally applies an activation function and converts class-index
    predictions and targets to one-hot representations before delegating
    computation to MONAI.

    Parameters
    ----------
    num_classes : int, optional
        Number of classes. If provided, class-index predictions and targets
        are converted to one-hot representations when necessary.

    act : callable, optional
        Activation function applied to predictions before metric computation.

    *args
        Positional arguments passed to ``ROCAUCMetric``.

    **kwargs
        Additional arguments passed to ``ROCAUCMetric``.
    """

    def __init__(
        self,
        num_classes=None,
        act=None,
        *args,
        **kwargs,
    ):
        self.num_classes = num_classes
        self.act = act

        super().__init__(*args, **kwargs)

        self._name = "ROCAUC"

    def _maybe_one_hot(self, x):
        """Convert class-index data to one-hot representation when needed."""
        if self.num_classes is None:
            return x

        if x.ndim > 1 and x.shape[1] == self.num_classes:
            return x

        return one_hot(
            x.long(),
            num_classes=self.num_classes,
        )

    def _prepare(self, pred, target):
        """Prepare predictions and targets for MONAI's ROC-AUC metric."""
        if self.act is not None:
            pred = self.act(pred)

        if self.num_classes is not None:
            pred = self._maybe_one_hot(pred)
            target = self._maybe_one_hot(target)

        return pred, target

# %% ../nbs/060_metrics.ipynb #a86d7472
class ROCAUCMetric(BioMetric):
    """
    Compute the area under the receiver operating characteristic curve
    (ROC-AUC) using MONAI.

    ROC-AUC summarizes the ability of a model to distinguish between
    positive and negative classes across all possible classification
    thresholds. For multiclass problems, MONAI supports different
    reduction strategies for combining the per-class AUC values.

    Parameters
    ----------
    average : str, default="macro"
        Reduction method used to combine AUC values across classes.
        The available options depend on the underlying MONAI
        implementation.

    get_not_nans : bool, default=False
        If ``True``, also return the number of valid, non-NaN AUC
        values when aggregating the metric.

    kwargs
        Additional keyword arguments are passed directly to MONAI's
        :class:`monai.metrics.ROCAUCMetric`.

    Notes
    -----
    With ``backend="fastai"``, predictions are optionally activated and
    converted to one-hot representations by ``ROCAUCFastaiMetric`` before
    being passed to MONAI.

    With the default MONAI backend, ``num_classes`` and ``act`` are not
    interpreted by this wrapper; they are specific to the fastai adapter.

    Examples
    --------
    Compute macro-averaged ROC-AUC with the default MONAI backend::

        metric = ROCAUCMetric()

    Use the metric with the fastai backend::

        metric = ROCAUCMetric(backend="fastai")

    """
    _default = mm.ROCAUCMetric
    _fastai = ROCAUCFastaiMetric

# %% ../nbs/060_metrics.ipynb #06247a60
class AveragePrecisionMetric(BioMetric):
    _default = mm.AveragePrecisionMetric

# %% ../nbs/060_metrics.ipynb #65149c1d
class ConfusionMatrixMetric(BioMetric):
    _default = mm.ConfusionMatrixMetric

# %% ../nbs/060_metrics.ipynb #06bef472
class HausdorffDistanceMetric(BioMetric):
    _default = mm.HausdorffDistanceMetric

# %% ../nbs/060_metrics.ipynb #a13fc7d6
class SurfaceDistanceMetric(BioMetric):
    _default = mm.SurfaceDistanceMetric

# %% ../nbs/060_metrics.ipynb #0481a590
class SurfaceDiceMetric(BioMetric):
    _default = mm.SurfaceDiceMetric

# %% ../nbs/060_metrics.ipynb #33fa9b46
class FIDMetric(BioMetric):
    _default = mm.FIDMetric

# %% ../nbs/060_metrics.ipynb #54b110e4
class MMDMetric(BioMetric):
    _default = mm.MMDMetric

# %% ../nbs/060_metrics.ipynb #bfad25b6
class MetricsReloadedBinaryFastai(FastaiMetricMixin, mm.MetricsReloadedBinary):
    """
    Fastai-compatible adapter for MONAI's ``MetricsReloadedBinary``.

    This class combines ``FastaiMetricMixin`` with MONAI's
    ``MetricsReloadedBinary`` implementation. It adapts the target produced
    by fastai, which is stored in ``learn.yb`` as a tuple, to the tensor
    expected by the MONAI metric.

    Parameters
    ----------
    metric_name : str
        Name of the MetricsReloaded metric to compute.

    *args
        Positional arguments passed to ``MetricsReloadedBinary``.

    **kwargs
        Additional keyword arguments passed to
        ``MetricsReloadedBinary``.

    Notes
    -----
    The metric computation and aggregation are delegated entirely to MONAI.
    ``FastaiMetricMixin`` provides the fastai ``accumulate`` and ``value``
    interface.

    Only the first target in ``learn.yb`` is used.
    """

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self._name = "MetricsReloadedBinary"

    def _prepare(self, pred, target):
        """
        Prepare predictions and targets for the MONAI metric.

        Parameters
        ----------
        pred : torch.Tensor
            Predictions produced by the fastai learner.

        target : tuple
            Targets stored by fastai in ``learn.yb``.

        Returns
        -------
        tuple
            Prepared ``(pred, target)`` pair.
        """
        return pred, target[0]

# %% ../nbs/060_metrics.ipynb #8481bc99
class MetricsReloadedBinary(BioMetric):
    """
    Compute binary segmentation metrics using the MetricsReloaded framework.

    This metric evaluates predictions for binary segmentation tasks using
    the MetricsReloaded binary evaluation framework.

    Parameters
    ----------
    spacing : tuple, optional
        Physical spacing of the image dimensions. Used when computing
        metrics that depend on physical distances.

    """

    _default = mm.MetricsReloadedBinary
    _fastai = MetricsReloadedBinaryFastai


# %% ../nbs/060_metrics.ipynb #218af239
class MetricsReloadedCategorical(BioMetric):
    """
    Compute categorical segmentation metrics using the MetricsReloaded framework.

    This metric evaluates predictions for categorical or multi-class
    segmentation tasks using the MetricsReloaded categorical evaluation
    framework.

    Parameters
    ----------
    spacing : tuple, optional
        Physical spacing of the image dimensions. Used when computing
        metrics that depend on physical distances.

    """

    _default = mm.MetricsReloadedCategorical

# %% ../nbs/060_metrics.ipynb #bcb17f76
class FRCLossMetric(mm.LossMetric):
    """
    MONAI metric wrapper for the Fourier Ring Correlation loss.

    This metric evaluates ``FRCLoss`` for each batch and aggregates the
    resulting loss values using MONAI's ``LossMetric`` implementation.

    Parameters
    ----------
    reduction : str, default="mean"
        Reduction applied when aggregating loss values across iterations.
        Supported modes include ``"none"``, ``"mean"``, ``"sum"``,
        ``"mean_batch"``, ``"sum_batch"``, ``"mean_channel"``, and
        ``"sum_channel"``.

    get_not_nans : bool, default=False
        If ``True``, ``aggregate`` also returns the number of non-NaN values.

    Notes
    -----
    The ``FRCLoss`` instance is created automatically and passed to MONAI's
    ``LossMetric`` as ``loss_fn``.
    """

    def __init__(
        self,
        reduction="mean",
        get_not_nans=False,
    ):
        super().__init__(
            loss_fn=FRCLoss(),
            reduction=reduction,
            get_not_nans=get_not_nans,
        )

# %% ../nbs/060_metrics.ipynb #c8d22398
class FRCMetric(BioMetric):
    """
    Compute the Fourier Ring Correlation metric.

    The metric uses ``FRCLoss`` through MONAI's ``LossMetric`` wrapper.
    """

    _default = FRCLossMetric

# %% ../nbs/060_metrics.ipynb #ba352fcc
class VarianceMetric(BioMetric):
    _default = mm.VarianceMetric

# %% ../nbs/060_metrics.ipynb #4536906b
class LabelQualityScore(BioMetric):
    _default = mm.LabelQualityScore
