"""Metric tracking and analysis tools"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/060_metrics.ipynb.

# %% auto #0
__all__ = ['SSIMMetric', 'PSNRMetric', 'MSSSIMMetric', 'MAEMetric', 'RMSEMetric', 'get_metric', 'DiceMetric',
           'PanopticQualityMetric', 'ROCAUCMetric', 'plot_roc_curve_with_std', 'plot_roc_curve_with_std_interactive',
           'MetricsReloadedBinary', 'MetricsReloadedCategorical', 'FRCMetric']

# %% ../nbs/060_metrics.ipynb #09106178
# =================================
# Scientific / numerical
# =================================
import numpy as np
from numpy import trapezoid as trapz
import matplotlib.pyplot as plt
from sklearn import svm
from sklearn.datasets import load_iris
from sklearn.model_selection import StratifiedKFold
from sklearn.metrics import RocCurveDisplay, auc, roc_curve

# =================================
# Plots
# =================================
import plotly.graph_objects as go
import plotly.io as pio
pio.renderers.default = "notebook_connected"

# =================================
# PyTorch
# =================================
from torch import (
    abs,
    argmax,
    complex64,
    div,
    isnan,
    is_tensor,
    isinf,
    real,
    sigmoid,
    where,
    zeros_like,
)
from torch.fft import fft2, fftshift
from torch.nn.functional import one_hot, softmax

# =================================
# fastai
# =================================
from fastai.metrics import *
from fastai.vision.all import AvgMetric, Metric, partial

# =================================
# MONAI
# =================================
import monai.metrics as mm

# =================================
# bioMONAI
# =================================
from .utils import torch_from_numpy
from .losses import FRCLoss

# %% ../nbs/060_metrics.ipynb #b2246e52
def get_metric(metric_cls, backend="monai", *args, **kwargs):
    metric = metric_cls(*args, **kwargs)

    if backend in ("monai", "ignite"):
        # Return MONAI metric as-is
        return metric

    elif backend == "fastai":
        # Wrap for fastai (epoch-level correct version)
        class MonaiFastaiMetric(Metric):
            def reset(self):
                if hasattr(metric, "reset"):
                    metric.reset()

            def accumulate(self, learn):
                pred, targ = learn.pred, learn.y
                metric(pred, targ)

            @property
            def value(self):
                if hasattr(metric, "aggregate"):
                    return metric.aggregate().mean().item()
                else:
                    return None

            @property
            def name(self):
                return metric.__class__.__name__

        return MonaiFastaiMetric()

    else:
        raise ValueError(f"Unknown backend: {backend}")

# %% ../nbs/060_metrics.ipynb #4960aa4d
SSIMMetric = partial(get_metric, mm.SSIMMetric)
PSNRMetric = partial(get_metric, mm.PSNRMetric)
MSSSIMMetric = partial(get_metric, mm.MultiScaleSSIMMetric)
MAEMetric = partial(get_metric, mm.MAEMetric)
RMSEMetric = partial(get_metric, mm.RMSEMetric)

# %% ../nbs/060_metrics.ipynb #a63e7732
def DiceMetric(threshold=0.5, instance=False, **kwargs):
    """
    Wrapper around monai.metrics.DiceMetric
    Works for binary segmentation with 1-channel logits.
    Accepts all keyword arguments supported by monai.metrics.DiceMetric
        Example:
            DiceMetric(
                include_background=False,
                reduction="mean",
                get_not_nans=False,
                ignore_empty=True
            )
    """
    dice_metric = mm.DiceMetric(**kwargs)

    def Dice(pred, target):
        # Check shapes 
        if target.ndim == 3:
            target = target.unsqueeze(1)

        # if target is not binary assume it's an instance mask and
        # convert to a binary foreground/background mask
        if instance:
            # Binarize
            pred = (pred > threshold).float()
            target = (target > 0).float()
        else:
            # logits -> probabilities
            pred = sigmoid(pred)
            # Binarize
            pred = (pred > threshold).float()

        dice_metric.reset()
        dice_metric(pred, target)
        return dice_metric.aggregate()

    return AvgMetric(Dice)


# %% ../nbs/060_metrics.ipynb #7df2d770
def PanopticQualityMetric(**kwargs):
    """
    Wrapper around monai.metrics.PanopticQualityMetric.

    Expects:
        pred  : (B, C, H, W) logits
        target: (B, H, W) or (B, 1, H, W) panoptic map
                Each pixel contains encoded panoptic label
                (semantic + instance id).

    All kwargs are forwarded to MONAI PanopticQualityMetric.
    """
    pq_metric = mm.PanopticQualityMetric(**kwargs)

    def PQ(pred, target):
        # Convert logits to discrete labels
        # pred = pred.argmax(dim=1)  # (B, H, W)

        if target.ndim == 4 and target.shape[1] == 1:
            target = target.squeeze(1)

        pq_metric.reset()
        pq_metric(y_pred=pred, y=target)
        return pq_metric.aggregate()

    return AvgMetric(PQ)

# %% ../nbs/060_metrics.ipynb #0481c954
def ROCAUCMetric(num_classes=None, # if not None, checks if preds and targets are one-hot encoded
                 act=None,         # activation operations, typically Sigmoid or Softmax.
                 **kwargs):
    """
    Wrapper around monai.metrics.ROCAUCMetric.

    If num_classes is None:
        assumes pred and target are already one-hot / probability encoded.

    If num_classes is provided:
        automatically one-hot encodes pred/target when needed.
    """
    rocaucmetric = mm.ROCAUCMetric(**kwargs)

    def _maybe_one_hot(x):
        # already encoded
        if x.ndim > 1 and x.shape[1] == num_classes:
            return x

        return one_hot(x.long(), num_classes=num_classes)

    def ROCAUC(pred, target):
        if act is not None:
            pred = act(pred)

        if num_classes is not None:
            pred = _maybe_one_hot(pred)
            target = _maybe_one_hot(target)

        rocaucmetric.reset()
        rocaucmetric(pred, target)
        return rocaucmetric.aggregate()

    return AvgMetric(ROCAUC)

# %% ../nbs/060_metrics.ipynb #c21e7570
def plot_roc_curve_with_std(
    y_probs_folds,
    y_true_folds,
    n_points=200,
    show_folds=False,
    title="ROC curve with cross-validation"
):
    """
    Plot ROC curves across CV folds with mean ROC and ±1 std band.

    Parameters
    ----------
    y_probs_folds : list of array-like
        Predicted probabilities for the positive class per fold.
    y_true_folds : list of array-like
        Ground truth labels per fold.
    n_points : int
        Resolution of interpolated ROC curve.
    show_folds : bool
        Whether to display individual fold curves.
    title : str
        Plot title.
    """

    fpr_grid = np.linspace(0, 1, n_points)

    tprs = []
    aucs = []

    fig, ax = plt.subplots(figsize=(6, 6))

    # ---------------------------------------------------------------------
    # Per-fold ROC
    # ---------------------------------------------------------------------
    for fold, (y_prob, y_true) in enumerate(zip(y_probs_folds, y_true_folds)):

        roc = RocCurveDisplay.from_predictions(
            y_true,
            y_prob,
            ax=ax,
            curve_kwargs={
                "alpha": 0.25 if show_folds else 0.0,
                "lw": 1
            }
        )

        # Interpolate TPR onto common grid
        tpr_interp = np.interp(fpr_grid, roc.fpr, roc.tpr)
        tpr_interp[0] = 0.0

        tprs.append(tpr_interp)
        aucs.append(roc.roc_auc)

        # Hide legend entries if not requested
        if not show_folds:
            roc.line_.set_label("_nolegend_")

    # ---------------------------------------------------------------------
    # Aggregate statistics
    # ---------------------------------------------------------------------
    tprs = np.array(tprs)

    mean_tpr = tprs.mean(axis=0)
    mean_tpr[-1] = 1.0

    std_tpr = tprs.std(axis=0)

    mean_auc = np.mean(aucs)
    std_auc = np.std(aucs)

    # ---------------------------------------------------------------------
    # Mean ROC curve
    # ---------------------------------------------------------------------
    ax.plot(
        fpr_grid,
        mean_tpr,
        color="red",
        lw=2,
        label=f"Mean ROC (AUC = {mean_auc:.2f} ± {std_auc:.2f})"
    )

    # ---------------------------------------------------------------------
    # Confidence band
    # ---------------------------------------------------------------------
    ax.fill_between(
        fpr_grid,
        np.maximum(mean_tpr - std_tpr, 0),
        np.minimum(mean_tpr + std_tpr, 1),
        color="grey",
        alpha=0.2,
        label="±1 std. dev."
    )

    # ---------------------------------------------------------------------
    # Final styling
    # ---------------------------------------------------------------------
    ax.set_xlabel("False Positive Rate")
    ax.set_ylabel("True Positive Rate")
    ax.set_title(title)
    ax.legend(loc="lower right")

    plt.show()

# %% ../nbs/060_metrics.ipynb #8a6477fd
def plot_roc_curve_with_std_interactive(
    y_probs_folds,
    y_true_folds,
    n_points=200,
    show_folds=True,
    title="ROC curve with cross-validation"
):

    fpr_grid = np.linspace(0, 1, n_points)

    tprs = []
    aucs = []

    fig = go.Figure()

    # ------------------------------------------------------------
    # Per-fold ROC
    # ------------------------------------------------------------
    for i, (y_prob, y_true) in enumerate(zip(y_probs_folds, y_true_folds)):

        fpr, tpr, _ = roc_curve(y_true, y_prob)
        roc_auc = auc(fpr, tpr)

        tpr_interp = np.interp(fpr_grid, fpr, tpr)
        tpr_interp[0] = 0.0

        tprs.append(tpr_interp)
        aucs.append(roc_auc)

        if show_folds:
            fig.add_trace(go.Scatter(
                x=fpr,
                y=tpr,
                mode="lines",
                name=f"Fold {i+1} (AUC={roc_auc:.2f})",
                opacity=0.4
            ))

    tprs = np.array(tprs)

    # ------------------------------------------------------------
    # Mean + std
    # ------------------------------------------------------------
    mean_tpr = tprs.mean(axis=0)
    mean_tpr[-1] = 1.0

    std_tpr = tprs.std(axis=0)

    mean_auc = np.mean(aucs)
    std_auc = np.std(aucs)

    upper = np.minimum(mean_tpr + std_tpr, 1)
    lower = np.maximum(mean_tpr - std_tpr, 0)

    # Mean ROC
    fig.add_trace(go.Scatter(
        x=fpr_grid,
        y=mean_tpr,
        mode="lines",
        name=f"Mean ROC (AUC={mean_auc:.2f} ± {std_auc:.2f})",
        line=dict(width=3, color="red")
    ))

    # Std band
    fig.add_trace(go.Scatter(
        x=np.concatenate([fpr_grid, fpr_grid[::-1]]),
        y=np.concatenate([upper, lower[::-1]]),
        fill="toself",
        fillcolor="rgba(128,128,128,0.2)",
        line=dict(color="rgba(255,255,255,0)"),
        hoverinfo="skip",
        name="±1 std. dev."
    ))

    # Chance line
    fig.add_trace(go.Scatter(
        x=[0, 1],
        y=[0, 1],
        mode="lines",
        line=dict(dash="dash", color="gray"),
        name="Chance"
    ))

    # ------------------------------------------------------------
    # Styling: black axes + centered title
    # ------------------------------------------------------------
    fig.update_layout(
        title=dict(
            text=title,
            x=0.5,              # center title
            xanchor="center"
        ),
            xaxis=dict(
            range=[0, 1],
            autorange=False,
            title="False Positive Rate",
            showline=True,
            linecolor="black",
            mirror=True,
            ticks="outside",
            scaleanchor="y",
            scaleratio=1
        ),
        yaxis=dict(
            range=[0, 1],
            autorange=False,
            title="True Positive Rate",
            showline=True,
            linecolor="black",
            mirror=True,
            ticks="outside"
        ),
        width=700,
        height=700,
        template="plotly_white",
        legend=dict(orientation="v")
    )

    fig.show()

    return fig

# %% ../nbs/060_metrics.ipynb #8481bc99
def MetricsReloadedBinary(metric_name, **kwargs):
    "Binary pairwise metrics of MetricsReloaded library"
    def MRB(x, y):
        return mm.MetricsReloadedBinary(metric_name, **kwargs)(x,y).mean()
    return AvgMetric(MRB)

def MetricsReloadedCategorical(metric_name, **kwargs):
    "Categorical pairwise metrics of MetricsReloaded library"
    def MRC(x, y):
        return mm.MetricsReloadedCategorical(metric_name, **kwargs)(x,y).mean()
    return AvgMetric(MRC)

# %% ../nbs/060_metrics.ipynb #c8d22398
def FRCMetric(image1, image2):
    """
    Metric derived from FRC loss.
    """

    return 1.0 - FRCLoss(image1, image2)

