"""bioMONAI optimizers"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/060_optimizers.ipynb.

# %% auto #0
__all__ = ['OptimWrapper', 'Adam', 'Optimizer']

# %% ../nbs/060_optimizers.ipynb #e46d9793
# =================================
# Scientific / data
# =================================
# import numpy as np
# import pandas as pd

# =================================
# PyTorch
# =================================
import torch.optim as toptim

# =================================
# fastai
# =================================
from fastai.optimizer import Adam, OptimWrapper, Optimizer

# =================================
# bioMONAI
# =================================
from .utils import *

# %% ../nbs/060_optimizers.ipynb #574e843b
OptimWrapper = OptimWrapper
Adam = Adam
Optimizer = Optimizer
