"""Data transformations and augmentations for 2D and 3D BioImages"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/030_transforms.ipynb.

# %% auto #0
__all__ = ['Blur', 'RandBlur', 'FunctionTransform', 'MonaiTransform', 'RandMonaiTransform', 'ApplyTo', 'Resample', 'Spacing',
           'Resize', 'Crop', 'SpatialCrop', 'CenterSpatialCrop', 'CropForeground', 'BoundingRect', 'CenterScaleCrop',
           'CropND', 'Pad', 'SpatialPad', 'BorderPad', 'DivisiblePad', 'Rotate', 'Rotate90', 'Zoom', 'Flip',
           'GridPatch', 'GridSplit', 'SpatialResample', 'ResampleToMatch', 'Orientation', 'Affine', 'AffineGrid',
           'GridDistortion', 'GaussianSmooth', 'MedianSmooth', 'SavitzkyGolaySmooth', 'GaussianSharpen',
           'ShiftIntensity', 'StdShiftIntensity', 'ScaleImage', 'ScaleImagePercentiles', 'ScaleImageVariance',
           'ScaleIntensity', 'ScaleIntensityFixedMean', 'ScaleIntensityRange', 'ScaleIntensityRangePercentiles',
           'NormalizeIntensity', 'HistogramNormalize', 'AdjustContrast', 'RelabelInstances',
           'InstanceToMaskAndDistance', 'ComputeHoVerMaps', 'ThresholdIntensity', 'MaskIntensity', 'ForegroundMask',
           'RGB2HED', 'HED2RGB', 'RandCrop2D', 'RandCropND', 'RandFlip', 'RandRot90', 'RandRotation', 'RandZoom',
           'RandCameraNoise', 'RandGaussianNoise', 'RandGaussianSmooth', 'RandGaussianSharpen', 'RandShiftIntensity',
           'RandStdShiftIntensity', 'RandAdjustContrast']

# %% ../nbs/030_transforms.ipynb #56ab9960
# =================================
# Standard library
# =================================
import random
from math import ceil

# =================================
# Scientific / numerical
# =================================
import numpy as np
from numpy import percentile, isscalar, float32 as np_float32
from scipy.ndimage import distance_transform_edt

# =================================
# Computer vision / imaging
# =================================
import cv2
from skimage.transform import resize

# =================================
# MONAI
# =================================
import monai.transforms as tfms
from monai.utils.enums import *

# =================================
# fastai
# =================================
from fastai.data.all import *
from fastai.vision.all import *

# =================================
# bioMONAI
# =================================
from .utils import *
from .data import BioImageBase, BioVolume, Tensor2BioImage

# %% ../nbs/030_transforms.ipynb #425f62e2
class FunctionTransform(Transform):
    """
    Generic MonaiTransform to apply any NumPy or SciPy function to an image.
    Works with CHW/CDHW arrays or BioImageBase.
    """

    def __init__(self, func, has_channels=True, **func_kwargs):
        self.has_channels = has_channels
        self.func = func
        self.func_kwargs = func_kwargs

    def encodes(self, img: np.ndarray):
        if not self.has_channels:
            img = np.expand_dims(img, axis=0)

        if img.ndim >= 3 and self.has_channels:
            out = np.stack([self.func(img[c], **self.func_kwargs) for c in range(img.shape[0])], axis=0)
        else:
            out = self.func(img, **self.func_kwargs)

        return out

    def encodes(self, img: 'BioImageBase'):
        result = self.encodes(img.numpy())
        return type(img)(result)

# %% ../nbs/030_transforms.ipynb #6162be1b
class MonaiTransform(DisplayedTransform):
    """
    Wrapper for MONAI transforms with typedispatch support.

    Supports:
    - MetaTensor (native MONAI)
    - dict (auto *d/*D transform + keys)
    - BioImageBase (type preserved)
    - NumPy arrays (type preserved)
    """

    _monai_transform = None
    _dict_transform = None

    def __init__(
        self,
        keys=None,
        has_channels=True,
        **kwargs,
    ):
        store_attr()

        if self._monai_transform is None:
            raise ValueError(
                f"{self.__class__.__name__} must define "
                f"`_monai_transform`"
            )

        # Base MONAI transform
        self.transform = self._monai_transform(**kwargs)

        # Dict transform
        dict_transform = self._dict_transform

        if keys is not None:

            # Auto-infer if not explicitly provided
            if dict_transform is None:
                dict_transform = self._infer_dict_transform(
                    self._monai_transform
                )

            if dict_transform is None:
                raise ValueError(
                    f"No dict transform found for "
                    f"{self._monai_transform.__name__}"
                )

            self.dict_transform = dict_transform(
                keys=keys,
                **kwargs,
            )
        else:
            self.dict_transform = None

    # -------------------------
    # Helper: infer dict transform
    # -------------------------
    def _infer_dict_transform(self, base_cls):
        name = base_cls.__name__

        for suffix in ("d", "D"):
            candidate = name + suffix

            if hasattr(tfms, candidate):
                return getattr(tfms, candidate)

        return None

    # -------------------------
    # MetaTensor
    # -------------------------
    def encodes(self, x: "MetaTensor"):
        return self.transform(x)

    # -------------------------
    # torch.Tensor
    # -------------------------
    def encodes(self, x: torchTensor):
        return self.transform(x)

    # -------------------------
    # dict (MONAI dict pipeline)
    # -------------------------
    def encodes(self, x: dict):

        if self.dict_transform is None:
            raise ValueError(
                f"No dict transform available for "
                f"{type(self.transform).__name__}"
            )

        return self.dict_transform(x)

    # -------------------------
    # BioImageBase
    # -------------------------
    def encodes(self, x: BioImageBase):
        out = self.transform(x)
        return type(x)(x=out, meta=out.meta)

    # -------------------------
    # NumPy
    # -------------------------
    def encodes(self, x: np.ndarray):

        if not self.has_channels:
            x = np.expand_dims(x, axis=0)

        tensor = MetaTensor(x)
        out = self.transform(tensor)

        return out.detach().cpu().numpy()


# %% ../nbs/030_transforms.ipynb #9f052222
def _uniform_sampler(v):

    # range sampling
    if isinstance(v, (tuple, list)) and len(v) == 2:

        a, b = v

        if isinstance(a, int) and isinstance(b, int):
            return np.random.randint(a, b + 1)

        if isinstance(a, (int, float)) and isinstance(b, (int, float)):
            return np.random.uniform(a, b)

        return v

    return v

# %% ../nbs/030_transforms.ipynb #ee7925d5
class RandMonaiTransform(RandTransform):
    """
    Wrapper for MONAI random transforms with:

    - typedispatch support
    - automatic Rand↔Det transform inference
    - deterministic fallback for BioImageBase
    - argument aliasing
    - deterministic parameter filtering

    MONAI-native types:
    - MetaTensor
    - Tensor
    - dict
    - ndarray

    use MONAI random transforms directly.

    BioImageBase:
    - uses sampled params from before_call()
    - applies deterministic transform
    """

    split_idx = None

    # ---------------------------------------------------------
    # MONAI transforms
    # ---------------------------------------------------------

    _monai_rand_transform = None
    _monai_det_transform = None

    # Deterministic transform to be used during validation / inference
    # If None, no transform will be used at all
    _val_transform = None

    # Explicit dict transform
    _dict_transform = None

    # parameters to sample
    _rand_kwargs = {}
    _default_kwargs = {}

    # ---------------------------------------------------------
    # Init
    # ---------------------------------------------------------

    def __init__(
        self,
        prob=0.1,
        param_sampler=_uniform_sampler,
        keys=None,
        has_channels=True,
        **kwargs,
    ):
        store_attr()

        self.p = prob

        # infer transforms
        self._infer_transforms()
        self._infer_dict_transform(self._monai_rand_transform)

        # kwargs
        self.kwargs = {
            **self._default_kwargs,
            **kwargs,
            'prob': prob,
        }

        # kwargs usable by deterministic transform
        self.det_kwargs = self._filter_kwargs(
            self._monai_det_transform,
            kwargs,
        )

        self._rand_transform = None
        self._dict_rand_transform = None

        super().__init__()

    # ---------------------------------------------------------
    # Transform inference
    # ---------------------------------------------------------

    def _infer_transforms(self):

        rand_cls = self._monai_rand_transform
        det_cls = self._monai_det_transform

        # Infer RandTfm from Tfm
        if rand_cls is None and det_cls is not None:

            candidate = "Rand" + det_cls.__name__
            if hasattr(tfms, candidate):
                rand_cls = getattr(tfms, candidate)

        # Infer Tfm from RandTfm
        if det_cls is None and rand_cls is not None:

            name = rand_cls.__name__

            if name.startswith("Rand"):

                candidate = name[4:]
                if hasattr(tfms, candidate):
                    det_cls = getattr(tfms, candidate)

        if rand_cls is None:
            raise ValueError(
                f"Could not infer random transform for "
                f"{self.__class__.__name__}"
            )

        if det_cls is None:
            raise ValueError(
                f"Could not infer deterministic transform for "
                f"{self.__class__.__name__}"
            )

        self._monai_rand_transform = rand_cls
        self._monai_det_transform = det_cls

    # ---------------------------------------------------------
    # Dict transform inference
    # ---------------------------------------------------------

    def _infer_dict_transform(self, base_cls):

        name = base_cls.__name__

        for suffix in ("d", "D"):

            candidate = name + suffix

            if hasattr(tfms, candidate):
                return getattr(tfms, candidate)

        return None

    # ---------------------------------------------------------
    # Signature filtering
    # ---------------------------------------------------------

    def _filter_kwargs(self, cls, kwargs):

        sig = inspect.signature(cls.__init__)

        valid = set(sig.parameters)

        return {
            k: v
            for k, v in kwargs.items()
            if k in valid
        }
    
    # ---------------------------------------------------------
    # Sampling
    # ---------------------------------------------------------

    def before_call(self, b=None, split_idx=0):

        super().before_call(b, split_idx)

        self.sampled_kwargs = {}

        for out_key, spec in self._rand_kwargs.items():

            # -----------------------------------------
            # single source key
            # -----------------------------------------
            if isinstance(spec, str):

                raw = self.kwargs[spec]

                self.sampled_kwargs[out_key] = _uniform_sampler(raw)

            # -----------------------------------------
            # multiple source keys → tuple output
            # -----------------------------------------
            elif isinstance(spec, (list, tuple)):

                raw_vals = [
                    self.kwargs[k] for k in spec
                ]

                self.sampled_kwargs[out_key] = tuple(
                    _uniform_sampler(v) for v in raw_vals
                )

            else:
                raise TypeError(
                    "`rand_kwargs` values must be str or list[str]"
                )

        # merge sampled into deterministic params
        self.sampled_kwargs = {
            **self.det_kwargs,
            **self.sampled_kwargs,
        }

    # ---------------------------------------------------------
    # Lazy builders
    # ---------------------------------------------------------

    def _build_rand_transform(self):

        self._rand_transform = self._monai_rand_transform(**self.kwargs)


    def _build_dict_transform(self):

        dict_cls = self._dict_transform

        if dict_cls is None:

            dict_cls = self._infer_dict_transform(
                self._monai_rand_transform
            )

        if dict_cls is None:
            raise ValueError(
                f"No dict transform found for "
                f"{self._monai_rand_transform.__name__}"
            )

        if self.keys is None:
            raise ValueError(
                "`keys` must be provided "
                "for dict transforms"
            )

        self._dict_rand_transform = dict_cls(
            keys=self.keys,
            **self.kwargs,
        )

    # ---------------------------------------------------------
    # MetaTensor
    # ---------------------------------------------------------

    def encodes(self, x: MetaTensor):

        if self._rand_transform is None:
            self._build_rand_transform()

        return self._rand_transform(x)

    # ---------------------------------------------------------
    # torch.Tensor
    # ---------------------------------------------------------

    def encodes(self, x: torch.Tensor):

        if self._rand_transform is None:
            self._build_rand_transform()

        return self._rand_transform(x)

    # ---------------------------------------------------------
    # dict
    # ---------------------------------------------------------

    def encodes(self, x: dict):

        if self._dict_rand_transform is None:
            self._build_dict_transform()

        return self._dict_rand_transform(x)

    # ---------------------------------------------------------
    # BioImageBase
    # ---------------------------------------------------------

    def encodes(self, x: BioImageBase):

        tfm = self._monai_det_transform(**self.sampled_kwargs)

        out = tfm(x)

        return type(x)(
            x=out,
            meta=x.meta,
        )

    # ---------------------------------------------------------
    # NumPy
    # ---------------------------------------------------------

    def encodes(self, x: np.ndarray):

        if self._rand_transform is None:
            self._build_rand_transform()

        if not self.has_channels:
            x = np.expand_dims(x, axis=0)

        tensor = MetaTensor(x)

        out = self._rand_transform(tensor)

        return out.detach().cpu().numpy()

# %% ../nbs/030_transforms.ipynb #83011f10
class ApplyTo(Transform):
    """
    Apply a transform to a specific element of a tuple.

    Args:
        tfm: the transform or callable to apply
        idx: index of the tuple element to modify (default 0)
    """
    def __init__(self, tfm, idx=0):
        self.tfm = tfm
        self.idx = idx

    def __call__(self, x, **kwargs):
        # Single element case
        if not isinstance(x, (tuple, list)):
            if self.idx != 0:
                raise IndexError(f"Tuple element index {self.idx} out of range for non-tuple input")
            return self.tfm(x, **kwargs)

        # Tuple/list case
        elems = list(x)
        elems[self.idx] = self.tfm(elems[self.idx], **kwargs)
        return tuple(elems)

# %% ../nbs/030_transforms.ipynb #9a9cd349
class Resample(MonaiTransform):
    """
    A subclass of Spacing that handles image resampling based on specified sampling factors or voxel dimensions.
    
    The `Resample` class inherits from `Spacing` and provides a flexible way to adjust the spacing (voxel size) of images by specifying either a sampling factor or explicitly providing new voxel dimensions.
    
    """
    _monai_transform = tfms.Spacing

    def __init__(
        self,
        sampling=None,        # isotropic factor OR pixdim fallback
        has_channels=True,
        keys=None,
        **kwargs
    ):
        """
        If `pixdim` is provided in kwargs, it is used directly.
        Otherwise `sampling` is used as pixdim.
        """

        if 'pixdim' not in kwargs:
            if sampling is None:
                raise ValueError("Provide either `sampling` or `pixdim`")
            kwargs['pixdim'] = sampling

        super().__init__(
            keys=keys,
            has_channels=has_channels,
            **kwargs
        )

# %% ../nbs/030_transforms.ipynb #efd4242e
class Spacing(MonaiTransform):
    """
    A wrapper around MONAI's Spacing transform that supports multiple input types and auto-infers dict transforms.

    """
    _monai_transform = tfms.Spacing

    def __init__(
        self,
        pixdim=None,
        has_channels=True,
        keys=None,
        **kwargs
    ):
       
        super().__init__(
            keys=keys,
            has_channels=has_channels,
            pixdim=pixdim,
            **kwargs
        )

# %% ../nbs/030_transforms.ipynb #9110a2b2
class Resize(MonaiTransform):
    """
    A wrapper around MONAI's Resize transform that supports multiple input types and auto-infers dict transforms.

    Args:
        size: output spatial size
        has_channels: whether the input has a channel dimension (default True)
        keys: keys for dict transforms (if applicable)
        **kwargs: additional arguments to pass to the underlying transform
    """
    _monai_transform = tfms.Resize

    def __init__(
        self,
        spatial_size,
        has_channels=True,
        keys=None,
        **kwargs
    ):
        super().__init__(
            keys=keys,
            has_channels=has_channels,
            spatial_size=spatial_size,
            **kwargs
        )

# %% ../nbs/030_transforms.ipynb #bb51abb4
class Crop(MonaiTransform):
    """
    MONAI Crop wrapper using MonaiTransform.

    Supports:
    - MetaTensor (preserves spatial metadata)
    - dict (Crop*d auto-inferred)
    - BioImageBase
    - NumPy arrays
    """
    _monai_transform = tfms.Crop


# %% ../nbs/030_transforms.ipynb #9cceb4af
class SpatialCrop(MonaiTransform):
    """
    MONAI SpatialCrop wrapper using MonaiTransform.

    Supports:
    - MetaTensor (preserves spatial metadata)
    - dict (SpatialCrop*d auto-inferred)
    - BioImageBase
    - NumPy arrays
    """
    _monai_transform = tfms.SpatialCrop


# %% ../nbs/030_transforms.ipynb #89d29c18
class CenterSpatialCrop(MonaiTransform):
    """
    MONAI CenterSpatialCrop wrapper using MonaiTransform.

    Supports:
    - MetaTensor (preserves spatial metadata)
    - dict (CenterSpatialCrop*d auto-inferred)
    - BioImageBase
    - NumPy arrays
    """
    _monai_transform = tfms.CenterSpatialCrop

    def __init__(
        self,
        roi_size=None,
        has_channels=True,
        keys=None,
        **kwargs,
    ):
        """
        roi_size:
            - int → broadcast to all spatial dims
            - tuple/list → target spatial size
        """

        self.roi_size = roi_size

        super().__init__(
            keys=keys,
            has_channels=has_channels,
            roi_size=roi_size,   # MONAI expects this arg
            **kwargs,
        )

# %% ../nbs/030_transforms.ipynb #9877db6d
class CropForeground(MonaiTransform):
    """
    MONAI CropForeground wrapper using MonaiTransform.

    Supports:
    - MetaTensor (preserves spatial metadata)
    - dict (CropForeground*d auto-inferred)
    - BioImageBase
    - NumPy arrays
    """
    _monai_transform = tfms.CropForeground

# %% ../nbs/030_transforms.ipynb #8c0506ba
class BoundingRect(MonaiTransform):
    """
    MONAI BoundingRect wrapper using MonaiTransform.

    Supports:
    - MetaTensor (preserves spatial metadata)
    - dict (BoundingRect*d auto-inferred)
    - BioImageBase
    - NumPy arrays
    """
    _monai_transform = tfms.BoundingRect

# %% ../nbs/030_transforms.ipynb #cdeac873
class CenterScaleCrop(MonaiTransform):
    """
    MONAI CenterScaleCrop wrapper using MonaiTransform.

    Supports:
    - MetaTensor (preserves spatial metadata)
    - dict (CenterScaleCrop*d auto-inferred)
    - BioImageBase
    - NumPy arrays
    """
    _monai_transform = tfms.CenterScaleCrop

    def __init__(
        self,
        roi_scale=1.0,
        has_channels=True,
        keys=None,
        **kwargs,
    ):

        self.roi_scale = roi_scale

        super().__init__(
            keys=keys,
            has_channels=has_channels,
            roi_scale=roi_scale, 
            **kwargs,
        )

# %% ../nbs/030_transforms.ipynb #ac665ddb
class CropND(Transform):
    """
    Crops an ND tensor along a specified dimension.

    This transform crops an ND tensor along specified dimensions, which could be a channel or spatial dimension.
    """
    
    def __init__(self, 
                 slices: list, # List of slice objects or tuples (start, end) for each dimension
                 dims: list = None, # List of dimensions to apply the slices. If None, slices are applied to all dimensions.
                 ):
        self.slices = [slice(*s) if isinstance(s, tuple) else s for s in slices]
        self.dims = dims
        
    def encodes(self, x: BioImageBase):
        """Apply cropping to a BioImageBase object."""
        bioimagetype = type(x)
        slices = [slice(None)] * x.ndim
        if self.dims is None:
            for i, s in enumerate(self.slices):
                if x.shape[i] >= s.stop - s.start:
                    slices[i] = s
        else:
            for dim, s in zip(self.dims, self.slices):
                if x.shape[dim] >= s.stop - s.start:
                    slices[dim] = s
        return bioimagetype(x[tuple(slices)])
    
    def encodes(self, x: np.ndarray):
        """Apply cropping to a NumPy array."""
        slices = [slice(None)] * x.ndim
        if self.dims is None:
            for i, s in enumerate(self.slices):
                if x.shape[i] >= s.stop - s.start:
                    slices[i] = s
        else:
            for dim, s in zip(self.dims, self.slices):
                if x.shape[dim] >= s.stop - s.start:
                    slices[dim] = s
        return x[tuple(slices)]

# %% ../nbs/030_transforms.ipynb #1b9c1d6a
class Pad(MonaiTransform):
    """
    MONAI Pad wrapper using MonaiTransform.

    Supports:
    - MetaTensor (preserves spatial metadata)
    - dict (Pad*d auto-inferred)
    - BioImageBase
    - NumPy arrays
    """
    _monai_transform = tfms.Pad

# %% ../nbs/030_transforms.ipynb #c1536f5c
class SpatialPad(MonaiTransform):
    """
    MONAI SpatialPad wrapper using MonaiTransform.

    Supports:
    - MetaTensor (preserves spatial metadata)
    - dict (SpatialPad*d auto-inferred)
    - BioImageBase
    - NumPy arrays
    """
    _monai_transform = tfms.SpatialPad

    def __init__(
        self,
        spatial_size,
        has_channels=True,
        keys=None,
        **kwargs,
    ):
        self.spatial_size = spatial_size

        super().__init__(
            keys=keys,
            has_channels=has_channels,
            spatial_size=spatial_size, 
            **kwargs,
        )

# %% ../nbs/030_transforms.ipynb #970c57c5
class BorderPad(MonaiTransform):
    """
    MONAI BorderPad wrapper using MonaiTransform.

    Supports:
    - MetaTensor (preserves spatial metadata)
    - dict (BorderPad*d auto-inferred)
    - BioImageBase
    - NumPy arrays
    """
    _monai_transform = tfms.BorderPad

    def __init__(
        self,
        spatial_border,
        has_channels=True,
        keys=None,
        **kwargs,
    ):
        self.border_size = spatial_border

        super().__init__(
            keys=keys,
            has_channels=has_channels,
            spatial_border=spatial_border, 
            **kwargs,
        )

# %% ../nbs/030_transforms.ipynb #f788202d
class DivisiblePad(MonaiTransform):
    """
    MONAI DivisiblePad wrapper using MonaiTransform.

    Supports:
    - MetaTensor (preserves spatial metadata)
    - dict (DivisiblePad*d auto-inferred)
    - BioImageBase
    - NumPy arrays
    """
    _monai_transform = tfms.DivisiblePad

    def __init__(
        self,
        k,
        has_channels=True,
        keys=None,
        **kwargs,
    ):
        self.spatial_size = k

        super().__init__(
            keys=keys,
            has_channels=has_channels,
            k=k, 
            **kwargs,
        )

# %% ../nbs/030_transforms.ipynb #17fea3a1
class Rotate(MonaiTransform):
    """
    MONAI Rotate wrapper using MonaiTransform.

    Supports:
    - MetaTensor (preserves spatial metadata)
    - dict (Rotate*d auto-inferred)
    - BioImageBase
    - NumPy arrays
    """
    _monai_transform = tfms.Rotate

    def __init__(
        self,
        angle=0.0,
        has_channels=True,
        keys=None,
        **kwargs,
    ):

        self.angle = angle

        super().__init__(
            keys=keys,
            has_channels=has_channels,
            angle=angle, 
            **kwargs,
        )

# %% ../nbs/030_transforms.ipynb #567191d8
class Rotate90(MonaiTransform):
    """
    MONAI Rotate90 wrapper using MonaiTransform.

    Supports:
    - MetaTensor (preserves spatial metadata)
    - dict (Rotate90*d auto-inferred)
    - BioImageBase
    - NumPy arrays
    """
    _monai_transform = tfms.Rotate90

    def __init__(
        self,
        spatial_axes=(0, 1),
        has_channels=True,
        keys=None,
        **kwargs,
    ):

        self.spatial_axes = spatial_axes

        super().__init__(
            keys=keys,
            has_channels=has_channels,
            spatial_axes=spatial_axes, 
            **kwargs,
        )

# %% ../nbs/030_transforms.ipynb #97b35d62
class Zoom(MonaiTransform):
    """
    MONAI Zoom wrapper using MonaiTransform.

    Supports:
    - MetaTensor (preserves spatial metadata)
    - dict (Zoom*d auto-inferred)
    - BioImageBase
    - NumPy arrays
    """
    _monai_transform = tfms.Zoom

    def __init__(
        self,
        zoom=1.0,
        has_channels=True,
        keys=None,
        **kwargs,
    ):

        self.zoom = zoom

        super().__init__(
            keys=keys,
            has_channels=has_channels,
            zoom=zoom, 
            **kwargs,
        )

# %% ../nbs/030_transforms.ipynb #c305ce78
class Flip(MonaiTransform):
    """
    MONAI Flip wrapper using MonaiTransform.

    Supports:
    - MetaTensor (preserves spatial metadata)
    - dict (Flip*d auto-inferred)
    - BioImageBase
    - NumPy arrays
    """

    _monai_transform = tfms.Flip

# %% ../nbs/030_transforms.ipynb #4a5925ac
class GridPatch(MonaiTransform):
    """
    MONAI GridPatch wrapper using MonaiTransform.

    Supports:
    - MetaTensor (preserves spatial metadata)
    - dict (GridPatch*d auto-inferred)
    - BioImageBase
    - NumPy arrays
    """
    _monai_transform = tfms.GridPatch

    def __init__(
        self,
        patch_size=None,
        has_channels=True,
        keys=None,
        **kwargs,
    ):

        self.patch_size = patch_size

        super().__init__(
            keys=keys,
            has_channels=has_channels,
            patch_size=patch_size, 
            **kwargs,
        )

# %% ../nbs/030_transforms.ipynb #2019a57c
class GridSplit(MonaiTransform):
    """
    MONAI GridSplit wrapper using MonaiTransform.

    Supports:
    - MetaTensor (preserves spatial metadata)
    - dict (GridSplit*d auto-inferred)
    - BioImageBase
    - NumPy arrays
    """
    _monai_transform = tfms.GridSplit

# %% ../nbs/030_transforms.ipynb #86723835
class SpatialResample(MonaiTransform):
    """
    MONAI SpatialResample wrapper using MonaiTransform.

    Supports:
    - MetaTensor (preserves spatial metadata)
    - dict (SpatialResample*d auto-inferred)
    - BioImageBase
    - NumPy arrays
    """
    _monai_transform = tfms.SpatialResample

# %% ../nbs/030_transforms.ipynb #b893c9a2
class ResampleToMatch(MonaiTransform):
    """
    MONAI ResampleToMatch wrapper using MonaiTransform.

    Supports:
    - MetaTensor (preserves spatial metadata)
    - dict (ResampleToMatch*d auto-inferred)
    - BioImageBase
    - NumPy arrays
    """
    _monai_transform = tfms.ResampleToMatch

# %% ../nbs/030_transforms.ipynb #2a6317ac
class Orientation(MonaiTransform):
    """
    MONAI Orientation wrapper using MonaiTransform.

    Supports:
    - MetaTensor (preserves spatial metadata)
    - dict (Orientation*d auto-inferred)
    - BioImageBase
    - NumPy arrays
    """
    _monai_transform = tfms.Orientation

# %% ../nbs/030_transforms.ipynb #72313503
class Affine(MonaiTransform):
    """
    MONAI Affine wrapper using MonaiTransform.

    Supports:
    - MetaTensor (preserves spatial metadata)
    - dict (Affine*d auto-inferred)
    - BioImageBase
    - NumPy arrays
    """
    _monai_transform = tfms.Affine

# %% ../nbs/030_transforms.ipynb #1f9f82c4
class AffineGrid(MonaiTransform):
    """
    MONAI AffineGrid wrapper using MonaiTransform.

    Supports:
    - MetaTensor (preserves spatial metadata)
    - dict (AffineGrid*d auto-inferred)
    - BioImageBase
    - NumPy arrays
    """
    _monai_transform = tfms.AffineGrid

# %% ../nbs/030_transforms.ipynb #1e0bc9f5
class GridDistortion(MonaiTransform):
    """
    MONAI GridDistortion wrapper using MonaiTransform.

    Supports:
    - MetaTensor (preserves spatial metadata)
    - dict (GridDistortion*d auto-inferred)
    - BioImageBase
    - NumPy arrays
    """
    _monai_transform = tfms.GridDistortion

# %% ../nbs/030_transforms.ipynb #db4c0435
class GaussianSmooth(MonaiTransform):
    """
    Apply Gaussian smoothing to the input image.

    Parameters
    ----------
    sigma : float or sequence
        Standard deviation of the Gaussian kernel.
    approx : str
        Kernel approximation method.
    """
    _monai_transform = tfms.GaussianSmooth

    def __init__(self, sigma=1.0, approx="erf", **kwargs):
        super().__init__(
            has_channels=True,
            sigma=sigma,
            approx=approx,
            **kwargs
        )


class MedianSmooth(MonaiTransform):
    """
    Apply median filtering to the input image.

    Parameters
    ----------
    radius : int or sequence
        Radius of the median filter kernel.
    """
    _monai_transform = tfms.MedianSmooth

    def __init__(self, radius=1, **kwargs):
        super().__init__(
            has_channels=True,
            radius=radius,
            **kwargs
        )


class SavitzkyGolaySmooth(MonaiTransform):
    """
    Smooth data using a Savitzky-Golay filter.

    Parameters
    ----------
    window_length : int
        Length of the filter window.
    order : int
        Polynomial order.
    axis : int
        Axis along which smoothing is applied.
    mode : str
        Padding mode.
    """
    _monai_transform = tfms.SavitzkyGolaySmooth

    def __init__(self, window_length, order, axis=1, mode="zeros", **kwargs):
        super().__init__(
            has_channels=True,
            window_length=window_length,
            order=order,
            axis=axis,
            mode=mode,
            **kwargs
        )

# %% ../nbs/030_transforms.ipynb #d883888d
Blur = GaussianSmooth

# %% ../nbs/030_transforms.ipynb #7552878a
class GaussianSharpen(MonaiTransform):
    """
    Sharpen images using Gaussian filtering.

    Parameters
    ----------
    sigma1 : float or sequence
        Sigma of the first Gaussian kernel.
    sigma2 : float or sequence
        Sigma of the second Gaussian kernel.
    alpha : float
        Sharpening strength.
    approx : str
        Kernel approximation method.
    """
    _monai_transform = tfms.GaussianSharpen

    def __init__(self, sigma1=3.0, sigma2=1.0, alpha=30.0, approx="erf", **kwargs):
        super().__init__(
            has_channels=True,
            sigma1=sigma1,
            sigma2=sigma2,
            alpha=alpha,
            approx=approx,
            **kwargs
        )

# %% ../nbs/030_transforms.ipynb #75e733b6
class ShiftIntensity(MonaiTransform):
    """
    Shift the intensity values of the entire image by a constant offset.

    This transform uniformly adds an offset to all pixel/voxel values.

    Parameters
    ----------
    offset : float
        Offset value added to the image intensity.
    safe : bool, optional
        If True, performs safe dtype conversion when overflow occurs.
    """
    _monai_transform = tfms.ShiftIntensity

    def __init__(self, offset, safe=False, **kwargs):
        super().__init__(
            offset=offset,
            safe=safe,
            has_channels=True,
            **kwargs
        )


class StdShiftIntensity(MonaiTransform):
    """
    Shift intensity values using the image standard deviation.

    The transform modifies intensity values using:
        v = v + factor * std(v)

    Parameters
    ----------
    factor : float
        Multiplicative factor applied to the image standard deviation.
    nonzero : bool, optional
        If True, compute statistics only on non-zero values.
    channel_wise : bool, optional
        Compute statistics separately for each channel.
    dtype : data-type, optional
        Output data type.
    """
    _monai_transform = tfms.StdShiftIntensity
    
    def __init__(self, factor, nonzero=False, channel_wise=False, dtype=np.float32, **kwargs):
        super().__init__(
            factor=factor,
            nonzero=nonzero,
            channel_wise=channel_wise,
            dtype=dtype,
            has_channels=True,
            **kwargs
        )

# %% ../nbs/030_transforms.ipynb #409a18ef
def _scale_intensity_range(x,   # The input image to scale.
                           mi,  # The minimum intensity value.
                           ma,  # The maximum intensity value.
                           eps=1e-20, # A small value to prevent division by zero.
                           dtype=np_float32, # The data type to use for the output image.
                           ):
    if dtype is not None:
        x = x.astype(dtype, copy=False)
        mi = dtype(mi) if isscalar(mi) else mi.astype(dtype, copy=False)
        ma = dtype(ma) if isscalar(ma) else ma.astype(dtype, copy=False)
        eps = dtype(eps)
        x = (x - mi) / (ma - mi + eps)
    return x

# %% ../nbs/030_transforms.ipynb #1f6fe6dd
class ScaleImage(Transform):
    """Image normalization."""
    def __init__(x,                 # The input image to scale.
                 min=0.0,           # The minimum intensity value.
                 max=1.0,           # The maximum intensity value.
                 axis=None,         # The axis or axes along which to compute the minimum and maximum values.
                 eps=1e-20,         # A small value to prevent division by zero.
                 dtype=np_float32,  # The data type to use for the output image.
                 ):
        store_attr()

    def encodes(self, x: BioImageBase):
        """Apply intensity scaling to a BioImageBase object."""
        bioimagetype = type(x)
        y = _scale_intensity_range(x, x.min(), x.max(), eps=self.eps, dtype=self.dtype)
        y *= self.max
        y += self.min
        return bioimagetype(y)
    
    def encodes(self, x: np.ndarray):
        """Apply intensity scaling to a NumPy array."""
        mi = x.min(axis=self.axis, keepdims=True)
        ma = x.max(axis=self.axis, keepdims=True)
        y = (x - mi) / (ma - mi + self.eps)  # Normalize to [0, 1]
        y = y * (self.max - self.min) + self.min  # Scale to [min, max]
        return y.astype(self.dtype)


# %% ../nbs/030_transforms.ipynb #567bbaab
class ScaleImagePercentiles(Transform):
    """Percentile-based image normalization."""
    def __init__(x,                 # The input image to scale.
                 pmin=3,            # The minimum percentile value.
                 pmax=99.8,         # The maximum percentile value.
                 axis=None,         # The axis or axes along which to compute the minimum and maximum values.
                 clip=True,         # If True, clips the output values to the specified range.
                 b_min=0.0,         # The minimum intensity value.
                 b_max=1.0,         # The maximum intensity value.
                 eps=1e-20,         # A small value to prevent division by zero.
                 dtype=np_float32,  # The data type to use for the output image.
                 ):
        store_attr()

    def encodes(self, x: BioImageBase):
        """Apply percentile-based normalization to a BioImageBase object."""
        bioimagetype = type(x)
        mi = percentile(x, self.pmin, axis=self.axis, keepdims=True)
        ma = percentile(x, self.pmax, axis=self.axis, keepdims=True)
        if self.clip:
            return bioimagetype(np.clip(_scale_intensity_range(x, mi, ma, eps=self.eps, dtype=self.dtype), self.b_min, self.b_max))
        return bioimagetype(_scale_intensity_range(x, mi, ma, eps=self.eps, dtype=self.dtype))
    
    def encodes(self, x: np.ndarray):
        """Apply percentile-based normalization to a NumPy array."""
        mi = np.percentile(x, self.pmin, axis=self.axis, keepdims=True)
        ma = np.percentile(x, self.pmax, axis=self.axis, keepdims=True)
        scaled = (x - mi) / (ma - mi + self.eps)
        scaled = scaled.astype(self.dtype)

        if self.clip:
            return np.clip(scaled, self.b_min, self.b_max)
        return scaled


# %% ../nbs/030_transforms.ipynb #21775c1d
class ScaleImageVariance(Transform):
    """
    Scales the intensity variance of an ND image to a target value.
    """
    def __init__(self, target_variance=1.0, # The desired variance for the scaled intensities.
                 ndim=2, # Number of spatial dimensions in the image.
                 ):
        store_attr()
        
    def encodes(self, x: BioImageBase):
        """Apply intensity variance scaling to a BioImageBase object."""
        bioimagetype = type(x)
        # Calculate the current variance of the image intensities
        mean, variance = torch.mean(x), torch.var(x)
        if variance == 0:
            return bioimagetype(x)  # Avoid division by zero
        # Calculate the scaling factor based on the ratio of target to current variance
        scale_factor = (self.target_variance / variance).sqrt()
        # Apply the scaling factor to each channel in the image
        if x.ndim == self.ndim + 1:  # Check if it's a multi-channel image (e.g., RGB)
            for i in range(x.shape[0]):
                x[i] = (x[i] - mean) * scale_factor
        else:
            x = (x - mean) * scale_factor
        return bioimagetype(x)
    
    def encodes(self, x: np.ndarray):
        """Apply intensity variance scaling to a NumPy array."""
        mean = np.mean(x)
        variance = np.var(x)
        if variance == 0:
            return x  # Avoid division by zero
        scale_factor = np.sqrt(self.target_variance / variance)
        return (x - mean) * scale_factor


# %% ../nbs/030_transforms.ipynb #18c593a5
class ScaleIntensity(MonaiTransform):
    """
    Scale image intensity to a specified range or by a multiplicative factor.

    Parameters
    ----------
    minv : float, optional
        Minimum output intensity value.
    maxv : float, optional
        Maximum output intensity value.
    factor : float, optional
        Scaling factor applied as v = v * (1 + factor).
    channel_wise : bool, optional
        If True, scale each channel independently.
    dtype : data-type, optional
        Output data type.
    """
    _monai_transform = tfms.ScaleIntensity

    def __init__(self, minv=0.0, maxv=1.0, factor=None, channel_wise=False, dtype=np.float32, **kwargs):
        super().__init__(
            minv=minv,
            maxv=maxv,
            factor=factor,
            channel_wise=channel_wise,
            dtype=dtype,
            has_channels=True,
            **kwargs
        )


class ScaleIntensityFixedMean(MonaiTransform):
    """
    Scale intensity while preserving the original mean.

    After scaling intensities, the transform shifts the output so that
    the mean intensity remains equal to the input mean.

    Parameters
    ----------
    factor : float
        Scaling factor applied to the image.
    preserve_range : bool
        Clip the output to the original intensity range.
    fixed_mean : bool
        Preserve the original image mean after scaling.
    channel_wise : bool
        Apply scaling independently to each channel.
    dtype : data-type
        Output data type.
    """

    _monai_transform = tfms.ScaleIntensityFixedMean

    def __init__(self, factor=0, preserve_range=False, fixed_mean=True, channel_wise=False, dtype=np.float32, **kwargs):
        super().__init__(
            factor=factor,
            preserve_range=preserve_range,
            fixed_mean=fixed_mean,
            channel_wise=channel_wise,
            dtype=dtype,
            has_channels=True,
            **kwargs
        )


class ScaleIntensityRange(MonaiTransform):
    """
    Linearly rescale intensities from one range to another.

    Parameters
    ----------
    a_min : float
        Minimum value of the input intensity range.
    a_max : float
        Maximum value of the input intensity range.
    b_min : float, optional
        Minimum value of the target intensity range.
    b_max : float, optional
        Maximum value of the target intensity range.
    clip : bool
        Clip intensities after scaling.
    dtype : data-type
        Output data type.
    """

    _monai_transform = tfms.ScaleIntensityRange

    def __init__(self, a_min, a_max, b_min=None, b_max=None, clip=False, dtype=np.float32, **kwargs):
        super().__init__(
            a_min=a_min,
            a_max=a_max,
            b_min=b_min,
            b_max=b_max,
            clip=clip,
            dtype=dtype,
            has_channels=True,
            **kwargs
        )


class ScaleIntensityRangePercentiles(MonaiTransform):
    """
    Scale intensity values based on image percentiles.

    The transform maps the intensity range defined by two percentiles
    to a target range.

    Parameters
    ----------
    lower : float
        Lower intensity percentile.
    upper : float
        Upper intensity percentile.
    b_min : float
        Target minimum intensity.
    b_max : float
        Target maximum intensity.
    clip : bool
        Clip intensities after scaling.
    relative : bool
        Scale relative to the output range percentiles.
    channel_wise : bool
        Apply independently to each channel.
    dtype : data-type
        Output data type.
    """

    _monai_transform = tfms.ScaleIntensityRangePercentiles

    def __init__(self, lower, upper, b_min, b_max, clip=False, relative=False, channel_wise=False, dtype=np.float32, **kwargs):
        super().__init__(
            lower=lower,
            upper=upper,
            b_min=b_min,
            b_max=b_max,
            clip=clip,
            relative=relative,
            channel_wise=channel_wise,
            dtype=dtype,
            has_channels=True,
            **kwargs
        )

# %% ../nbs/030_transforms.ipynb #16cf8bca
class NormalizeIntensity(MonaiTransform):
    """
    Normalize image intensity using mean and standard deviation.

    The transform performs:
        (img - subtrahend) / divisor

    Parameters
    ----------
    subtrahend : float or sequence, optional
        Value subtracted from the image (usually mean).
    divisor : float or sequence, optional
        Value used for division (usually std).
    nonzero : bool
        Normalize only non-zero values.
    channel_wise : bool
        Compute statistics independently per channel.
    dtype : data-type
        Output data type.
    """
    _monai_transform = tfms.NormalizeIntensity

    def __init__(self, subtrahend=None, divisor=None, nonzero=False, channel_wise=False, dtype=np.float32, **kwargs):
        super().__init__(
            subtrahend=subtrahend,
            divisor=divisor,
            nonzero=nonzero,
            channel_wise=channel_wise,
            dtype=dtype,
            has_channels=True,
            **kwargs
        )


class HistogramNormalize(MonaiTransform):
    """
    Normalize image intensity using histogram equalization.

    Parameters
    ----------
    num_bins : int
        Number of histogram bins.
    min : float
        Minimum intensity value.
    max : float
        Maximum intensity value.
    mask : ndarray, optional
        Optional mask defining valid histogram regions.
    dtype : data-type
        Output data type.
    """
    _monai_transform = tfms.HistogramNormalize
    def __init__(self, num_bins=256, min=0, max=255, mask=None, dtype=np.float32, **kwargs):
        super().__init__(
            num_bins=num_bins,
            min=min,
            max=max,
            mask=mask,
            dtype=dtype,
            has_channels=True,
            **kwargs
        )

# %% ../nbs/030_transforms.ipynb #68c3caee
class AdjustContrast(MonaiTransform):
    """
    Adjust image contrast using gamma transformation.

    Each pixel intensity is transformed using a gamma function.

    Parameters
    ----------
    gamma : float
        Gamma value controlling contrast.
    invert_image : bool
        Invert image before applying gamma.
    retain_stats : bool
        Preserve mean and standard deviation after transform.
    """
    _monai_transform = tfms.AdjustContrast
    
    def __init__(self, gamma, invert_image=False, retain_stats=False, **kwargs):
        super().__init__(
            gamma=gamma,
            invert_image=invert_image,
            retain_stats=retain_stats,
            has_channels=True,
            **kwargs
        )

# %% ../nbs/030_transforms.ipynb #95558960
class RelabelInstances(Transform):
    """Remap instance mask labels to consecutive integers.
    
    Example:
        [0, 1, 3, 7, 18] → [0, 1, 2, 3, 4]
    """

    def __init__(self,
                 background=0,        # Label considered background
                 dtype=np.int32,      # Output dtype
                 ):
        store_attr()

    def encodes(self, x: BioImageBase):
        bioimagetype = type(x)

        arr = np.asarray(x)

        unique_labels = np.unique(arr)
        fg_labels = unique_labels[unique_labels != self.background]

        new_ids = np.arange(1, len(fg_labels) + 1, dtype=self.dtype)
        mapping = dict(zip(fg_labels, new_ids))

        y = np.full_like(arr, self.background, dtype=self.dtype)

        for old_id, new_id in mapping.items():
            y[arr == old_id] = new_id

        return bioimagetype(y)
    
    def encodes(self, x: np.ndarray):
        """Relabel instance mask (NumPy array)."""

        x = np.asarray(x)

        unique_labels = np.unique(x)

        # Remove background from remapping
        fg_labels = unique_labels[unique_labels != self.background]

        # Create mapping dictionary
        new_ids = np.arange(1, len(fg_labels) + 1, dtype=self.dtype)
        mapping = dict(zip(fg_labels, new_ids))

        # Initialize output
        y = np.full_like(x, self.background, dtype=self.dtype)

        # Apply mapping
        for old_id, new_id in mapping.items():
            y[x == old_id] = new_id

        return y

# %% ../nbs/030_transforms.ipynb #1ffaa4e5
class InstanceToMaskAndDistance(Transform):
    """
    Converts a single-channel instance segmentation map (CHW or CDHW)
    into a 2-channel image:

    Channel 0: Binary mask (instances > 0)
    Channel 1: Distance transform (inside objects)
    """

    def __init__(self, 
                 has_channels=True,  # If False, adds channel dim
                 normalize=True,     # Normalize distance map per instance
                 ):
        store_attr()

    def encodes(self, img: BioImageBase):
        return type(img)(self._process(img.numpy()))

    def encodes(self, img: np.ndarray):
        if not self.has_channels:
            img = np.expand_dims(img, axis=0)

        return self._process(img)

    def _process(self, img: np.ndarray):
        """
        img: (C,H,W) or (C,D,H,W) with C=1
        """
        assert img.shape[0] == 1, "Input must have exactly 1 channel"

        inst = img[0]
        binary = (inst > 0).astype(np.uint8)

        # distance inside objects
        dist = distance_transform_edt(binary)

        if self.normalize and dist.max() > 0:
            dist = dist / dist.max()

        # stack channels
        out = np.stack([binary, dist], axis=0)

        return out.astype(np.float32)

# %% ../nbs/030_transforms.ipynb #f751f799
class ComputeHoVerMaps(MonaiTransform):
    """
    Compute HoVer maps (horizontal and vertical distance maps) from instance masks.

    These maps are commonly used in HoVer-Net based nucleus segmentation.

    Parameters
    ----------
    dtype : data-type
        Output data type.
    """

    _monai_transform = tfms.ComputeHoVerMaps

# %% ../nbs/030_transforms.ipynb #c2c0c55f
class ThresholdIntensity(MonaiTransform):
    """
    Filter image intensities using a threshold.

    Values above or below the threshold are replaced with a constant value.

    Parameters
    ----------
    threshold : float
        Intensity threshold.
    above : bool
        If True, filter values above the threshold.
    cval : float
        Fill value for filtered pixels.
    """
    _monai_transform = tfms.ThresholdIntensity

    def __init__(self, threshold, above=True, cval=0.0, **kwargs):
        super().__init__(
            threshold=threshold,
            above=above,
            cval=cval,
            has_channels=True,
            **kwargs
        )


class MaskIntensity(MonaiTransform):
    """
    Mask intensity values using a binary mask.

    Pixels outside the mask are set to zero.

    Parameters
    ----------
    mask_data : ndarray, optional
        Binary mask defining valid regions.
    select_fn : callable, optional
        Function defining valid mask values.
    """
    _monai_transform = tfms.MaskIntensity

    def __init__(self, mask_data=None, select_fn=None, **kwargs):
        super().__init__(
            mask_data=mask_data,
            select_fn=select_fn,
            has_channels=True,
            **kwargs
        )


class ForegroundMask(MonaiTransform):
    """
    Generate a binary foreground mask based on image intensity.

    Parameters
    ----------
    threshold : int, float, callable, or str
        Threshold method or value.
    hsv_threshold : optional
        Threshold defined in HSV space.
    invert : bool
        Invert image before thresholding.
    """
    _monai_transform=tfms.ForegroundMask

    def __init__(self, threshold="otsu", hsv_threshold=None, invert=False, **kwargs):
        super().__init__(
            threshold=threshold,
            hsv_threshold=hsv_threshold,
            invert=invert,
            has_channels=True,
            **kwargs
        )

# %% ../nbs/030_transforms.ipynb #0879d854
from skimage.color import rgb2hed, hed2rgb

# %% ../nbs/030_transforms.ipynb #1da05998
class RGB2HED(Transform):
    """Convert RGB images to HED color space."""
    def encodes(self, x: BioImageBase):
        bioimagetype = type(x)
        x = ScaleIntensity()(x).numpy()  # Ensure the image is scaled to [0, 1] before conversion
        ihc = rgb2hed(x.transpose(1, 2, 0)).transpose(2, 0, 1)  # Convert from (C, H, W) to (H, W, C) for rgb2hed, then back to (C, H, W)
        return bioimagetype(torchTensor(ihc))  # Return the converted image with the same type as the input
    
    def encodes(self, x: np.ndarray):
        x = ScaleIntensity()(x)  # Ensure the image is scaled to [0, 1] before conversion
        return rgb2hed(x.transpose(1, 2, 0)).transpose(2, 0, 1)  # Convert from (C, H, W) to (H, W, C) for rgb2hed, then back to (C, H, W)

# %% ../nbs/030_transforms.ipynb #516c0f4f
class HED2RGB(Transform):
    """Convert HED images back to RGB color space."""
    def encodes(self, x: BioImageBase):
        bioimagetype = type(x)
        x = ScaleIntensity()(x).numpy()  # Ensure the image is scaled to [0, 1] before conversion
        rgb = hed2rgb(x.transpose(1, 2, 0)).transpose(2, 0, 1)  # Convert from (C, H, W) to (H, W, C) for hed2rgb, then back to (C, H, W)
        return bioimagetype(torchTensor(rgb))  # Return the converted image with the same type as the input
    
    def encodes(self, x: np.ndarray):
        x = ScaleIntensity()(x)  # Ensure the image is scaled to [0, 1] before conversion
        return hed2rgb(x.transpose(1, 2, 0)).transpose(2, 0, 1)  # Convert from (C, H, W) to (H, W, C) for hed2rgb, then back to (C, H, W)

# %% ../nbs/030_transforms.ipynb #3f829aa9
def _process_sz(size, ndim=3):
    if isinstance(size,int): 
        size=(size,)*ndim
    return fastuple(size)

def _get_sz(x):
    if isinstance(x, tuple): x = x[0]
    if not isinstance(x, Tensor): return fastuple(x.size)
    return fastuple(getattr(x, 'img_size', getattr(x, 'sz', (x.shape[1:])))) # maybe it should swap x and y axes 

# %% ../nbs/030_transforms.ipynb #b072bd30
class RandCrop2D(RandTransform):
    """
    Randomly crops a 2D image to a specified size.

    This transform randomly crops a 2D image to a specified size during training and 
    performs a center crop during validation.
    """
    split_idx,order = None,1
    def __init__(self, 
        size:int|tuple, # Size to crop to, duplicated if one value is specified
        lazy = False,   # a flag to indicate whether this transform should execute lazily or not. Defaults to False
        **kwargs
    ):
        size = _process_sz(size, ndim=2)
        store_attr()
        super().__init__(**kwargs)

    def before_call(self, 
        b, 
        split_idx:int # Index of the train/valid dataset
    ):
        "Randomly positioning crop if train dataset else center crop"
        self.orig_sz = _get_sz(b)
        if split_idx: self.ctr = (self.orig_sz)//2
        else:
            wd = self.orig_sz[0] - self.size[0]
            hd = self.orig_sz[1] - self.size[1]
            w_rand = (wd, -1) if wd < 0 else (0, wd)
            h_rand = (hd, -1) if hd < 0 else (0, hd)
            self.ctr = fastuple(random.randint(*w_rand)+self.size[0]//2, random.randint(*h_rand)+self.size[1]//2)

    def encodes(self, x: BioImageBase):
        """Apply spatial cropping to a BioImageBase object."""
        bioimagetype = type(x)
        return bioimagetype(tfms.SpatialCrop(roi_center=self.ctr, roi_size=self.size, lazy=self.lazy)(x))
    
    def encodes(self, x: np.ndarray):
        """Apply spatial cropping to a NumPy array."""
        half_w, half_h = self.size[0] // 2, self.size[1] // 2
        cx, cy = self.ctr

        # Calculate crop region
        x_start, x_end = max(cx - half_w, 0), min(cx + half_w, x.shape[0])
        y_start, y_end = max(cy - half_h, 0), min(cy + half_h, x.shape[1])

        return x[x_start:x_end, y_start:y_end]

# %% ../nbs/030_transforms.ipynb #4ae153f1
class RandCropND(RandTransform):
    """
    Randomly crops an ND image to a specified size.

    This transform randomly crops an ND image to a specified size during training and performs
    a center crop during validation. It supports both 2D and 3D images and videos, assuming
    the first dimension is the batch dimension.
    """

    split_idx,order = None,1
        
    def __init__(self, size: int | tuple, # Size to crop to, duplicated if one value is specified
                 lazy = False,            # a flag to indicate whether this transform should execute lazily or not. Defaults to False
                 **kwargs):
        size = _process_sz(size)
        store_attr()
        super().__init__(**kwargs)

    def before_call(self, b, split_idx: int):
        "Randomly position crop if train dataset else center crop"
        self.orig_sz = _get_sz(b)
        if split_idx:
            self.tl = tuple((osz - sz) // 2 for osz, sz in zip(self.orig_sz, self.size))
            self.br = tuple((osz + sz) // 2 for osz, sz in zip(self.orig_sz, self.size))
        else:
            tl = [] # top-left corner
            br = [] # bottom-right corner
            # Calculate top-left and bottom-right corner coordinates for random crop
            for osz, sz in zip(self.orig_sz, self.size):
                w_dif = osz - sz
                if w_dif < 0:
                    w_rand = (0, 0) # No random cropping if input size is smaller than crop size
                    sz = osz # Adjust crop size to match input size
                else:
                    w_rand = (0, w_dif)
                rnd = random.randint(*w_rand)
                tl.append(rnd)
                br.append(rnd + sz)
            self.tl = fastuple(*tl)
            self.br = fastuple(*br)

    def encodes(self, x:BioImageBase):
        "Apply spatial crop transformation to the input image."
        bioimagetype = type(x)
        return bioimagetype(tfms.SpatialCrop(roi_start=self.tl, roi_end=self.br, lazy=self.lazy)(x))
    
    def encodes(self, x: np.ndarray):
        """Apply spatial cropping to a NumPy array."""
        slices = tuple(slice(t, b) for t, b in zip(self.tl, self.br))
        return x[slices]
    

# %% ../nbs/030_transforms.ipynb #c0f5f953
class RandFlip(RandTransform):
    """
    Randomly flips an ND image over a specified axis.
    Works with both NumPy arrays and BioImageBase objects.
    """

    split_idx, order = None, 1

    def __init__(self, 
                 prob=0.1,            # Probability of flipping
                 spatial_axis=None,   # Axes to flip. Default is None (random selection)
                 ndim=2,              # Number of spatial dimensions
                 lazy=False,          # Flag for lazy execution (for BioImageBase)
                 **kwargs):
        store_attr()
        self.p = prob  # Will be set in `before_call`

    def before_call(self, b=None, split_idx: int = 0):
        """Determine whether to apply flipping and choose random axes if needed."""
        super().before_call(b, split_idx)

        # If no specific axis is given, randomly select axes to flip
        if self.spatial_axis is None:
            self.spatial_axis = np.random.choice(
                np.arange(self.ndim), 
                size=np.random.randint(1, self.ndim + 1), 
                replace=False
            )

    def encodes(self, x: BioImageBase):
        """Applies flipping to a  BioImageBase object."""
        bioimagetype = type(x)
        return bioimagetype(tfms.Flip(spatial_axis=self.spatial_axis, lazy=self.lazy)(x))

    def encodes(self, x: np.ndarray):
        """Applies flipping to a NumPy array object."""
        for axis in np.atleast_1d(self.spatial_axis):
            x = np.flip(x, axis=axis)
        return x
        

# %% ../nbs/030_transforms.ipynb #38824529
class RandRot90(RandTransform):
    """
    Randomly rotate an ND image by 90 degrees in the plane specified by axes.

    """

    split_idx,order = None,1
        
    def __init__(self, 
                 prob = 0.1,            # Probability of rotating
                 k = None,                 # Number of times to rotate by 90 degrees. If k is None, it will be set randomly in `before_call`.
                 max_k = 3,             # Max number of times to rotate by 90 degrees
                 spatial_axes = (0, 1), # Spatial axes that define the plane around which to rotate. Default: (0, 1), this are the first two axis in spatial dimensions.
                 ndim = 2,              # Number of spatial dimensions
                 lazy = False,          # Flag to indicate whether this transform should execute lazily or not. Defaults to False
                 **kwargs):
        store_attr()
        self.p = prob 
        super().__init__(**kwargs)

    def before_call(self, b, split_idx: int):
        super().before_call(b, split_idx)
        if self.k is None:
            self.k = 1 + np.random.randint(self.max_k)
          
    def encodes(self, x:BioImageBase):
        bioimagetype = type(x)
        return bioimagetype(tfms.Rotate90(k=self.k, spatial_axes=self.spatial_axes, lazy=self.lazy)(x))
    
    def encodes(self, x: np.ndarray):
        return np.rot90(x, self.k, axes=self.spatial_axes)

# %% ../nbs/030_transforms.ipynb #697116d4
class RandRotation(RandTransform):
    """
    Randomly rotate the input arrays.

    """

    split_idx = None
        
    def __init__(self, 
                 prob = 0.1,            # Probability of rotating
                 range_x=None,
                 range_y=None, 
                 range_z=None,
                 ndim=2,
                 has_channels=True,
                 keep_size=True, 
                 mode=GridSampleMode.BILINEAR, 
                 padding_mode=GridSamplePadMode.BORDER, 
                 align_corners=False, 
                 dtype=torch.float32, 
                 lazy = False,          # Flag to indicate whether this transform should execute lazily or not. Defaults to False
                 **kwargs):
        store_attr()
        self.p = prob 
        super().__init__(**kwargs)

    def _sample_range(self, r):
        """Sample a value from a float or (min,max) range."""
        if r is None:
            return 0.0
        if np.iterable(r):
            return np.random.uniform(r[0], r[1])
        return np.random.uniform(-r, r)


    def sample_rotation(self, range_x, range_y=None, range_z=None, ndim=2):
        """
        Sample rotation angle(s) in radians.
        
        Returns
        -------
        float for 2D
        tuple(float,float,float) for 3D
        """
        
        if ndim == 2:
            return self._sample_range(range_x)

        if ndim == 3:
            ax = self._sample_range(range_x)
            ay = self._sample_range(range_y)
            az = self._sample_range(range_z)
            return (ax, ay, az)

        raise ValueError("ndim must be 2 or 3")

    def before_call(self, b, split_idx: int):
        super().before_call(b, split_idx)
        self.angle = self.sample_rotation(range_x=self.range_x, range_y=self.range_y, range_z=self.range_z, ndim=self.ndim)
        self._process = tfms.Rotate(self.angle, keep_size=self.keep_size, mode=self.mode, padding_mode=self.padding_mode, align_corners=self.align_corners, dtype=self.dtype, lazy=self.lazy)
      
    def encodes(self, x:BioImageBase):
        bioimagetype = type(x)
        return bioimagetype(self._process(x))
    
    def encodes(self, img: np.ndarray):
        """Transforms a NumPy array to BioImage and applies Rotate."""
        if not self.has_channels:
            img = np.expand_dims(img, axis=0)  # Add channel dimension if not present
        tensor_img = Tensor2BioImage()(torchTensor(img))
        return self._process(tensor_img).numpy()

# %% ../nbs/030_transforms.ipynb #74e4a03d
class RandZoom(RandTransform):
    """
    Randomly zoom the input arrays with given probability within given zoom range.

    """

    split_idx = None
        
    def __init__(self, 
                 prob = 0.1,            # Probability of the transform
                 min_zoom=0.9, 
                 max_zoom=1.1,
                 has_channels=True,
                 keep_size=True, 
                 mode=InterpolateMode.AREA, 
                 padding_mode=NumpyPadMode.EDGE, 
                 align_corners=None, 
                 dtype=torch.float32, 
                 lazy = False,          # Flag to indicate whether this transform should execute lazily or not. Defaults to False
                 **kwargs):
        store_attr()
        self.p = prob 
        super().__init__(**kwargs)

    def before_call(self, b, split_idx: int):
        super().before_call(b, split_idx)
        self.zoom = np.random.uniform(self.min_zoom, self.max_zoom)
        self._process = tfms.Zoom(self.zoom, keep_size=self.keep_size, mode=self.mode, padding_mode=self.padding_mode, align_corners=self.align_corners, dtype=self.dtype, lazy=self.lazy)
      
    def encodes(self, x:BioImageBase):
        bioimagetype = type(x)
        return bioimagetype(self._process(x))
    
    def encodes(self, img: np.ndarray):
        """Transforms a NumPy array to BioImage and applies Rotate."""
        if not self.has_channels:
            img = np.expand_dims(img, axis=0)  # Add channel dimension if not present
        tensor_img = Tensor2BioImage()(torchTensor(img))
        return self._process(tensor_img).numpy()

# %% ../nbs/030_transforms.ipynb #14c19a89
class RandCameraNoise(RandTransform):
    """
    Simulates camera noise with typedispatch support:
    - MetaTensor (kept in tensor domain)
    - dict (image key-based pipeline)
    - BioImageBase (type preserved)
    - NumPy arrays
    """

    def __init__(
        self,
        p: float = 1.0,
        damp=1e-2,
        qe=0.7,
        gain=2,
        offset=100,
        exp_time=0.1,
        dark_current=0.6,
        readout=1.5,
        bitdepth=16,
        seed=42,
        simulation=False,
        camera='cmos',
        gain_variance=0.1,
        offset_variance=5,
        keys=None,  # <-- for dict support
    ):
        store_attr()
        self.rs = np.random.RandomState(seed=seed)

    # -------------------------
    # CORE NOISE FUNCTION 
    # -------------------------
    def _apply_noise(self, x, rs):
        max_adu = float(2**self.bitdepth - 1)

        # normalize input
        if x.min() >= 0.0 and x.max() <= 1.0:
            x = (x * max_adu).astype(np.uint16 if self.bitdepth > 8 else np.uint8)

        # photon model
        if not self.simulation:
            photons = x / self.gain / self.qe * self.damp
        else:
            photons = x

        photons = rs.poisson(photons, size=photons.shape)
        electrons = self.qe * photons

        # dark current
        electrons += rs.poisson(self.dark_current * self.exp_time, size=electrons.shape)

        # read noise (FIX: std should NOT be squared)
        electrons += rs.normal(scale=self.readout, size=electrons.shape) * (self.bitdepth / 16)

        gain = np.broadcast_to(self.gain, electrons.shape).astype(np.float32).copy()
        offset = np.broadcast_to(self.offset, electrons.shape).astype(np.float32).copy()

        if self.camera == 'cmos':
            gain_noise = rs.normal(scale=self.gain_variance, size=electrons.shape)
            offset_noise = (
                rs.normal(scale=self.offset_variance, size=electrons.shape)
                + rs.normal(scale=self.offset_variance, size=(electrons.shape[0],))
            )

            gain = gain + gain_noise
            offset = offset + offset_noise

        adu = electrons * gain + offset
        adu = np.clip(adu, 0, max_adu)

        return adu

    # -------------------------
    # MetaTensor
    # -------------------------
    def encodes(self, x: "MetaTensor"):
        rs = np.random.RandomState(self.rs.randint(0, 2**32 - 1))
        out = self._apply_noise(x, rs)
        return type(x)(out)

    # -------------------------
    # torch.Tensor
    # -------------------------
    def encodes(self, x: torchTensor):
        rs = np.random.RandomState(self.rs.randint(0, 2**32 - 1))
        out = self._apply_noise(x.numpy(), rs)
        return torch.as_tensor(out)

    # -------------------------
    # dict (MONAI-style)
    # -------------------------
    def encodes(self, x: dict):
        if self.keys is None:
            raise ValueError("keys must be provided for dict input")

        rs = np.random.RandomState(self.rs.randint(0, 2**32 - 1))

        x = dict(x)  # avoid mutation
        for k in self.keys:
            x[k] = self._apply_noise(x[k], rs)

        return x

    # -------------------------
    # BioImageBase
    # -------------------------
    def encodes(self, x: BioImageBase):
        rs = np.random.RandomState(self.rs.randint(0, 2**32 - 1))
        out = self._apply_noise(x, rs)
        return type(x)(out)

    # -------------------------
    # NumPy
    # -------------------------
    def encodes(self, x: np.ndarray):
        rs = np.random.RandomState(self.rs.randint(0, 2**32 - 1))
        return self._apply_noise(x, rs)

# %% ../nbs/030_transforms.ipynb #a55abc6e
class RandGaussianNoise(RandMonaiTransform):
    """
    Add Gaussian noise to image.
    """

    def __init__(self,
                 mean=0.0, 
                 std=0.1,
                 prob=0.1,
                 dtype=np.float32,
                 has_channels=True):

        super().__init__(
            tfms.RandGaussianNoise,
            prob=prob,
            param_sampler=None,
            has_channels=has_channels,
            mean=mean, 
            std=std,
            dtype=dtype,
        )

# %% ../nbs/030_transforms.ipynb #97c264d8
class RandGaussianSmooth(RandMonaiTransform):
    """
    Apply Gaussian smoothing with randomly sampled sigma.
    """

    def __init__(self,
                 sigma_x=(0.5,1.5),
                 sigma_y=None,
                 sigma_z=None,
                 prob=0.1,
                 approx="erf",
                 has_channels=True):

        def sample_sigma(r):
            if r is None:
                return None
            if np.iterable(r):
                return np.random.uniform(r[0], r[1])
            return r

        def param_sampler():
            sigma = tuple(filter(None, [
                sample_sigma(sigma_x),
                sample_sigma(sigma_y),
                sample_sigma(sigma_z)
            ]))

            return dict(sigma=sigma)

        super().__init__(
            tfms.GaussianSmooth,
            prob=prob,
            param_sampler=param_sampler,
            has_channels=has_channels,
            approx=approx
        )

# %% ../nbs/030_transforms.ipynb #0cd57b2b
RandBlur = RandGaussianSmooth

# %% ../nbs/030_transforms.ipynb #2fdcaa3a
class RandGaussianSharpen(RandMonaiTransform):
    """
    Randomly sharpen image using Gaussian kernels.
    """

    def __init__(self,
                 sigma1=(0.5,1.0),
                 sigma2=(0.5,1.0),
                 alpha=(10.0,30.0),
                 prob=0.1,
                 approx="erf",
                 has_channels=True):

        def sample(r):
            if np.iterable(r):
                return np.random.uniform(r[0], r[1])
            return r

        def param_sampler():
            return dict(
                sigma1=sample(sigma1),
                sigma2=sample(sigma2),
                alpha=sample(alpha)
            )

        super().__init__(
            tfms.GaussianSharpen,
            prob=prob,
            param_sampler=param_sampler,
            has_channels=has_channels,
            approx=approx
        )

# %% ../nbs/030_transforms.ipynb #fa3cb5cb
class RandShiftIntensity(RandMonaiTransform):
    """
    Randomly shift image intensity.

    Equivalent to MONAI RandShiftIntensity but uses the deterministic
    ShiftIntensity transform internally.
    """

    def __init__(self,
                 offsets,
                 prob=0.1,
                 safe=False,
                 has_channels=True):

        def param_sampler():
            if np.iterable(offsets):
                offset = np.random.uniform(offsets[0], offsets[1])
            else:
                offset = np.random.uniform(-offsets, offsets)

            return dict(offset=offset)

        super().__init__(
            tfms.ShiftIntensity,
            prob=prob,
            param_sampler=param_sampler,
            has_channels=has_channels,
            safe=safe
        )

class RandStdShiftIntensity(RandMonaiTransform):
    """
    Randomly shift intensity by a factor of the image standard deviation.
    """

    def __init__(self,
                 factors,
                 prob=0.1,
                 nonzero=False,
                 channel_wise=False,
                 has_channels=True):

        def param_sampler():
            if np.iterable(factors):
                factor = np.random.uniform(factors[0], factors[1])
            else:
                factor = np.random.uniform(-factors, factors)

            return dict(factor=factor)

        super().__init__(
            tfms.StdShiftIntensity,
            prob=prob,
            param_sampler=param_sampler,
            has_channels=has_channels,
            nonzero=nonzero,
            channel_wise=channel_wise
        )

# %% ../nbs/030_transforms.ipynb #2d5ca9ca
class RandAdjustContrast(RandMonaiTransform):
    """
    Randomly adjust image contrast using gamma correction.
    """

    def __init__(self,
                 gamma,
                 prob=0.1,
                 invert_image=False,
                 retain_stats=False,
                 has_channels=True):

        def param_sampler():
            if np.iterable(gamma):
                g = np.random.uniform(gamma[0], gamma[1])
            else:
                g = np.random.uniform(1-gamma, 1+gamma)

            return dict(gamma=g)

        super().__init__(
            tfms.AdjustContrast,
            prob=prob,
            param_sampler=param_sampler,
            has_channels=has_channels,
            invert_image=invert_image,
            retain_stats=retain_stats
        )
