"""Data classes and functions"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../../nbs/021_data.core.ipynb.

# %% auto #0
__all__ = ['MetaResolver', 'BioImageBase', 'BioImage', 'BioVolume', 'BioVideo', 'BioMultiChannel', 'Tensor2BioImage']

# %% ../../nbs/021_data.core.ipynb #7a8886ba
# =================================
# Standard library
# =================================
from plum import dispatch



# =================================
# fastai
# =================================
from fastai.torch_core import TensorImage
from fastai.vision.all import merge

# =================================
# bioMONAI
# =================================
from ..utils import *
from ..io import image_reader, image_reader_dict
from ..visualize import show_biodata, show_multichannel

# =================================
# fasttransform patch
# =================================
import fasttransform

_original_repr = fasttransform.transform.Transform.__repr__

def _safe_repr(self):
    try:
        return _original_repr(self)
    except AttributeError as e:
        if "'_BoundFunction' object has no attribute 'methods'" in str(e):
            return f"{self.__class__.__name__}(...)"
        raise

fasttransform.transform.Transform.__repr__ = _safe_repr

# %% ../../nbs/021_data.core.ipynb #4faea311
class MetaResolver(type(torchTensor), metaclass=BypassNewMeta):
    """
    The `MetaResolver` class addresses metaclass conflicts, ensuring compatibility across different data structures. This is particularly useful when integrating with libraries that have specific metaclass requirements.
    """
    pass
    

# %% ../../nbs/021_data.core.ipynb #2ec695f1
@dispatch
def _create(cls, fn: dict, keys=None, **kwargs):
    if keys is None:
        keys = []

    metatensor_dict = cls.load_dict(keys=keys, **kwargs)(fn)

    if isinstance(keys, str):
        keys = [keys]

    for key in keys:
        if key in metatensor_dict:
            x = metatensor_dict[key]
            metatensor_dict[key] = cls(x.data, meta=x.meta)

    return metatensor_dict


@dispatch
def _create(cls, fn: object, **kwargs):
    metatensor = cls.load(**kwargs)(fn)
    return cls(metatensor.data, meta=metatensor.meta)

# %% ../../nbs/021_data.core.ipynb #c04e0a04
class BioImageBase(MetaTensor, TensorImage, metaclass=MetaResolver):
    """
    Base class for bioimaging data.

    Provides:
    - MetaTensor integration
    - visualization utilities
    - lightweight tensor wrapper

    """

    _bypass_type = torchTensor
    _show_args = {"cmap": "gray"}
    _channels="CZYX"
    _transforms = None
    _keys = []

    # --------------------------------------------------
    # BASIC CONSTRUCTORS
    # --------------------------------------------------
    @classmethod
    def from_tensor(cls, x: torchTensor, meta: dict | None = None):
        return cls(x=x, meta=meta or {})

    def as_tensor(self) -> torchTensor:
        return self.as_subclass(torchTensor)
    
    # --------------------------------------------------
    # TRANSFORMS CONFIG
    # --------------------------------------------------
    @classmethod
    def item_preprocessing(cls, transforms):
        cls._transforms = transforms

    # --------------------------------------------------
    # LOADING
    # --------------------------------------------------
    create = classmethod(_create)
    
    # --------------------------------------------------
    # MONAI INTEGRATION
    # --------------------------------------------------
    @classmethod
    def load(cls,**kwargs) -> Callable:
        def _load(fn):
            if isinstance(fn, torchTensor):
                return cls.from_tensor(fn)

            local_kwargs = dict(kwargs)
            local_kwargs.setdefault("channels", cls._channels)
            local_kwargs.setdefault("transforms", cls._transforms)

            return image_reader(
                fn,
                output="metatensor",
                **local_kwargs,
            )

        return _load

    @classmethod
    def load_dict(cls, **kwargs) -> Callable:
        def _load_dict(data: dict|Sequence[dict]):

            local_kwargs = dict(kwargs)
            local_kwargs.setdefault("keys", cls._keys)
            local_kwargs.setdefault("channels", cls._channels)
            local_kwargs.setdefault("transforms", cls._transforms)

            return image_reader_dict(
                data,
                **local_kwargs,
            )

        return _load_dict

    # --------------------------------------------------
    # VISUALIZATION
    # --------------------------------------------------
    def show(self, ctx=None, figsize=None, title=None, **kwargs):
        return show_biodata(
            self,
            ctx=ctx,
            title=[title],
            volume_mode='grid',
            figsize=figsize,
            **merge(self._show_args, kwargs),
        )

    # --------------------------------------------------
    # REPR
    # --------------------------------------------------
    def __repr__(self) -> str:
        return f"{self.__class__.__name__}{self.as_tensor().__repr__()[6:]}"

# %% ../../nbs/021_data.core.ipynb #bcec9658
class BioImage(BioImageBase):
    """
    Tensor-backed bioimage loaded from disk.
    """

    _channels = "CYX"

    # --------------------------------------------------
    # VISUALIZATION
    # --------------------------------------------------
    def show(self, ctx=None, **kwargs):
        "Show image using `merge(self._show_args, kwargs)`"
        return show_biodata(self, ctx=ctx, **merge(self._show_args, kwargs))

    # --------------------------------------------------
    # LOADER FACTORY
    # --------------------------------------------------
    @classmethod
    def load(cls, **kwargs):
        kwargs.setdefault("channels", cls._channels)
        return super().load(**kwargs)

    # --------------------------------------------------
    # DICT LOADER
    # --------------------------------------------------
    @classmethod
    def load_dict(cls, **kwargs):
        kwargs.setdefault("channels", cls._channels)
        return super().load_dict(**kwargs)

# %% ../../nbs/021_data.core.ipynb #a32aa47a
class BioVolume(BioImageBase):
    """
    Tensor-backed bioimage loaded from disk.

    This is the class that:
    - uses image_reader
    - handles transforms
    - returns MetaTensor-backed images
    """

    _channels="CZYX"
    
    # --------------------------------------------------
    # MONAI INTEGRATION
    # --------------------------------------------------
    @classmethod
    def load(cls, **kwargs) -> Callable:
        kwargs.setdefault("channels", cls._channels)
        return super().load(**kwargs)

    @classmethod
    def load_dict(cls, keys, **kwargs) -> Callable:
        kwargs.setdefault("channels", cls._channels)
        return super().load_dict(keys, **kwargs)

# %% ../../nbs/021_data.core.ipynb #b6cdac7d
def _mip_transform(cls, img, layout):
    z_dim = layout.index("Z")

    mip = torchmax(img.as_tensor(), dim=z_dim).values

    meta = dict(img.meta)
    meta["layout"] = layout.replace("Z", "")
    meta["size_output"] = tuple(mip.shape)

    return cls(x=mip, meta=meta)

@dispatch
def _create_mip(
    cls,
    fn: PathLike | Sequence[PathLike] | torchTensor,
    **kwargs,
):
    kwargs.setdefault("channels", cls._channels)

    img = super(cls, cls).create(fn, **kwargs)

    layout = kwargs.get("channels")

    return _mip_transform(cls, img, layout)

@dispatch
def _create_mip(
    cls,
    fn: dict | Sequence[dict],
    keys=None,
    **kwargs,
):
    kwargs.setdefault("channels", cls._channels)

    out = super(cls, cls).create(
        fn,
        keys=keys,
        **kwargs,
    )

    if keys is None:
        keys = []

    if isinstance(keys, str):
        keys = [keys]

    layout = kwargs.get("channels")

    for key in keys:

        img = out[key]

        out[key] = _mip_transform(cls, img, layout)

    return out

# %% ../../nbs/021_data.core.ipynb #0febd1d1
class BioVideo(BioImageBase):
    """
    Tensor-backed video loaded from disk.

    This is the class that:
    - uses image_reader
    - handles transforms
    - returns MetaTensor-backed images
    """

    _channels="CTYX"

    # --------------------------------------------------
    # LOADING
    # --------------------------------------------------
    @classmethod
    def create(
        cls,
        fn: PathLike | Sequence[PathLike] | torchTensor,
        **kwargs,
    ):

        kwargs.setdefault("channels", cls._channels)

        return super().create(fn, **kwargs)
    
    # --------------------------------------------------
    # MONAI INTEGRATION
    # --------------------------------------------------
    @classmethod
    def load(cls, **kwargs) -> Callable:
        kwargs.setdefault("channels", cls._channels)
        return super().load(**kwargs)

    @classmethod
    def load_dict(cls, keys, **kwargs) -> Callable:
        kwargs.setdefault("channels", cls._channels)
        return super().load_dict(keys, **kwargs)

# %% ../../nbs/021_data.core.ipynb #b484acfa
class BioMultiChannel(BioImageBase):
    """
    Multi-channel 2D/3D image assuming CZYX layout.
    """
    @classmethod
    def create(
        cls,
        fn: PathLike | Sequence[PathLike] | torchTensor,
        merge_cd: bool = True,
        interleaved: bool = True,
        **kwargs,
    ):
        kwargs.setdefault("channels", cls._channels)
        tensor = super().create(fn, **kwargs)
        layout = kwargs.get("layout") or tensor.meta.get("layout") or cls._channels

        output_layout = layout
        if merge_cd:
            if layout is None or "C" not in layout or "Z" not in layout:
                raise ValueError(f"BioMultiChannel merge_cd requires C and Z axes, got {layout!r}")

            c_dim = layout.index("C")
            z_dim = layout.index("Z")
            c = tensor.shape[c_dim]
            d = tensor.shape[z_dim]
            spatial_dims = [i for i in range(tensor.ndim) if i not in (c_dim, z_dim)]

            if interleaved:
                permute_dims = [z_dim, c_dim, *spatial_dims]
            else:
                permute_dims = [c_dim, z_dim, *spatial_dims]

            tensor = tensor.permute(*permute_dims)
            tensor = tensor.reshape(c * d, *tensor.shape[2:])
            output_layout = layout.replace("Z", "")

        tensor.meta["layout"] = output_layout
        tensor.meta["size_output"] = tuple(tensor.shape)

        return cls(x=tensor, meta=tensor.meta)

    def show(self, ctx=None, **kwargs):
        return show_multichannel(self, ctx=ctx, **merge(self._show_args, kwargs))

    # --------------------------------------------------
    # MONAI INTEGRATION
    # --------------------------------------------------
    @classmethod
    def load(cls, **kwargs) -> Callable:
        kwargs.setdefault("channels", cls._channels)
        return super().load(**kwargs)

    @classmethod
    def load_dict(cls, keys, **kwargs) -> Callable:
        kwargs.setdefault("channels", cls._channels)
        return super().load_dict(keys, **kwargs)


# %% ../../nbs/021_data.core.ipynb #98c6bb4c
class Tensor2BioImage(DisplayedTransform):
    """
    The `Tensor2BioImage` transform converts tensors into `BioImageBase` instances, enabling the application of bioimaging-specific methods to tensor data. 
    This is essential for integrating deep learning models with bioimaging workflows.
    """
    def __init__(self, cls:BioImageBase=BioImage):
        self.cls = cls

    def encodes(self, o: MetaTensor):
        # return self.cls(o.clone(), affine=o.affine, meta=o.meta)
        return self.cls(o.clone(), meta=o.meta)
    
    def encodes(self, o: BioImageBase):
        # Already converted, pass through
        return o
    
    def encodes(self, o: torchTensor):
        return self.cls(o)
    
    def decodes(self, o: BioImageBase):
        return o
    
    def __repr__(self):
        """Override to handle plum's _BoundFunction from multiple dispatch."""
        enc = 0
        dec = 0
        if hasattr(self, 'encodes'):
            try:
                # For plum dispatch functions, just count as 1 if callable
                enc = 1 if callable(self.encodes) else len(self.encodes.methods)
            except:
                enc = 0
        if hasattr(self, 'decodes'):
            try:
                # For plum dispatch functions, just count as 1 if callable
                dec = 1 if callable(self.decodes) else len(self.decodes.methods)
            except:
                dec = 0
        return f'{self.name}(enc:{enc},dec:{dec})'
