"""Data classes and functions"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../../nbs/021_data.core.ipynb.

# %% auto #0
__all__ = ['MetaResolver', 'BioDataClass', 'BioImageBase', 'BioImage', 'BioVolume', 'BioVideo', 'BioMultiChannel', 'BioLabel']

# %% ../../nbs/021_data.core.ipynb #7a8886ba
# =================================
# Standard library
# =================================
from plum import dispatch



# =================================
# fastai
# =================================
from fastai.torch_core import TensorImage, TensorCategory, TensorMultiCategory
from fastai.vision.all import TransformBlock

# =================================
# bioMONAI
# =================================
from ..utils import *
from ..io import image_reader, image_reader_dict
from ..visualize import show_biodata, show_multichannel

# =================================
# fasttransform patch
# =================================
import fasttransform

_original_repr = fasttransform.transform.Transform.__repr__

def _safe_repr(self):
    try:
        return _original_repr(self)
    except AttributeError as e:
        if "'_BoundFunction' object has no attribute 'methods'" in str(e):
            return f"{self.__class__.__name__}(...)"
        raise

fasttransform.transform.Transform.__repr__ = _safe_repr

# %% ../../nbs/021_data.core.ipynb #4faea311
class MetaResolver(type(torchTensor), metaclass=BypassNewMeta):
    """
    The `MetaResolver` class addresses metaclass conflicts, ensuring compatibility across different data structures. This is particularly useful when integrating with libraries that have specific metaclass requirements.
    """
    pass
    

# %% ../../nbs/021_data.core.ipynb #95565a2c
class BioDataClass(MetaTensor):
    """
    Base class for bioMONAI data.
    """

    _transforms = None
    _keys = []

    # --------------------------------------------------
    # BASIC CONSTRUCTORS
    # --------------------------------------------------
    @classmethod
    def from_tensor(cls, x: torchTensor, meta: dict | None = None):
        return cls(x=x, meta=meta or {})
    
    @classmethod
    def from_metatensor(cls, x: MetaTensor):
        return cls(x=x.data, meta=x.meta)
    
    # --------------------------------------------------
    # TRANSFORMS CONFIG
    # --------------------------------------------------
    @classmethod
    def item_preprocessing(cls, transforms):
        cls._transforms = transforms

    # --------------------------------------------------
    # LOADING
    # --------------------------------------------------
    @classmethod
    def create(cls, x, keys=None, **kwargs):
        raise NotImplementedError("Subclasses must implement the `create` method to define how to instantiate from raw data.")
    
    # --------------------------------------------------
    # MONAI INTEGRATION
    # --------------------------------------------------
    @classmethod
    def load(cls,**kwargs) -> Callable:
        raise NotImplementedError("Subclasses must implement the `load` method to define how to load data.")

    @classmethod
    def load_as_dict(cls, **kwargs) -> Callable:
        raise NotImplementedError("Subclasses must implement the `load_dict` method to define how to load data.")
    
    # --------------------------------------------------
    # CREATE DATABLOCK (fastai integration)
    # --------------------------------------------------
    def get_datablock(self):
        return TransformBlock(type_tfms=[self.create])

    # --------------------------------------------------
    # REPR
    # --------------------------------------------------
    def __repr__(self) -> str:
        return f"{self.__class__.__name__}{self.as_tensor().__repr__()[6:]}"

# %% ../../nbs/021_data.core.ipynb #c04e0a04
class BioImageBase(BioDataClass, TensorImage, metaclass=MetaResolver):
    """
    Base class for bioimaging data.

    Provides:
    - MetaTensor integration
    - visualization utilities
    - lightweight tensor wrapper

    """

    _bypass_type = torchTensor
    _show_args = {"cmap": "gray"}
    _channels = "CZYX"
    _output = 'metatensor'
    _transforms = None
    _keys = ['image']

    # --------------------------------------------------
    # LOADING
    # --------------------------------------------------
    @classmethod
    def create(cls, x, keys=None, **kwargs):
        if isinstance(x, dict):
            if keys is None:
                keys = []

            metatensor_dict = cls.load_as_dict(keys=keys, **kwargs)(x)

            if isinstance(keys, str):
                keys = [keys]

            for key in keys:
                if key in metatensor_dict:
                    x = metatensor_dict[key]
                    metatensor_dict[key] = cls(x.data, meta=x.meta)

            return metatensor_dict

        metatensor = cls.load(**kwargs)(x)
        return cls(metatensor.data, meta=metatensor.meta)
    
    # --------------------------------------------------
    # MONAI INTEGRATION
    # --------------------------------------------------
    @classmethod
    def load(cls,**kwargs) -> Callable:
        def _load(x):
            if isinstance(x, torchTensor):
                return cls.from_tensor(x)

            local_kwargs = dict(kwargs)
            local_kwargs.setdefault("output", cls._output)
            local_kwargs.setdefault("channels", cls._channels)
            local_kwargs.setdefault("transforms", cls._transforms)

            return image_reader(
                x,
                **local_kwargs,
            )

        return _load

    @classmethod
    def load_as_dict(cls, **kwargs) -> Callable:
        def _load_dict(data: dict):

            local_kwargs = dict(kwargs)
            local_kwargs.setdefault("keys", cls._keys)
            local_kwargs.setdefault("output", cls._output)
            local_kwargs.setdefault("channels", cls._channels)
            local_kwargs.setdefault("transforms", cls._transforms)

            return image_reader_dict(
                data,
                **local_kwargs,
            )

        return _load_dict
    
    # --------------------------------------------------
    # VISUALIZATION
    # --------------------------------------------------
    def show(self, ctx=None, figsize=None, title=None, **kwargs):
        return show_biodata(
            self,
            ctx=ctx,
            title=title if title is not None else None,
            volume_mode='grid',
            figsize=figsize,
            **merge(self._show_args, kwargs),
        )
    

# %% ../../nbs/021_data.core.ipynb #bcec9658
class BioImage(BioImageBase):
    """
    Tensor-backed bioimage loaded from disk.
    """

    _channels = "CYX"


# %% ../../nbs/021_data.core.ipynb #a32aa47a
class BioVolume(BioImageBase):
    """
    Tensor-backed volume loaded from disk.

    """

    _channels="CZYX"


# %% ../../nbs/021_data.core.ipynb #b6cdac7d
def _mip_transform(cls, img, layout):
    z_dim = layout.index("Z")

    mip = torchmax(img.as_tensor(), dim=z_dim).values

    meta = dict(img.meta)
    meta["layout"] = layout.replace("Z", "")
    meta["size_output"] = tuple(mip.shape)

    return cls(x=mip, meta=meta)

# %% ../../nbs/021_data.core.ipynb #0febd1d1
class BioVideo(BioImageBase):
    """
    Tensor-backed video loaded from disk.

    This is the class that:
    - uses image_reader
    - handles transforms
    - returns MetaTensor-backed images
    """

    _channels="CTYX"
    

# %% ../../nbs/021_data.core.ipynb #b484acfa
class BioMultiChannel(BioImageBase):
    """
    Multi-channel 2D/3D image assuming CZYX layout.
    """

    @classmethod
    def _apply_mip(cls, tensor, merge_cd, interleaved, **kwargs):
            layout = (
                kwargs.get("layout")
                or getattr(tensor, "meta", {}).get("layout")
                or cls._channels
            )

            if not merge_cd:
                if hasattr(tensor, "meta"):
                    tensor.meta["layout"] = layout
                    tensor.meta["size_output"] = tuple(tensor.shape)
                return tensor

            if layout is None or "C" not in layout or "Z" not in layout:
                raise ValueError(
                    f"BioMultiChannel merge_cd requires C and Z axes, got {layout!r}"
                )

            c_dim = layout.index("C")
            z_dim = layout.index("Z")

            c = tensor.shape[c_dim]
            d = tensor.shape[z_dim]

            spatial_dims = [i for i in range(tensor.ndim) if i not in (c_dim, z_dim)]

            if interleaved:
                permute_dims = [z_dim, c_dim, *spatial_dims]
            else:
                permute_dims = [c_dim, z_dim, *spatial_dims]

            tensor = tensor.permute(*permute_dims)
            tensor = tensor.reshape(c * d, *tensor.shape[2:])

            output_layout = layout.replace("Z", "")

            if hasattr(tensor, "meta"):
                tensor.meta["layout"] = output_layout
                tensor.meta["size_output"] = tuple(tensor.shape)

            return tensor
    
    @classmethod
    def create(
        cls,
        x: PathLike | Sequence[PathLike] | torchTensor,
        keys=None,
        merge_cd: bool = True,
        interleaved: bool = True,
        **kwargs,
    ):
        kwargs.setdefault("channels", cls._channels)

        out = super().create(x, keys=keys, **kwargs)

        if isinstance(out, dict):
            return {k: cls._apply_mip(v, merge_cd=merge_cd, interleaved=interleaved, **kwargs) for k, v in out.items()}

        return cls._apply_mip(out, merge_cd=merge_cd, interleaved=interleaved, **kwargs)

    def show(self, ctx=None, **kwargs):
        return show_multichannel(self, ctx=ctx, **merge(self._show_args, kwargs))



# %% ../../nbs/021_data.core.ipynb #d3ec8d1a
class BioLabel(BioDataClass):
    """
    Data class for Categorical data.

    """

    _keys = ['label']

    # --------------------------------------------------
    # LOADING
    # --------------------------------------------------
    @classmethod
    def create(cls, x, keys=None, **kwargs):
        if isinstance(x, dict):
            if keys is None:
                keys = []

            metatensor_dict = cls.load_as_dict(keys=keys, **kwargs)(x)

            if isinstance(keys, str):
                keys = [keys]

            for key in keys:
                if key in metatensor_dict:
                    x = metatensor_dict[key]
                    metatensor_dict[key] = cls(x.data, meta=x.meta)

            return metatensor_dict

        metatensor = cls.load(**kwargs)(x)
        return cls(metatensor.data, meta=metatensor.meta)
    
    # --------------------------------------------------
    # MONAI INTEGRATION
    # --------------------------------------------------
    @classmethod
    def load(cls,**kwargs) -> Callable:
        def _load(fn):
            if isinstance(fn, torchTensor):
                return cls.from_tensor(fn)

            local_kwargs = dict(kwargs)
            local_kwargs.setdefault("transforms", cls._transforms)

            return image_reader(
                fn,
                **local_kwargs,
            )

        return _load

    @classmethod
    def load_as_dict(cls, **kwargs) -> Callable:
        def _load_dict(data: dict):

            local_kwargs = dict(kwargs)
            local_kwargs.setdefault("keys", cls._keys)
            local_kwargs.setdefault("transforms", cls._transforms)

            return image_reader_dict(
                data,
                **local_kwargs,
            )

        return _load_dict
    
    
