"""Functions for getting, splitting, and labeling data"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../../nbs/023_data.tfms.ipynb.

# %% auto #0
__all__ = ['SlidingWindowSplitter', 'get_images', 'get_gt', 'get_target', 'get_noisy_pair', 'show_batch', 'show_results',
           'split_dataframe', 'build_df', 'build_df_from_folder', 'ProcessImageDataset']

# %% ../../nbs/023_data.tfms.ipynb #7a8886ba
# =================================
# Standard library
# =================================
import os
import random
from inspect import signature, _empty

# =================================
# Third-party scientific stack
# =================================
import h5py
import numpy as np
import pandas as pd
from tqdm import tqdm

# =================================
# Bioimage IO
# =================================
from bioio import BioImage as AICSImage
from bioio import Writer as OmeTiffWriter

# =================================
# PyTorch
# =================================
from torch.utils.data import DataLoader as torchDataLoader

# =================================
# fastai
# =================================
from fastai.vision.all import get_grid

# =================================
# MONAI
# =================================
from monai.inferers import SlidingWindowSplitter, Splitter

# =================================
# bioMONAI
# =================================
from ..utils import *
from ..io import image_reader, _sanitize
from .core import *
from .load import *

# =================================
# fasttransform patch
# =================================
import fasttransform

_original_repr = fasttransform.transform.Transform.__repr__

def _safe_repr(self):
    try:
        return _original_repr(self)
    except AttributeError as e:
        if "'_BoundFunction' object has no attribute 'methods'" in str(e):
            return f"{self.__class__.__name__}(...)"
        raise

fasttransform.transform.Transform.__repr__ = _safe_repr

# %% ../../nbs/023_data.tfms.ipynb #12e03f1b
from fastai.vision.all import get_image_files
from typing import Callable
import re
from glob import glob as glob_expand

# %% ../../nbs/023_data.tfms.ipynb #472da9cc
def _glob_to_regex(pattern: str) -> str:
    pattern = re.escape(pattern)
    pattern = pattern.replace(r"\*", ".*")
    pattern = pattern.replace(r"\?", ".")
    pattern = pattern.replace(r"\[", "[")
    pattern = pattern.replace(r"\]", "]")
    return f"^{pattern}$"


def _build_filename_predicate(
    filename_filter: str|re.Pattern|Callable[[str], bool]
) -> Callable[[str], bool]:
    """
    Build a filename predicate function from the provided filter.
    """

    if isinstance(filename_filter, str):
        if any(c in filename_filter for c in "*?["):
            regex = re.compile(_glob_to_regex(filename_filter))
            return lambda name: regex.search(name) is not None
        return lambda name: filename_filter in name

    if isinstance(filename_filter, re.Pattern):
        return lambda name: filename_filter.search(name) is not None

    if callable(filename_filter):
        return filename_filter

    raise ValueError("Unsupported filename_filter type")


def get_images(
    path: str|Path,
    folders: str|list[str]|None = None,
    recurse: bool = True,
    filename_filter: str|re.Pattern|Callable[[str], bool]|None = None,
) -> L:
    """
    Get image files from a list of folders or a glob expression.
    """

    # Resolve folders
    if folders is None:
        files = get_image_files(path, recurse=recurse)
    else:
        if isinstance(folders, str):
            if any(c in folders for c in "*?["):
                expanded = sorted(glob_expand(os.path.join(path, folders)))
                img_folders = (
                    [os.path.basename(p) for p in expanded]
                    if expanded else [folders]
                )
            else:
                img_folders = [folders]
        else:
            img_folders = list(folders)

        files = get_image_files(path, folders=img_folders, recurse=recurse)

    # No filtering requested
    if filename_filter is None:
        return files

    # Build filtering function
    predicate = _build_filename_predicate(filename_filter)

    # Apply filtering
    filtered = L()
    for f in files:
        name = os.path.basename(f)
        if predicate(name):
            filtered.append(f)

    return filtered

# %% ../../nbs/023_data.tfms.ipynb #cc868a5b
def get_gt(path_gt, # The base directory where the ground truth files are stored, or a file path from which to derive the parent directory.
           gt_file_name="avg50.png", # The name of the ground truth file.
           ):
    """
    The `get_gt` function retrieves ground truth data, essential for supervised learning tasks. 
    It ensures that the correct labels or annotations are associated with each data sample.
    
    This function constructs a path to a ground truth file based on the given `path_gt` and `gt_file_name`.    
    It uses a lambda function to create a new path by appending `gt_file_name` to 
    the parent directory of the input file, as specified by `path_gt`.
    
    Returns a callable: A function that takes a single argument (a filename) and returns a Path object 
                   representing the full path to the ground truth file. When called with a filename, 
                   this function constructs the path by combining `path_gt` or the parent directory of 
                   the filename with `gt_file_name`. 
    """
    
    # Convert path_gt to Path object if it's a string
    path_gt = Path(path_gt)
    
    # Define the lambda function that constructs the full path
    _fn = lambda fn: path_gt / f"{Path(fn).parent}" / gt_file_name
    
    return _fn


# %% ../../nbs/023_data.tfms.ipynb #88481387
def get_target(path:str, # The base directory where the files are located. This should be a string representing an absolute or relative path.
               same_filename=True, #If True, the target file name will match the original file name; otherwise, it will use the specified prefix. 
               same_foldername=False, #If True, the target folder name will match the original folder name; otherwise, it will use the specified prefix.
               target_file_prefix="target", # The prefix to insert into the target file name if `same_filename` is False. 
               signal_file_prefix="signal", # The prefix used in the original file names that should be replaced by the target prefix.
               map_foldername=False, #If True, the target folder name will match the original folder name; otherwise, it will use the specified prefix. 
               target_folder_prefix="target", # The prefix to insert into the target folder name if `same_foldername` is False. 
               signal_folder_prefix="signal", # The prefix used in the original folder names that should be replaced by the target prefix. 
               relative_path=False, # If True, it indicates that the path is relative to the parent folder in the path where the input files are located.
               ):
    """
    Constructs and returns functions for generating file paths to "target" files based on given input parameters.
    
    This function defines two nested helper functions within its scope: \n
        - `construct_target_filename(file_name)`: Constructs a target file name by inserting the specified prefix into the original file name.
        - `generate_target_path(file_name)`: Generates a path to the target file based on whether `same_filename` is set to True or False.
    
    The main function returns the appropriate helper function based on the value of `same_filename`.
    
    Returns a callable: A function that takes a file name as input and returns its corresponding target file path based on the specified parameters.
    
    """
    # Define a function to construct the target file name based on input parameters
    def construct_target_filename(file_name):
        # Split the file name based on the signal file prefix
        parts = file_name.split(signal_file_prefix)   
        # Construct the target file name by inserting the target file prefix
        target_file_name = parts[0] + target_file_prefix + parts[1]
        
        return target_file_name
    
    def construct_target_foldername(folder_name):
        # Split the folder name based on the signal folder prefix
        parts = folder_name.split(signal_folder_prefix)
        # Construct the target folder name by inserting the target folder prefix
        target_folder_name = parts[0] + target_folder_prefix + parts[1]
        
        return target_folder_name
    
    # Define a function to generate the target file path based on the given file name
    def generate_target_path(file_name):
        
        if map_foldername:
            # Extract the folder name and replace the signal folder prefix with the target folder prefix
            folder_name = os.path.dirname(file_name)
            target_folder_name = Path(construct_target_foldername(folder_name))
        elif same_foldername:
            target_folder_name = Path(os.path.dirname(file_name))
        else:
            base_path = ''
            if relative_path:
                base_path = Path(file_name).parents[1]
            target_folder_name = base_path / Path(path)
                            
        # Extract the base file name
        base_filename = os.path.basename(file_name)
        
        # If same_filename is True, simply return the path joined with the base file name
        if same_filename:
            return target_folder_name / base_filename
        
        # If same_filename is False, construct the target file name and return the path joined with it
        target_filename = construct_target_filename(base_filename)
        return target_folder_name / target_filename
    
    # Return the appropriate function based on the value of same_filename
    return generate_target_path



# %% ../../nbs/023_data.tfms.ipynb #a9e836bd
def get_noisy_pair(fn):
    """
    Get another "noisy" version of the input file by selecting a file from the same directory.
    
    This function first retrieves all image files in the directory of the input file `fn` (excluding subdirectories). 
    It then selects one of these files at random, ensuring that it is not the original file itself to avoid creating a trivial "noisy" pair.
    
    Parameters: \n
        fn (Path or str): The path to the original image file. This should be a Path object but accepts string inputs for convenience.
    
    Returns: \n
        Path: A Path object pointing to the selected noisy file.
    
    """
    
    # Convert fn to Path object if it's not already one
    fn = Path(fn)
    
    # Get all image files in the parent directory of the input file
    tmp = get_image_files(fn.parent, recurse=False)
    
    # Select a random file from the list, ensuring it's not the original file
    fn2 = tmp[randint(0, len(tmp) - 1)]
    while fn2 == fn:
        fn2 = tmp[randint(0, len(tmp) - 1)]
    
    return fn2


# %% ../../nbs/023_data.tfms.ipynb #8a3daf33
@typedispatch
def show_batch(x: BioImageBase,     # The input image data.
               y: BioImageBase,     # The target image data.
               samples,             # List of sample indices to display.
               ctxs=None,           # List of contexts for displaying images. If None, create new ones using get_grid().
               max_n: int=9,       # Maximum number of samples to display. Default is 9.
               nrows: int|None=None,     # Number of rows in the grid if ctxs are not provided.
               ncols: int|None=None,     # Number of columns in the grid if ctxs are not provided.
               figsize: tuple|None=None, # Figure size for the image display.
               **kwargs,            # Additional keyword arguments to pass to the show method of BioImageBase.
               ):
    """
    Display a batch of images and their corresponding targets.
    
    Returns:
        List[Context]: A list of contexts after displaying the images and targets.
    """
    # If ctxs are not provided, create new ones using get_grid()
    if ctxs is None:
        ctxs = get_grid(min(len(samples), max_n), nrows=nrows, ncols=ncols, figsize=figsize, double=True)
    
    # Loop through the images and targets in pairs (x and y)
    for i in range(2):
        # Display each image-target pair in a specific context
        ctxs[i::2] = [b.show(ctx=c, **kwargs) for b, c, _ in zip(samples.itemgot(i), ctxs[i::2], range(max_n))]
    
    return ctxs


# %% ../../nbs/023_data.tfms.ipynb #7c68373c
from fastai.vision.all import TensorCategory

# %% ../../nbs/023_data.tfms.ipynb #b389c760
@typedispatch
def show_batch(x: BioImageBase,      # The input image data.
               y: TensorCategory,    # The target data (categorical labels).
               samples,              # List of sample indices to display.
               ctxs=None,            # List of contexts for displaying images. If None, create new ones using get_grid().
               max_n: int=9,        # Maximum number of samples to display. Default is 9.
               nrows: int|None=None,      # Number of rows in the grid if ctxs are not provided.
               ncols: int|None=None,      # Number of columns in the grid if ctxs are not provided.
               figsize: tuple|None=None,  # Figure size for the image display.
               **kwargs,             # Additional keyword arguments to pass to the show method of BioImageBase.
               ):
    """
    Display a batch of images with their corresponding labels as titles.
    
    Returns:
        List[Context]: A list of contexts after displaying the images and their labels.
    """
    # If ctxs are not provided, create new ones using get_grid()
    if ctxs is None: 
        ctxs = get_grid(min(len(samples), max_n), nrows=nrows, ncols=ncols, figsize=figsize)
    
    # Flatten the context in case it returns as an array
    if isinstance(ctxs, np.ndarray):
        ctxs = ctxs.flatten()
    
    # Extract the input images and the corresponding labels
    xs, ys = samples.itemgot(0), samples.itemgot(1)

    # Loop through the images and labels
    for i in range(len(xs)):
        # Display each input image
        ctxs[i] = xs[i].show(ctx=ctxs[i], title=f"Label: {ys[i]}", **kwargs)
    
    return ctxs

# %% ../../nbs/023_data.tfms.ipynb #bee716ba
@typedispatch
def show_batch(
    x: list[MetaTensor|torchTensor],   # inputs
    y: MetaTensor|torchTensor|list,    # targets
    samples: list|None=None,           # List of sample indices to display.
    ctxs=None,                         # List of contexts for displaying images. If None, create new ones using get_grid().
    max_n: int=9,                      # Maximum number of samples to display. Default is 9.
    nrows: int|None=None,      # Number of rows in the grid if ctxs are not provided.
    ncols: int|None=None,      # Number of columns in the grid if ctxs are not provided.
    figsize: tuple|None=None,  # Figure size for the image display.
    vocab=None,
    **kwargs
):
    """
    Show `max_n` inputs and targets from a batch.

    Supports both MetaTensor and torch.Tensor inputs.
    Converts to BioImage/BioImageMulti automatically.
    """

    # -------------------------
    # Create samples if not provided
    # -------------------------
    if samples is None:

        # Ensure x is a list
        if isinstance(x, (MetaTensor, torchTensor)):
            if x.ndim == 4:        # batch tensor
                x = [x[i] for i in range(len(x))]
            else:
                x = [x]

        elif isinstance(x, list) and isinstance(x[0], (MetaTensor, torchTensor)) and x[0].ndim > 3:
            # flatten batch dimension
            x = [t[i] for t in x for i in range(t.shape[0])]

        # -------------------------
        # Convert tensors → BioImage
        # -------------------------
        cls = BioImage if x[0].shape[0] == 1 else BioMultiChannel
        x_bio = [Tensor2BioImage(cls)(t) for t in x]

        # -------------------------
        # Convert y to list
        # -------------------------
        if isinstance(y, (MetaTensor, torchTensor)):
            if y.ndim == 0:
                y_list = [int(y)]
            else:
                y_list = [int(y[i]) for i in range(len(y))]
        else:
            y_list = list(y)

        if vocab is not None:
            y_list = [vocab[o] for o in y_list]

        samples = L(zip(x_bio, y_list))

    # -------------------------
    # Create grid if ctxs not provided
    # -------------------------
    if ctxs is None:
        ctxs = get_grid(min(len(samples), max_n), nrows=nrows, ncols=ncols, figsize=figsize)

    # -------------------------
    # Display
    # -------------------------
    for i, ((img, lbl), ax) in enumerate(zip(samples, ctxs)):
        if i >= max_n: break
        img.show(ctx=ax, **kwargs)
        ax.set_title(str(lbl), fontsize=10)

    return ctxs

# %% ../../nbs/023_data.tfms.ipynb #c5cef986
@typedispatch
def show_results(x: BioImageBase, # The input image data.
                 y: BioImageBase, # The target label data.
                 samples, # List of sample indices to display.
                 outs, # List of output predictions corresponding to the samples.
                 ctxs=None, # List of contexts for displaying images. If None, create new ones using get_grid().
                 max_n: int=10, # Maximum number of samples to display.
                 figsize: tuple|None=None, # Figure size for the image display.
                 **kwargs, # Additional keyword arguments to pass to the show method of BioImageBase.
                 ):
    """
    Display a batch of input images along with their predicted and target labels.
   
    Returns: \n
        List[Context]: A list of contexts after displaying the images and labels.
    """
    # If ctxs are not provided, create new ones using get_grid() with a specific title and size
    if ctxs is None: 
        ctxs = get_grid(3 * min(len(samples), max_n), ncols=3, figsize=figsize, title='Input/Target/Prediction')
    
    # Loop through the images and display them in a specific context for input (x) and output predictions (outs)
    for i in range(2):
        ctxs[i::3] = [b.show(ctx=c, **kwargs) for b, c, _ in zip(samples.itemgot(i), ctxs[i::3], range(max_n))]
    
    # Display the target labels (y) in a specific context after the input images
    ctxs[2::3] = [b.show(ctx=c, **kwargs) for b, c, _ in zip(outs.itemgot(0), ctxs[2::3], range(max_n))]
    
    return ctxs


# %% ../../nbs/023_data.tfms.ipynb #02818581
@typedispatch
def show_results(x: BioImageBase,       # The input image data.
                y: TensorCategory,      # The target data (categorical labels).
                samples,                # List of sample indices to display.
                outs,                   # List of output predictions corresponding to the samples.
                ctxs=None,              # List of contexts for displaying images. If None, create new ones using get_grid().
                max_n: int=10,               # Maximum number of samples to display.
                nrows: int|None=None,        # Number of rows in the grid if ctxs are not provided.
                ncols: int|None=None,        # Number of columns in the grid if ctxs are not provided.
                figsize: tuple|None=None,           # Figure size for the image display.
                **kwargs,               # Additional keyword arguments to pass to the show method of BioImageBase.
                ):
    """
    Display a batch of input images along with their predicted and target labels.
   
    Returns: \n
        List[Context]: A list of contexts after displaying the images and labels.
    """
    # If ctxs are not provided, create new ones using get_grid() with a specific title and size
    if ctxs is None: 
        ctxs = get_grid(min(len(samples), max_n), nrows=nrows, ncols=ncols, figsize=figsize, title='Target/Prediction')
    
    # Loop through the images and display them in a specific context for input (x) and output predictions (outs)
    for i in range(2):
        ctxs = [b.show(ctx=c, **kwargs) for b,c,_ in zip(samples.itemgot(i),ctxs,range(max_n))]
    
    # Display predictions and target labels (y) in green, when matching, or red, otherwise.
    ctxs = [r.show(ctx=c, color='green' if b==r else 'red', **kwargs)
            for b,r,c,_ in zip(samples.itemgot(1), outs.itemgot(0), ctxs, range(max_n))]
    
    return ctxs


# %% ../../nbs/023_data.tfms.ipynb #96d2aa11
@typedispatch
def show_results(dl: torchDataLoader,         # DataLoader containing the batch and optional vocab
                 batch: list,                # The batch of data from the DataLoader (inputs, targets)
                 preds: MetaTensor|torchTensor,          # Model predictions corresponding to the batch
                 ctxs=None,                  # Optional: list of axes to plot on. If None, created automatically
                 max_n: int=10,              # Maximum number of samples to display
                 nrows: int|None=None,       # Number of rows in the grid if ctxs are not provided
                 ncols: int|None=None,       # Number of columns in the grid if ctxs are not provided
                 figsize: tuple|None=None,   # Figure size for the display grid
                 **kwargs                     # Additional keyword arguments passed to `BioImage.show`
                ):
    """
    Display a batch of images with their ground truth labels and predicted labels.

    This version supports `BioImage` or `BioImageMulti` depending on input channels,
    and will use `dl.vocab` to convert integer class indices to class names if available.

    Args:
        dl (torchDataLoader): DataLoader providing the batch and optional `vocab`.
        batch (list): A tuple/list `(x, y)` containing input tensors and labels.
        preds (MetaTensor): Model outputs for the batch.
        ctxs (list, optional): Predefined plotting axes. If None, axes are created automatically.
        max_n (int): Maximum number of samples to display.
        nrows (int | None): Number of rows in the grid if ctxs not provided.
        ncols (int | None): Number of columns in the grid if ctxs not provided.
        figsize (tuple | None): Figure size for the display grid.
        **kwargs: Additional arguments to pass to `BioImage.show`.

    Returns:
        list: List of matplotlib axes containing the displayed images with labels.
    """

    x, y = batch

    # Choose the right BioImage class based on channels
    cls = BioImage if x[0].shape[0]==1 else BioMultiChannel
    x_bio = [Tensor2BioImage(cls)(t) for t in x]

    # Convert predictions and labels to lists
    y_list = y.tolist()
    preds_list = TensorCategory(preds).tolist()

    # Map indices to class names if DataLoader has vocab
    if hasattr(dl, 'vocab') and dl.vocab is not None:
        y_list = [dl.vocab[o] for o in y_list]
        preds_list = [dl.vocab[o] for o in preds_list]

    # Combine images and true labels
    samples = L(zip(x_bio, y_list))

    # Create grid of axes if not provided
    if ctxs is None:
        ctxs = get_grid(min(len(samples), max_n), nrows=nrows, ncols=ncols, 
                        figsize=figsize, title="Target / Prediction")

    # Display images and overlay text for GT vs Pred
    for i, ((img, true_label), pred_label) in enumerate(zip(samples, preds_list)):
        if i >= max_n: break
        ax = ctxs[i]
        img.show(ctx=ax, **kwargs)
        color = 'green' if true_label == pred_label else 'red'
        ax.set_title(f"{true_label} / {pred_label}", color=color, fontsize=10)

    return ctxs

# %% ../../nbs/023_data.tfms.ipynb #8d7f5f52
def _save_csv(df: pd.DataFrame, path: str) -> None:
    df.to_csv(path, index=False)


def _add_column(
    df: pd.DataFrame,
    column_name: str,
    value,
) -> pd.DataFrame:
    df = df.copy()
    df[column_name] = value
    return df


def _save_separate(
    train_df: pd.DataFrame,
    test_df: pd.DataFrame,
    valid_df: Optional[pd.DataFrame],
    save_dir: str,
    train_path: str,
    test_path: str,
    valid_path: str,
) -> None:

    _save_csv(train_df, os.path.join(save_dir, train_path))
    _save_csv(test_df, os.path.join(save_dir, test_path))

    if valid_df is not None:
        _save_csv(valid_df, os.path.join(save_dir, valid_path))


def _save_single(
    train_df: pd.DataFrame,
    test_df: pd.DataFrame,
    valid_df: Optional[pd.DataFrame],
    save_dir: str,
    combined_path: str,
    split_column: str,
) -> None:

    dfs = [
        _add_column(train_df, split_column, "train"),
        _add_column(test_df, split_column, "test"),
    ]

    if valid_df is not None:
        dfs.append(
            _add_column(valid_df, split_column, "valid")
        )

    combined_df = pd.concat(dfs, ignore_index=True)

    _save_csv(
        combined_df,
        os.path.join(save_dir, combined_path),
    )


def _save_train_valid_together(
    train_df: pd.DataFrame,
    test_df: pd.DataFrame,
    valid_df: Optional[pd.DataFrame],
    save_dir: str,
    test_path: str,
    train_valid_path: str,
    is_valid_column: str,
) -> None:

    # Save test separately
    _save_csv(
        test_df,
        os.path.join(save_dir, test_path),
    )

    dfs = [
        _add_column(
            train_df,
            is_valid_column,
            False,
        )
    ]

    if valid_df is not None:
        dfs.append(
            _add_column(
                valid_df,
                is_valid_column,
                True,
            )
        )

    train_valid_df = pd.concat(dfs, ignore_index=True)

    _save_csv(
        train_valid_df,
        os.path.join(save_dir, train_valid_path),
    )


# %% ../../nbs/023_data.tfms.ipynb #26b3ab24
def split_dataframe(
    input_data: Union[str, pd.DataFrame],
    splitter: Callable = RandomSplitter,
    save_mode: str = "separate",
    split_column: str = "split",
    is_valid_column: str = "is_valid",
    train_path: str = "train.csv",
    test_path: str = "test.csv",
    valid_path: str = "valid.csv",
    combined_path: str = "dataset.csv",
    train_valid_path: str = "train_valid.csv",
    data_save_path: Optional[str] = None,
    **kwargs,
) -> tuple:
    """
    Split a dataset into multiple subsets.

    The input dataset can be provided either as a pandas DataFrame
    or as a path to a CSV file. The splitting logic is delegated to
    the provided ``splitter`` callable.

    The splitter may return either:

    - ``(train_df, valid_df)``
    - ``(train_df, valid_df, test_df)``

    The resulting datasets can optionally be saved in different formats:

    - ``"separate"``
        Save each split as an individual CSV file.

    - ``"single"``
        Save all splits into a single CSV file with an additional
        column identifying the split name.

    - ``"train_valid_together"``
        Save the test set separately while combining train and
        validation datasets into one CSV file with an ``is_valid``
        boolean column.

    Args:
        input_data:
            Input dataset as either a pandas DataFrame or a CSV file path.

        splitter:
            Callable responsible for splitting the dataset.

        save_mode:
            Saving strategy for output datasets.
            One of:
            ``"separate"``,
            ``"single"``,
            ``"train_valid_together"``.

        split_column:
            Column name used when ``save_mode="single"``.

        is_valid_column:
            Column name used when
            ``save_mode="train_valid_together"``.

        train_path:
            Filename for the train dataset.

        test_path:
            Filename for the test dataset.

        valid_path:
            Filename for the validation dataset.

        combined_path:
            Filename used when saving all splits into one file.

        train_valid_path:
            Filename used when saving combined
            train + validation data.

        data_save_path:
            Directory where datasets will be saved.
            If ``None``, datasets are not saved.

        **kwargs:
            Additional keyword arguments passed to the splitter.

    Returns:
        tuple:
            Split datasets returned by the splitter.

    Raises:
        TypeError:
            If ``input_data`` is neither a DataFrame nor a file path.

        ValueError:
            If ``save_mode`` is invalid or the splitter
            returns an unsupported number of outputs.
    """

    # ---------------------------------
    # Load dataset
    # ---------------------------------
    if isinstance(input_data, str):
        df = pd.read_csv(input_data)

    elif isinstance(input_data, pd.DataFrame):
        df = input_data.copy()

    else:
        raise TypeError(
            "input_data must be a file path "
            "or pandas DataFrame"
        )

    print("Splitting dataset...")

    splits = splitter(**kwargs)(df)

    if not isinstance(splits, (tuple, list)):
        raise ValueError(
            "splitter must return a tuple/list"
        )

    if len(splits) == 2:
        train_df, test_df = splits
        valid_df = None

    elif len(splits) == 3:
        train_df, valid_df, test_df = splits

    else:
        raise ValueError(
            "splitter must return either "
            "(train, valid) or "
            "(train, valid, test)"
        )

    # ---------------------------------
    # Save datasets
    # ---------------------------------
    if data_save_path:

        os.makedirs(data_save_path, exist_ok=True)

        save_handlers = {
            "separate": lambda: _save_separate(
                train_df=train_df,
                test_df=test_df,
                valid_df=valid_df,
                save_dir=data_save_path,
                train_path=train_path,
                test_path=test_path,
                valid_path=valid_path,
            ),

            "single": lambda: _save_single(
                train_df=train_df,
                test_df=test_df,
                valid_df=valid_df,
                save_dir=data_save_path,
                combined_path=combined_path,
                split_column=split_column,
            ),

            "train_valid_together": lambda:
                _save_train_valid_together(
                    train_df=train_df,
                    test_df=test_df,
                    valid_df=valid_df,
                    save_dir=data_save_path,
                    test_path=test_path,
                    train_valid_path=train_valid_path,
                    is_valid_column=is_valid_column,
                ),
        }

        if save_mode not in save_handlers:
            raise ValueError(
                "save_mode must be one of: "
                "'separate', "
                "'single', "
                "'train_valid_together'"
            )

        save_handlers[save_mode]()

        print(f"Datasets saved to {data_save_path}")

    return splits

# %% ../../nbs/023_data.tfms.ipynb #1e42b2d6
def build_df(
    filenames: Union[list[str|Path], L],                 # List of file names to process
    *functions: Callable[[str], str],               # One or more functions that take a filename and return a string (e.g., for generating target paths).
    function_names: Optional[Union[List[str], L]] = None,     # Optional column names for the function outputs. If None, function.__name__ is used.
    filename_col: str = "filename",                            # Column name for the input filenames.
    output_csv: Optional[str|Path] = None,               # If provided, saves the full dataframe to this CSV path.
    split: bool = False,                            # If True, applies split_dataframe to the generated dataframe.
    split_kwargs: Optional[dict] = None,            # Keyword arguments passed to split_dataframe.
) -> Union[
    pd.DataFrame,
    tuple[pd.DataFrame, pd.DataFrame, Optional[pd.DataFrame]]
]:
    
    """
    Create a DataFrame from filenames and one or more transformation functions.
    """

    if function_names and len(function_names) != len(functions):
        raise ValueError("Length of function_names must match number of functions.")

    # Determine column names
    if function_names is None:
        column_names = [
            f.__name__ if hasattr(f, "__name__") else f"func_{i}"
            for i, f in enumerate(functions)
        ]
    else:
        column_names = function_names

    # Build dataframe
    data = {filename_col: filenames}

    for col_name, func in zip(column_names, functions):
        data[col_name] = [func(fname) for fname in filenames]

    df = pd.DataFrame(data)

    # Save full dataset if requested
    if output_csv:
        df.to_csv(output_csv, index=False)

    # Apply splitting if requested
    if split:
        split_kwargs = split_kwargs or {}
        return split_dataframe(df, **split_kwargs)

    return df

# %% ../../nbs/023_data.tfms.ipynb #02b16df9
def build_df_from_folder(
    path: str|Path,
    *functions: Callable[[str], str],               # One or more functions that take a filename and return a string (e.g., for generating target paths).
    function_names: Optional[Union[List[str], L]] = None,     # Optional column names for the function outputs. If None, function.__name__ is used.
    output_csv: Optional[str|Path] = None,               # If provided, saves the full dataframe to this CSV path.
    subfolders: str|list[str]|None = None,
    recurse: bool = True,
    filename_filter: str|re.Pattern|Callable[[str], bool]|None = None,
    split: bool = False,                            # If True, applies split_dataframe to the generated dataframe.
    split_kwargs: Optional[dict] = None,            # Keyword arguments passed to split_dataframe.
) -> Union[
    pd.DataFrame,
    tuple[pd.DataFrame, pd.DataFrame, Optional[pd.DataFrame]]
]:
    """
    Create a DataFrame from filenames and one or more transformation functions.
    """

    filenames = get_images(path, subfolders, recurse, filename_filter)
    return build_df(filenames, *functions, 
                    function_names=function_names,
                    output_csv=output_csv, 
                    split=split, 
                    split_kwargs=split_kwargs)

# %% ../../nbs/023_data.tfms.ipynb #fd1ae9aa
SlidingWindowSplitter = SlidingWindowSplitter

# %% ../../nbs/023_data.tfms.ipynb #28ac83da
def _select_transforms(transforms, keys):
    if transforms is None:
        return None
    return [fn for fn in transforms if set(fn.keys) & set(keys)]
    
def _resolve_columns(df, colmap):
    if colmap:
        keys = list(colmap.keys())

        if len(keys) < 2:
            raise ValueError("colmap must have at least two keys")

        input_key, target_key = keys[:2]
        df = df[[input_key, target_key]].copy()

    else:
        input_key, target_key = "input", "target"
        df = df[[df.columns[0], df.columns[1]]].copy()
        df.columns = [input_key, target_key]

    return input_key, target_key, df

def _store_metadata(group, meta, patch_size, patch_transforms):
    for k, v in meta.items():
        group.attrs[k] = str(v)

    group.attrs["patch_size"] = str(patch_size)
    group.attrs["affine"] = meta["affine"]

    patch_transforms_info = "None"

    if patch_transforms is not None:
        patch_transforms_info = {
            tfm.__class__.__name__: _sanitize(tfm)
            for tfm in patch_transforms
        }

    group.attrs["patch_transforms"] = str(patch_transforms_info)

def _get_image_name(path):
    return os.path.splitext(os.path.basename(path))[0]


# %% ../../nbs/023_data.tfms.ipynb #0d381dff
def _process_single_image(
    row,
    hf,
    split_name,
    input_key,
    target_key,
    patch_size,
    image_splitter,
    image_transforms,
    patch_transforms,
    patch_list,
    compression,
    input_class,
    target_class,
    **kwargs,
):

    image_name = _get_image_name(row[input_key])

    # --------------------------------------------------
    # Load images
    # --------------------------------------------------
    image_reader_kwargs = route_kwargs(image_reader, kwargs)
    row = input_class.create(
        row, keys=[input_key], transforms=_select_transforms(image_transforms, [input_key]), **image_reader_kwargs
    )
    row = target_class.create(
        row, keys=[target_key], transforms=_select_transforms(image_transforms, [target_key]), **image_reader_kwargs
    )

    input_metatensor = row[input_key]
    gt_metatensor = row[target_key]

    data_img, data_meta = input_metatensor.data, input_metatensor.meta
    gt_img, gt_meta = gt_metatensor.data, gt_metatensor.meta

    # --------------------------------------------------
    # Validate shapes
    # --------------------------------------------------
    if data_img.shape != gt_img.shape:
        if data_img.shape[-2:] != gt_img.shape[-2:]:
            raise ValueError(f"Shape mismatch: {data_img.shape} vs {gt_img.shape}")
        gt_patch_size = patch_size[-2:]
    else:
        gt_patch_size = patch_size

    # --------------------------------------------------
    # Create splitter
    # --------------------------------------------------
    splitter_kwargs = route_kwargs(image_splitter, kwargs)
    splitter = image_splitter(patch_size=patch_size, **splitter_kwargs)

    patches = splitter(data_img)

    # --------------------------------------------------
    # Create HDF5 groups
    # --------------------------------------------------
    base = f"{split_name}/{image_name}"

    x_group = hf.require_group(f"{base}/X")
    y_group = hf.require_group(f"{base}/y")

    _store_metadata(x_group, data_meta, patch_size, patch_transforms)
    _store_metadata(y_group, gt_meta, gt_patch_size, patch_transforms)

    # --------------------------------------------------
    # Save patches
    # --------------------------------------------------
    for idx, (data_patch, loc) in enumerate(patches):

        gt_patch = splitter._get_patch(
            gt_img, location=loc, patch_size=gt_patch_size
        )

        if patch_transforms:
            patch_dict = {input_key: data_patch, target_key: gt_patch}
            for tfm in patch_transforms:
                patch_dict = tfm(patch_dict)
            data_patch = patch_dict[input_key]
            gt_patch = patch_dict[target_key]

        x_ds = f"{base}/X/{idx}"
        y_ds = f"{base}/y/{idx}"

        hf.create_dataset(x_ds, data=data_patch, compression=compression)
        hf.create_dataset(y_ds, data=gt_patch, compression=compression)

        hf[x_ds].attrs["patch_location"] = str(loc)
        hf[y_ds].attrs["patch_location"] = str(loc)

        # Store the pair in the provided list instead of returning immediately
        patch_list.append({
            input_key: x_ds,
            target_key: y_ds,
            "image_name": image_name,
            "split": split_name,
            "patch_idx": idx,
            "location": loc
        })


# %% ../../nbs/023_data.tfms.ipynb #b6f9d525
def _load_dataset_dataframe(
    data_paths,
    colmap=None,
):
    "Load dataset metadata into a DataFrame."

    return pd.DataFrame(
        BioDataLoaders._load_data(
            data_paths,
            {'colmap': colmap},
        )
    )


def _build_dataset_splits(
    df,
    splitter=None,
    **kwargs,
):
    """
    Build dataset splits from splitter indices.

    Returns:
        dict:
            Mapping of split name -> DataFrame
    """

    if splitter is None:
        return {"all": df}

    # ------------------------------------------
    # Get split indices
    # ------------------------------------------
    split_idxs = split_dataframe(
        df,
        splitter=splitter,
        **kwargs,
    )

    split_names = getattr(
        splitter(**kwargs),
        "split_names",
        None,
    )

    # ------------------------------------------
    # Default split names
    # ------------------------------------------
    if split_names is None:

        split_names = (
            ("train", "valid")
            if len(split_idxs) == 2
            else ("train", "valid", "test")
        )

    # ------------------------------------------
    # Convert idxs -> DataFrames
    # ------------------------------------------
    splits = {}

    for name, idxs in zip(
        split_names,
        split_idxs,
    ):

        splits[name] = (
            df.iloc[idxs]
            .reset_index(drop=True)
        )

    return splits


def _save_patch_csv(
    patches,
    output_folder,
    csv_filename,
):
    "Save patch metadata CSV."

    csv_path = os.path.join(
        output_folder,
        csv_filename,
    )

    pd.DataFrame(patches).to_csv(
        csv_path,
        index=False,
    )

    print(
        "Patch information saved to CSV: "
        f"{csv_path}"
    )



# %% ../../nbs/023_data.tfms.ipynb #1c350e06
def ProcessImageDataset(
    data_paths,
    output_folder,
    output_filename,
    patch_size,
    input_class=BioImageBase,
    target_class=BioImageBase,
    image_splitter=SlidingWindowSplitter,
    splitter=RandomSplitter,
    colmap=None,
    csv=True,
    csv_filename=None,
    image_transforms=None,
    patch_transforms=None,
    compression=None,
    **kwargs
):
    """
    Prepare an image dataset by:

    1. Loading dataset metadata
    2. Optionally splitting the dataset
    3. Extracting patches
    4. Saving patches into HDF5
    5. Optionally saving patch metadata CSV
    """

    os.makedirs(output_folder, exist_ok=True)

    # ------------------------------------------
    # Load dataset
    # ------------------------------------------
    df = _load_dataset_dataframe(
        data_paths,
        colmap,
    )

    input_key, target_key, df = _resolve_columns(
        df,
        colmap,
    )

    # ------------------------------------------
    # Build splits
    # ------------------------------------------
    splits = _build_dataset_splits(
        df=df,
        splitter=splitter,
        **kwargs,
    )

    # ------------------------------------------
    # Create HDF5 dataset
    # ------------------------------------------
    h5_path = os.path.join(
        output_folder,
        f"{output_filename}.h5",
    )

    all_patches = []

    with h5py.File(h5_path, "w") as hf:

        for split_name, split_df in splits.items():

            print(f"\nProcessing split: {split_name}")

            for row in tqdm(
                split_df.to_dict("records")
            ):

                _process_single_image(
                    row=row,
                    hf=hf,
                    split_name=split_name,
                    input_key=input_key,
                    target_key=target_key,
                    patch_size=patch_size,
                    patch_list=all_patches,
                    image_splitter=image_splitter,
                    image_transforms=image_transforms,
                    patch_transforms=patch_transforms,
                    compression=compression,
                    input_class=input_class,
                    target_class=target_class,
                    **kwargs,
                )

    print(
        "\nDataset processing complete. "
        f"HDF5 file saved to: {h5_path}"
    )

    # ------------------------------------------
    # Save CSV metadata
    # ------------------------------------------
    if csv:

        csv_filename = (
            csv_filename
            or f"{output_filename}.csv"
        )

        _save_patch_csv(
            patches=all_patches,
            output_folder=output_folder,
            csv_filename=csv_filename,
        )
